"""Seed data for the build designer option catalog.

The catalog intentionally contains pragmatic, UX-oriented presets rather than a
perfect game database. Public sources are incomplete for some upgrade names, so
rows use source notes to separate documented items from community/meta inspired
options.
"""

ITEMS_SOURCE_URL = "https://world-of-sea-battle.fandom.com/wiki/Items"
SHIPS_SOURCE_URL = "https://world-of-sea-battle.fandom.com/wiki/Ships"
UPDATE_B17_SOURCE_URL = "https://www.worldofseabattle.com/en/news/e798b1c0-2954-4fb0-9c2c-7c42239960fc"
COMMUNITY_SOURCE_URL = "https://steamcommunity.com/app/2948190/discussions/0/824857476142740596/"
PLANNER_SOURCE_URL = "https://wosbplanner.com/buildmaker?lang=en"

DOCUMENTED_ITEMS_NOTE = "Documented item/category in the public World of Sea Battle Wiki item overview."
SHIP_STATS_NOTE = "Filtered using public ship stats/classes/rates from the World of Sea Battle Wiki ship overview."
OFFICIAL_SLOT_NOTE = "Slot guidance follows official Update B17 notes: sail slot, upgrade slots, special upgrade slot, and equipment presets."
COMMUNITY_NOTE = "Community/meta-inspired option; keep editable because exact values may change by patch."
UX_NOTE = "UX preset derived from documented game systems; intended as editable planner guidance."

BUILD_OPTION_SEED_DATA: list[dict] = [
    # Sail / sail-slot options.
    {
        "category": "sail",
        "name": "Small Additional Sails",
        "description": "Kurzzeitiger Mobilitäts-/Speed-Baustein für kleinere oder leichtere Schiffe.",
        "effect_hint": "Mobilität / Flucht / Chase",
        "max_rate": 7,
        "source_url": ITEMS_SOURCE_URL,
        "source_note": DOCUMENTED_ITEMS_NOTE,
    },
    {
        "category": "sail",
        "name": "Large Additional Sails",
        "description": "Starker Segel-/Speed-Baustein für größere Schiffe und längere Gefechte.",
        "effect_hint": "Speed-Burst / Positionierung",
        "source_url": ITEMS_SOURCE_URL,
        "source_note": DOCUMENTED_ITEMS_NOTE,
    },
    {
        "category": "sail",
        "name": "Elite Sails",
        "description": "Meta-orientierter Speed-Slot für Builds, die Cruise-Speed und Positionierung priorisieren.",
        "effect_hint": "Speed / Positionierung",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
    },
    {
        "category": "sail",
        "name": "Imported Sails",
        "description": "Situativer High-End-Speed-Slot für Spezialfälle und schnelle Hulls.",
        "effect_hint": "High-End Speed",
        "progression_class": "Fast",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
    },
    # Core upgrades.
    {
        "category": "upgrade",
        "name": "Structural Expansion",
        "description": "Erweitert den Upgrade-Spielraum, kostet aber Beweglichkeit; besonders interessant für schwere/Transport-Builds.",
        "effect_hint": "Mehr Slots / weniger Agilität",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
        "is_default": True,
    },
    {
        "category": "upgrade",
        "name": "Ammunition Cradles",
        "description": "Reload-orientiertes Kanonen-Upgrade für konstantes Feuer.",
        "effect_hint": "Cannon Reload",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
        "is_default": True,
    },
    {
        "category": "upgrade",
        "name": "Incendiary Mixture",
        "description": "Offensives Setup für Brandschaden bzw. stärkeren Standardbeschuss.",
        "effect_hint": "Offense / Fire Pressure",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
    },
    {
        "category": "upgrade",
        "name": "Emergency Powder Charge",
        "description": "Risikoreiches Damage-Upgrade für kritische Situationen.",
        "effect_hint": "Damage bei Low-HP",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
    },
    {
        "category": "upgrade",
        "name": "Maneuverable Helm",
        "description": "Mobilitäts-/Wendigkeitsslot für Scout, Chase und Kiting.",
        "effect_hint": "Mobility",
        "progression_class": "Fast",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
    },
    {
        "category": "upgrade",
        "name": "Fortified Ports",
        "description": "Reichweitenorientiertes Kanonen-Upgrade für Distanzdruck.",
        "effect_hint": "Cannon Range",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
    },
    {
        "category": "upgrade",
        "name": "Copper Plating",
        "description": "Defensiver Hull-Baustein; sinnvoll für Linie, Tank und Heavy-Builds.",
        "effect_hint": "Defense",
        "progression_class": "Heavy",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
    },
    {
        "category": "upgrade",
        "name": "Strong Frames",
        "description": "Defensiver Struktur-Baustein für lange Gefechte.",
        "effect_hint": "Durability / Defense",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
    },
    {
        "category": "upgrade",
        "name": "Double Hold",
        "description": "Laderaumfokus für Transport- und Handelsbuilds.",
        "effect_hint": "Cargo Capacity",
        "progression_class": "Transport",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
    },
    {
        "category": "upgrade",
        "name": "Cellars",
        "description": "Stauraum-/Versorgungs-Upgrade für Handels- und Langfahrten.",
        "effect_hint": "Cargo / Supplies",
        "progression_class": "Transport",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
    },
    {
        "category": "upgrade",
        "name": "Lightweight Hull",
        "description": "Mobilitätslastiger Hull-Baustein für Transport oder schnelle Schiffe.",
        "effect_hint": "Speed / Handling",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
    },
    {
        "category": "upgrade",
        "name": "Repairs Arsenal",
        "description": "Reparatur- und Sustain-orientierter Slot für längere PvE/PvP-Fahrten.",
        "effect_hint": "Sustain / Repair",
        "source_url": COMMUNITY_SOURCE_URL,
        "source_note": COMMUNITY_NOTE,
    },
    # Special upgrade slot suggestions.
    {
        "category": "special_upgrade",
        "name": "Special Slot: Reload Feintuning",
        "description": "Spezialslot mit kleinem Fokus auf Reload; passend für Damage-Builds.",
        "effect_hint": "Special Slot / Reload",
        "source_url": UPDATE_B17_SOURCE_URL,
        "source_note": OFFICIAL_SLOT_NOTE,
    },
    {
        "category": "special_upgrade",
        "name": "Special Slot: Mobility Feintuning",
        "description": "Spezialslot mit Mobilitätsfokus; passend für Scout, Fast und Chase.",
        "effect_hint": "Special Slot / Mobility",
        "source_url": UPDATE_B17_SOURCE_URL,
        "source_note": OFFICIAL_SLOT_NOTE,
    },
    {
        "category": "special_upgrade",
        "name": "Special Slot: Durability Feintuning",
        "description": "Spezialslot mit defensivem Fokus; passend für Linie, Heavy und Tank.",
        "effect_hint": "Special Slot / Defense",
        "source_url": UPDATE_B17_SOURCE_URL,
        "source_note": OFFICIAL_SLOT_NOTE,
    },
    # Cannons / weapons from documented items.
    {"category": "cannon", "name": "Standard Cannons", "description": "Zuverlässige Midrange-Bewaffnung.", "effect_hint": "Allround", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "cannon", "name": "Long Cannons / Culverins", "description": "Reichweiten- und Präzisionsfokus.", "effect_hint": "Range", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "cannon", "name": "Carronades", "description": "Kurzdistanz-Burst und Nahkampfdruck.", "effect_hint": "Close Range", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "cannon", "name": "Bombards / Siege Weapons", "description": "Schwere Waffen für Siege-/Heavy-Situationen.", "effect_hint": "Siege / Heavy", "progression_class": "Siege", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "cannon", "name": "Mortars", "description": "Mörser-Setup für Schiffe mit passender Modifikation.", "effect_hint": "Mortar / Siege", "progression_class": "Siege", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "cannon", "name": "Alchemical Fire", "description": "Spezialwaffe mit Arc-/Flächenfokus.", "effect_hint": "Special Weapon", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "cannon", "name": "Imperial Bombard", "description": "Schwere Spezialbewaffnung für besondere Builds.", "effect_hint": "Special Weapon / Heavy", "progression_class": "Imperial", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    # Ammunition.
    {"category": "ammunition", "name": "Round Shots", "description": "Standardmunition für konstanten Schaden.", "effect_hint": "Standard Damage", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE, "is_default": True},
    {"category": "ammunition", "name": "Heated Shots", "description": "Brand-/Druckoption gegen passende Ziele.", "effect_hint": "Fire Pressure", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "ammunition", "name": "Bar Shots", "description": "Kontrolle gegen Segel und Beweglichkeit.", "effect_hint": "Sail Control", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "ammunition", "name": "Grapeshot", "description": "Nahbereich/Boarding-Vorbereitung gegen Crew.", "effect_hint": "Boarding Setup", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "ammunition", "name": "Strike Rounds", "description": "Experimentelle Damage-Munition.", "effect_hint": "Burst", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "ammunition", "name": "Shrapnel Rounds", "description": "Streuung/Flächendruck für spezielle Ziele.", "effect_hint": "Area Pressure", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "ammunition", "name": "Phosphorous Shots", "description": "Spezialmunition für Debuff-/Drucksituationen.", "effect_hint": "Debuff / Pressure", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "ammunition", "name": "Burning Arrows", "description": "Feuerorientierte Spezialmunition.", "effect_hint": "Fire", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "ammunition", "name": "Small Gunpowder Barrels", "description": "Taktische Payload für Kontrolle und Zonen.", "effect_hint": "Payload", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "ammunition", "name": "Small Flaming Barrels", "description": "Feuer-Payload für Engstellen und Rückzug.", "effect_hint": "Payload / Fire", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "ammunition", "name": "Large Shrapnel Mines", "description": "Minen-Payload für Raumkontrolle.", "effect_hint": "Mine / Area Control", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "ammunition", "name": "Large Phosphorous Mine", "description": "Minen-Payload mit Phosphor-Druck.", "effect_hint": "Mine / Debuff", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "ammunition", "name": "Fire Ship", "description": "Riskante taktische Spezialoption.", "effect_hint": "Special Payload", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    # Consumables.
    {"category": "consumable", "name": "Wooden Patches", "description": "Basis-Reparatur für Einsteiger und kleine Schiffe.", "effect_hint": "Repair", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Iron Patches", "description": "Solide Reparaturreserve für Combat/PvP.", "effect_hint": "Repair", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE, "is_default": True},
    {"category": "consumable", "name": "Bronze Patches", "description": "Höherwertige Reparaturreserve.", "effect_hint": "Repair", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Wreckage Patches", "description": "Notfall-Reparaturoption.", "effect_hint": "Emergency Repair", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Wooden Repair Kit", "description": "Reparaturkit für längere Fahrten.", "effect_hint": "Repair Kit", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Iron Repair Kit", "description": "Stärkeres Reparaturkit für Combat-Builds.", "effect_hint": "Repair Kit", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Field Kit", "description": "Feld-/Notfallkit für Gefechtsfenster.", "effect_hint": "Emergency", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Smoke Bomb", "description": "Taktisches Tool für Rückzug und Sichtlinie.", "effect_hint": "Escape / Control", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Smoke Screen", "description": "Größere Rauchoption für Gruppen und Rückzüge.", "effect_hint": "Escape / Group Utility", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Black Double Powder", "description": "Damage-/Druck-Verbrauchsgut.", "effect_hint": "Damage Buff", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Red Double Powder", "description": "Situativer Damage-/Druck-Buff.", "effect_hint": "Damage Buff", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "White Double Powder", "description": "Situativer Powder-Buff.", "effect_hint": "Buff", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Rum Ration", "description": "Crew-/Sustain-orientierter Buff.", "effect_hint": "Crew / Sustain", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Filling Ration", "description": "Crew-/Versorgungs-Buff für längere Kämpfe.", "effect_hint": "Crew / Sustain", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Phosphorous", "description": "Spezial-Verbrauchsgut für Debuff-/Druckspiel.", "effect_hint": "Debuff", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Powder Charge", "description": "Offensives Verbrauchsgut für Burst-Fenster.", "effect_hint": "Burst", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Poseidon's Hook", "description": "Taktisches Utility-Item.", "effect_hint": "Utility", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Blue Signal Flare", "description": "Signal-/Gruppenutility.", "effect_hint": "Signal", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Red Signal Flare", "description": "Signal-/Gruppenutility.", "effect_hint": "Signal", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Yellow Signal Flare", "description": "Signal-/Gruppenutility.", "effect_hint": "Signal", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "consumable", "name": "Horn", "description": "Taktisches Utility-Item.", "effect_hint": "Utility", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    # Crew and special crew planner rows.
    {"category": "crew_focus", "name": "Fill max with Sailors", "description": "Crew zunächst bis zur Schiffskapazität auffüllen.", "effect_hint": "Regular Crew", "source_url": PLANNER_SOURCE_URL, "source_note": UX_NOTE, "is_default": True},
    {"category": "crew_focus", "name": "Kanoniere priorisieren", "description": "Crewverteilung auf Reload und konstantes Feuer ausrichten.", "effect_hint": "Gunnery", "source_url": SHIPS_SOURCE_URL, "source_note": SHIP_STATS_NOTE},
    {"category": "crew_focus", "name": "Reparaturcrew priorisieren", "description": "Mehr Fokus auf Sustain und Schadenskontrolle.", "effect_hint": "Repair", "source_url": SHIPS_SOURCE_URL, "source_note": SHIP_STATS_NOTE},
    {"category": "crew_focus", "name": "Segelhandling priorisieren", "description": "Crewfokus für Manöver, Chase und Rückzug.", "effect_hint": "Sailing", "progression_class": "Fast", "source_url": SHIPS_SOURCE_URL, "source_note": SHIP_STATS_NOTE},
    {"category": "crew_focus", "name": "Boarding-Crew priorisieren", "description": "Crewfokus für Enteraktionen und Nahkampf.", "effect_hint": "Boarding", "source_url": SHIPS_SOURCE_URL, "source_note": SHIP_STATS_NOTE},
    {"category": "special_crew", "name": "Explorer Crew", "description": "Utility-orientierte Spezialcrew für Erkundung und Funde.", "effect_hint": "Exploration", "source_url": PLANNER_SOURCE_URL, "source_note": UX_NOTE},
    {"category": "special_crew", "name": "Old Hand", "description": "Community-erwähnte Sustain-Spezialcrew für PvE-Farming.", "effect_hint": "Sustain", "source_url": COMMUNITY_SOURCE_URL, "source_note": COMMUNITY_NOTE},
    {"category": "special_crew", "name": "Repair Specialist", "description": "Spezialcrew-Slot für Reparatur/Sustain-Setups.", "effect_hint": "Repair", "source_url": PLANNER_SOURCE_URL, "source_note": UX_NOTE},
    {"category": "special_crew", "name": "Gunnery Specialist", "description": "Spezialcrew-Slot für Kanonen-/Damage-Setups.", "effect_hint": "Gunnery", "source_url": PLANNER_SOURCE_URL, "source_note": UX_NOTE},
    {"category": "special_crew", "name": "Boarding Specialist", "description": "Spezialcrew-Slot für Boarding-Builds.", "effect_hint": "Boarding", "source_url": PLANNER_SOURCE_URL, "source_note": UX_NOTE},
    {"category": "special_crew", "name": "Navigator / Helmsman", "description": "Spezialcrew-Slot für Speed, Handling und Scout-Fahrweise.", "effect_hint": "Mobility", "progression_class": "Fast", "source_url": PLANNER_SOURCE_URL, "source_note": UX_NOTE},
    # Cargo / hold contents.
    {"category": "cargo", "name": "Repair Materials", "description": "Reparaturmaterial und Vorräte als Standardladung.", "effect_hint": "Sustain", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE, "is_default": True},
    {"category": "cargo", "name": "Wood", "description": "Rohmaterial für Reparatur/Handel/Crafting.", "effect_hint": "Material", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "cargo", "name": "Iron", "description": "Verarbeitetes Material für Crafting/Schiffbau.", "effect_hint": "Material", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "cargo", "name": "Canvas", "description": "Verarbeitetes Material für Segel/Schiffbau.", "effect_hint": "Material", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "cargo", "name": "Bulkhead", "description": "Fortgeschrittenes Bauteil für Schiffbau/Upgrades.", "effect_hint": "Advanced Material", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "cargo", "name": "Beam", "description": "Fortgeschrittenes Bauteil für Schiffbau/Upgrades.", "effect_hint": "Advanced Material", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "cargo", "name": "Rum", "description": "Versorgungs-/Craftinggut.", "effect_hint": "Supply", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
    {"category": "cargo", "name": "Trade Goods Mix", "description": "Handelswaren wie Cinnamon, Silk, Coffee, Wine oder Oil.", "effect_hint": "Trading", "progression_class": "Transport", "source_url": ITEMS_SOURCE_URL, "source_note": DOCUMENTED_ITEMS_NOTE},
]
