DEMO_BUILD_DATA = [
    {
        "build_name": "Victory Defensive Line",
        "ship_name": "Victory",
        "build_type": "defensive",
        "sails": "Tarpaulin Sails",
        "upgrade_1": "Sturdy Frames",
        "upgrade_2": "Strong Beams",
        "upgrade_3": "Repair Arsenal",
        "upgrade_4": "Fortified Gun Ports",
        "upgrade_5": "Cellars",
        "lantern": "Golden Lantern",
        "sailors": 82,
        "soldiers": 42,
        "musketeers": 56,
        "mercenaries": 18,
        "ammunition_slots": [
            {"item": "Round Shots", "quantity": 240},
            {"item": "Bar Shots", "quantity": 90},
        ],
        "consumable_slots": [
            {"item": "Iron Repair Kit", "quantity": 12},
            {"item": "Smoke Screen", "quantity": 4},
        ],
        "hold_slots": [
            {"item": "Wood", "quantity": 120},
            {"item": "Iron", "quantity": 80},
            {"item": "Fresh Meat", "quantity": 40},
        ],
        "details": "Demo build for line/sustain play. The data model is normalized; slots reference the option catalog.",
    },
    {
        "build_name": "Surprise Gunnery Scout",
        "ship_name": "Surprise",
        "build_type": "gunnery",
        "sails": "Elite Sails",
        "upgrade_1": "Ammunition Cradles",
        "upgrade_2": "Fortified Gun Ports",
        "upgrade_3": "Lightweight Hull",
        "lantern": "Red Lantern",
        "sailors": 45,
        "soldiers": 14,
        "musketeers": 26,
        "mercenaries": 6,
        "ammunition_slots": [
            {"item": "Bar Shots", "quantity": 120},
            {"item": "Grapeshot", "quantity": 60},
        ],
        "consumable_slots": [
            {"item": "Smoke Bomb", "quantity": 4},
            {"item": "Small Additional Sails", "quantity": 6},
        ],
        "hold_slots": [
            {"item": "Wood", "quantity": 45},
            {"item": "Fabric", "quantity": 30},
        ],
        "details": "Fast sample build for scouting and pressure on sails/positioning.",
    },
]
