"""Ship catalog seed data.

Ship names, rates/classes, and crew values are derived from the public WoSB
ship tables used during the MVP research. `sailor_minimum` is an app-level
planning rule derived from crew capacity for the prototype, not an official
game stat.
"""

SHIP_SOURCE_URL = "https://world-of-sea-battle.fandom.com/wiki/Ships"

SHIP_SEED_DATA = [{'crew_capacity': 170,
  'has_lantern': True,
  'name': 'Firestorm',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 68,
  'ship_type': 'Frigate',
  'upgrade_slots': 5},
 {'crew_capacity': 152,
  'has_lantern': True,
  'name': 'Ingermanland',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 61,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 132,
  'has_lantern': True,
  'name': 'Poltava',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 53,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 112,
  'has_lantern': True,
  'name': 'Surprise',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 45,
  'ship_type': 'Corvette',
  'upgrade_slots': 5},
 {'crew_capacity': 66,
  'has_lantern': True,
  'name': 'Axel Thorsen',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 26,
  'ship_type': 'Schooner',
  'upgrade_slots': 5},
 {'crew_capacity': 96,
  'has_lantern': True,
  'name': 'La Creole',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 38,
  'ship_type': 'Corvette',
  'upgrade_slots': 5},
 {'crew_capacity': 78,
  'has_lantern': True,
  'name': 'Le Cerf',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 31,
  'ship_type': 'Cutter',
  'upgrade_slots': 5},
 {'crew_capacity': 94,
  'has_lantern': True,
  'name': 'Savannah',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 38,
  'ship_type': 'Frigate',
  'upgrade_slots': 5},
 {'crew_capacity': 66,
  'has_lantern': True,
  'name': 'Pickle',
  'rate': 7,
  'sail_slots': 1,
  'sailor_minimum': 26,
  'ship_type': 'Schooner',
  'upgrade_slots': 5},
 {'crew_capacity': 188,
  'has_lantern': True,
  'name': 'De Zeven Provincien',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 75,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 192,
  'has_lantern': True,
  'name': 'Sovereign',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 77,
  'ship_type': 'Galleon',
  'upgrade_slots': 5},
 {'crew_capacity': 204,
  'has_lantern': True,
  'name': 'Victory',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 82,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 194,
  'has_lantern': True,
  'name': 'Neptuno',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 78,
  'ship_type': 'Galleon',
  'upgrade_slots': 5},
 {'crew_capacity': 184,
  'has_lantern': True,
  'name': 'Sans Pareil',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 74,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 160,
  'has_lantern': True,
  'name': 'Anson',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 64,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 170,
  'has_lantern': True,
  'name': 'Le Saint Louis',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 68,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 136,
  'has_lantern': True,
  'name': 'Essex',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 54,
  'ship_type': 'Frigate',
  'upgrade_slots': 5},
 {'crew_capacity': 140,
  'has_lantern': True,
  'name': 'Red Arrow',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 56,
  'ship_type': 'Galleon',
  'upgrade_slots': 5},
 {'crew_capacity': 113,
  'has_lantern': True,
  'name': 'Black Wind',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 45,
  'ship_type': 'Frigate',
  'upgrade_slots': 5},
 {'crew_capacity': 108,
  'has_lantern': True,
  'name': 'Kwee Song',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 43,
  'ship_type': 'Phanokson',
  'upgrade_slots': 5},
 {'crew_capacity': 96,
  'has_lantern': True,
  'name': 'La Salamandre',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 38,
  'ship_type': 'Ketch',
  'upgrade_slots': 5},
 {'crew_capacity': 92,
  'has_lantern': True,
  'name': 'Shunsen',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 37,
  'ship_type': 'Junk',
  'upgrade_slots': 5},
 {'crew_capacity': 78,
  'has_lantern': True,
  'name': 'Horizont',
  'rate': 7,
  'sail_slots': 1,
  'sailor_minimum': 31,
  'ship_type': 'Brigantine',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'La Couronne',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Galleon',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'La Sirene',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Mordaunt',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Prins Willem',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Galleon',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Falmouth',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Flying Cloud',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Clipper',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Friedrich Wilhelm',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Frigate',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Russia',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Frigate',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Mercury',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Galleon',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Friede',
  'rate': 7,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Flute',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': '12 Apostolov',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Santisima Trinidad',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Redoutable',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'St. Pavel',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Vasa',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Azov',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Bellona',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Constitution',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Frigate',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'San Martin',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Galleon',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Phoenix',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Brig',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'La Royale',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Galley',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Adventure',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Galley',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Kobukson',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Phanokson',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Shen',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Galiot',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Sparrow',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Tartane',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Eagle',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Flute',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Le Requin',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Xebec',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Golden Apostle',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Cutter',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Polacca',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Polacca',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Huracan',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship of the Line',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Octopus',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Deadfish',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Ship',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Devourer',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Barque',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Black Prince',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Galleon',
  'upgrade_slots': 5},
 {'crew_capacity': 100,
  'has_lantern': True,
  'name': 'Balloon',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Montgolfiere',
  'upgrade_slots': 5}]
