"""Rate 1 ship seeds."""

from app.seeds.ship_data.common import (
    SHIP_SCREENSHOT_SOURCE,
    ship,
)

RATE_1_SHIPS = [
    ship(
        name='12 Apostolov',
        rate=1,
        ship_type='Ship of the Line',
        durability=4400,
        speed_knots=6.2,
        maneuverability=49,
        armor=10.0,
        hold_capacity=36000,
        crew_capacity=220,
        displacement_tons=4500,
        max_weapon_class='heavy',
        weapon_layout='0-59-0',
        source=SHIP_SCREENSHOT_SOURCE,
    ),
    ship(
        name='De Zeven Provincien',
        rate=1,
        ship_type='Ship of the Line',
        durability=3320,
        speed_knots=7.7,
        maneuverability=75,
        armor=8.6,
        hold_capacity=26000,
        crew_capacity=188,
        displacement_tons=4440,
        max_weapon_class='heavy',
        weapon_layout='4-42-4',
        source=SHIP_SCREENSHOT_SOURCE,
    ),
    ship(
        name='Huracan',
        rate=1,
        ship_type='Ship of the Line',
        durability=8000,
        speed_knots=5.5,
        maneuverability=42,
        armor=11.5,
        hold_capacity=54000,
        crew_capacity=288,
        displacement_tons=5625,
        max_weapon_class='heavy',
        weapon_layout='0-85-2',
        source=SHIP_SCREENSHOT_SOURCE,
        upgrade_slots=6,
        special_weapon_capacity=2,
    ),
    ship(
        name='La Couronne',
        rate=1,
        ship_type='Galleon',
        durability=3500,
        speed_knots=7.6,
        maneuverability=72,
        armor=5.5,
        hold_capacity=50000,
        crew_capacity=188,
        displacement_tons=4500,
        max_weapon_class='heavy',
        weapon_layout='8-28-0',
        source=SHIP_SCREENSHOT_SOURCE,
        upgrade_slots=6,
    ),
    ship(
        name='La Royale',
        rate=1,
        ship_type='Galley',
        durability=2900,
        speed_knots=7.4,
        maneuverability=83,
        armor=6.5,
        hold_capacity=24000,
        crew_capacity=156,
        displacement_tons=3870,
        max_weapon_class='heavy',
        weapon_layout='0-18-6 + mortar 11in x3',
        source=SHIP_SCREENSHOT_SOURCE,
    ),
    ship(
        name='Santisima Trinidad',
        rate=1,
        ship_type='Ship of the Line',
        durability=4160,
        speed_knots=6.4,
        maneuverability=54,
        armor=9.0,
        hold_capacity=39500,
        crew_capacity=212,
        displacement_tons=4500,
        max_weapon_class='heavy',
        weapon_layout='4-63-0',
        source=SHIP_SCREENSHOT_SOURCE,
    ),
    ship(
        name='Sovereign',
        rate=1,
        ship_type='Galleon',
        durability=3600,
        speed_knots=7.4,
        maneuverability=70,
        armor=7.0,
        hold_capacity=26500,
        crew_capacity=192,
        displacement_tons=4275,
        max_weapon_class='heavy',
        weapon_layout='4-38-8 + mortar 7in x2',
        source=SHIP_SCREENSHOT_SOURCE,
    ),
    ship(
        name='Victory',
        rate=1,
        ship_type='Ship of the Line',
        durability=3740,
        speed_knots=7.1,
        maneuverability=66,
        armor=8.0,
        hold_capacity=25000,
        crew_capacity=204,
        displacement_tons=4050,
        max_weapon_class='heavy',
        weapon_layout='4-49-4',
        source=SHIP_SCREENSHOT_SOURCE,
    ),
]
