version: 2
updates:
  - package-ecosystem: maven
    directory: /spring-api
    schedule: { interval: weekly }
    groups:
      spring-dependencies: { patterns: ['*'] }
  - package-ecosystem: npm
    directory: /frontend
    schedule: { interval: weekly }
    groups:
      frontend-dependencies: { patterns: ['*'] }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /infrastructure/docker
    schedule: { interval: weekly }
