// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.ModeratorCreate;
import eu.royalblackwater.api.dto.ModeratorCreateResponse;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

public interface AdminModeratorsApi {
    @PostMapping("/api/admin/moderators")
    ResponseEntity<ModeratorCreateResponse> adminCreateModerator(
            @Valid @RequestBody ModeratorCreate body
    );
}
