// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.UserAdministrationUpdate;
import eu.royalblackwater.api.dto.UserRead;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

public interface AdminUsersApi {
    @GetMapping("/api/admin/users")
    ResponseEntity<List<UserRead>> adminListUsers(
            @RequestParam(name = "search", required = false) String search,
            @RequestParam(name = "role", required = false) String role,
            @RequestParam(name = "status", required = false) String status,
            @RequestParam(name = "fleet_id", required = false) Long fleetId,
            @RequestParam(name = "limit", defaultValue = "100") long limit,
            @RequestParam(name = "offset", defaultValue = "0") long offset
    );

    @PutMapping("/api/admin/users/{user_id}")
    ResponseEntity<UserRead> adminUpdateUser(
            @PathVariable("user_id") long userId,
            @Valid @RequestBody UserAdministrationUpdate body
    );
}
