// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.LegalNoticeAdminRead;
import eu.royalblackwater.api.dto.LegalNoticeUpdate;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;

public interface AdminLegalNoticeApi {
    @GetMapping("/api/admin/legal-notice")
    ResponseEntity<LegalNoticeAdminRead> adminGetLegalNotice();

    @PutMapping("/api/admin/legal-notice")
    ResponseEntity<LegalNoticeAdminRead> adminUpdateLegalNotice(
            @Valid @RequestBody LegalNoticeUpdate body
    );

    @PostMapping("/api/admin/legal-notice/reset-environment")
    ResponseEntity<LegalNoticeAdminRead> adminResetLegalNotice();
}
