// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.SecurityDashboard;
import java.time.LocalDate;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

public interface AdminLogsApi {
    @GetMapping("/api/admin/logs/security-dashboard")
    ResponseEntity<SecurityDashboard> adminSecurityDashboard(
            @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @RequestParam(name = "from_date", required = false) LocalDate fromDate,
            @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @RequestParam(name = "to_date", required = false) LocalDate toDate,
            @RequestParam(name = "threat_level", required = false) String threatLevel,
            @RequestParam(name = "client_ip", required = false) String clientIp,
            @RequestParam(name = "sort", defaultValue = "threat") String sort,
            @RequestParam(name = "limit", defaultValue = "100") long limit
    );
}
