// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.MasterDataCategoryCreate;
import eu.royalblackwater.api.dto.MasterDataCategoryRead;
import eu.royalblackwater.api.dto.MasterDataCategoryUpdate;
import eu.royalblackwater.api.dto.MasterDataOptionCreate;
import eu.royalblackwater.api.dto.MasterDataOptionRead;
import eu.royalblackwater.api.dto.MasterDataOptionUpdate;
import eu.royalblackwater.api.dto.MasterDataOverview;
import eu.royalblackwater.api.dto.MasterDataSeedRestoreSummary;
import eu.royalblackwater.api.dto.MasterDataShipCreate;
import eu.royalblackwater.api.dto.MasterDataShipRead;
import eu.royalblackwater.api.dto.MasterDataShipUpdate;
import eu.royalblackwater.api.dto.MasterDataTaxonomyRead;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

public interface AdminMasterDataApi {
    @GetMapping("/api/admin/master-data/categories")
    ResponseEntity<List<MasterDataCategoryRead>> categories();

    @PostMapping("/api/admin/master-data/categories")
    ResponseEntity<MasterDataCategoryRead> postCategory(
            @Valid @RequestBody MasterDataCategoryCreate body
    );

    @DeleteMapping("/api/admin/master-data/categories/{category_id}")
    ResponseEntity<Void> deleteCategory(
            @PathVariable("category_id") long categoryId
    );

    @PutMapping("/api/admin/master-data/categories/{category_id}")
    ResponseEntity<MasterDataCategoryRead> putCategory(
            @PathVariable("category_id") long categoryId,
            @Valid @RequestBody MasterDataCategoryUpdate body
    );

    @PostMapping("/api/admin/master-data/categories/{category_id}/restore-seed")
    ResponseEntity<MasterDataCategoryRead> restoreCategory(
            @PathVariable("category_id") long categoryId
    );

    @GetMapping("/api/admin/master-data/options")
    ResponseEntity<List<MasterDataOptionRead>> options(
            @RequestParam(name = "category", required = false) String category,
            @RequestParam(name = "search", required = false) String search
    );

    @PostMapping("/api/admin/master-data/options")
    ResponseEntity<MasterDataOptionRead> postOption(
            @Valid @RequestBody MasterDataOptionCreate body
    );

    @DeleteMapping("/api/admin/master-data/options/{option_id}")
    ResponseEntity<Void> deleteOption(
            @PathVariable("option_id") long optionId
    );

    @PutMapping("/api/admin/master-data/options/{option_id}")
    ResponseEntity<MasterDataOptionRead> putOption(
            @PathVariable("option_id") long optionId,
            @Valid @RequestBody MasterDataOptionUpdate body
    );

    @PostMapping("/api/admin/master-data/options/{option_id}/restore-seed")
    ResponseEntity<MasterDataOptionRead> restoreOption(
            @PathVariable("option_id") long optionId
    );

    @GetMapping("/api/admin/master-data/overview")
    ResponseEntity<MasterDataOverview> overview();

    @PostMapping("/api/admin/master-data/restore-seed-defaults")
    ResponseEntity<MasterDataSeedRestoreSummary> restoreSeedDefaults();

    @GetMapping("/api/admin/master-data/ships")
    ResponseEntity<List<MasterDataShipRead>> ships(
            @RequestParam(name = "search", required = false) String search
    );

    @PostMapping("/api/admin/master-data/ships")
    ResponseEntity<MasterDataShipRead> postShip(
            @Valid @RequestBody MasterDataShipCreate body
    );

    @DeleteMapping("/api/admin/master-data/ships/{ship_id}")
    ResponseEntity<Void> deleteShip(
            @PathVariable("ship_id") long shipId
    );

    @PutMapping("/api/admin/master-data/ships/{ship_id}")
    ResponseEntity<MasterDataShipRead> putShip(
            @PathVariable("ship_id") long shipId,
            @Valid @RequestBody MasterDataShipUpdate body
    );

    @PostMapping("/api/admin/master-data/ships/{ship_id}/restore-seed")
    ResponseEntity<MasterDataShipRead> restoreShip(
            @PathVariable("ship_id") long shipId
    );

    @GetMapping("/api/admin/master-data/taxonomy")
    ResponseEntity<MasterDataTaxonomyRead> taxonomy();
}
