// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.RegistrationDecision;
import eu.royalblackwater.api.dto.RegistrationRequestRead;
import jakarta.validation.Valid;
import java.time.LocalDate;
import java.util.List;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

public interface AdminRegistrationRequestsApi {
    @GetMapping("/api/admin/registration-requests")
    ResponseEntity<List<RegistrationRequestRead>> adminListRegistrationRequests(
            @RequestParam(name = "status", defaultValue = "pending") String status,
            @RequestParam(name = "search", required = false) String search,
            @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @RequestParam(name = "from_date", required = false) LocalDate fromDate,
            @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) @RequestParam(name = "to_date", required = false) LocalDate toDate
    );

    @PostMapping("/api/admin/registration-requests/{request_id}/approve")
    ResponseEntity<RegistrationRequestRead> adminApproveRegistrationRequest(
            @PathVariable("request_id") long requestId,
            @Valid @RequestBody RegistrationDecision body
    );

    @PostMapping("/api/admin/registration-requests/{request_id}/reject")
    ResponseEntity<RegistrationRequestRead> adminRejectRegistrationRequest(
            @PathVariable("request_id") long requestId,
            @Valid @RequestBody RegistrationDecision body
    );
}
