// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.OutboundWebhookBroadcastRequest;
import eu.royalblackwater.api.dto.OutboundWebhookCreate;
import eu.royalblackwater.api.dto.OutboundWebhookDeliveryDeleteResult;
import eu.royalblackwater.api.dto.OutboundWebhookDeliveryRead;
import eu.royalblackwater.api.dto.OutboundWebhookEventCatalogItem;
import eu.royalblackwater.api.dto.OutboundWebhookRead;
import eu.royalblackwater.api.dto.OutboundWebhookSummary;
import eu.royalblackwater.api.dto.OutboundWebhookTestRequest;
import eu.royalblackwater.api.dto.OutboundWebhookUpdate;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

public interface AdminDiscordWebhooksApi {
    @GetMapping("/api/admin/discord-webhooks")
    ResponseEntity<List<OutboundWebhookRead>> adminListWebhooks(
            @RequestParam(name = "purpose", required = false) String purpose
    );

    @PostMapping("/api/admin/discord-webhooks")
    ResponseEntity<OutboundWebhookRead> adminCreateWebhook(
            @Valid @RequestBody OutboundWebhookCreate body
    );

    @PostMapping("/api/admin/discord-webhooks/broadcast/send")
    ResponseEntity<List<OutboundWebhookDeliveryRead>> adminSendBroadcast(
            @Valid @RequestBody OutboundWebhookBroadcastRequest body
    );

    @GetMapping("/api/admin/discord-webhooks/broadcast/targets")
    ResponseEntity<List<OutboundWebhookRead>> adminListBroadcastWebhooks();

    @DeleteMapping("/api/admin/discord-webhooks/deliveries/history")
    ResponseEntity<OutboundWebhookDeliveryDeleteResult> adminDeleteWebhookDeliveryHistory(
            @RequestParam(name = "webhook_id", required = false) Long webhookId,
            @RequestParam(name = "status", required = false) String status,
            @RequestParam(name = "event_type", required = false) String eventType
    );

    @GetMapping("/api/admin/discord-webhooks/deliveries/history")
    ResponseEntity<List<OutboundWebhookDeliveryRead>> adminListWebhookDeliveries(
            @RequestParam(name = "webhook_id", required = false) Long webhookId,
            @RequestParam(name = "status", required = false) String status,
            @RequestParam(name = "event_type", required = false) String eventType,
            @RequestParam(name = "limit", defaultValue = "100") long limit
    );

    @DeleteMapping("/api/admin/discord-webhooks/deliveries/{delivery_id}")
    ResponseEntity<OutboundWebhookDeliveryDeleteResult> adminDeleteWebhookDelivery(
            @PathVariable("delivery_id") long deliveryId
    );

    @PostMapping("/api/admin/discord-webhooks/deliveries/{delivery_id}/retry")
    ResponseEntity<OutboundWebhookDeliveryRead> adminRetryWebhookDelivery(
            @PathVariable("delivery_id") long deliveryId
    );

    @GetMapping("/api/admin/discord-webhooks/events")
    ResponseEntity<List<OutboundWebhookEventCatalogItem>> adminWebhookEventCatalog();

    @GetMapping("/api/admin/discord-webhooks/summary")
    ResponseEntity<OutboundWebhookSummary> adminWebhookSummary(
            @RequestParam(name = "purpose", required = false) String purpose
    );

    @DeleteMapping("/api/admin/discord-webhooks/{webhook_id}")
    ResponseEntity<Void> adminDeleteWebhook(
            @PathVariable("webhook_id") long webhookId
    );

    @PutMapping("/api/admin/discord-webhooks/{webhook_id}")
    ResponseEntity<OutboundWebhookRead> adminUpdateWebhook(
            @PathVariable("webhook_id") long webhookId,
            @Valid @RequestBody OutboundWebhookUpdate body
    );

    @PostMapping("/api/admin/discord-webhooks/{webhook_id}/test")
    ResponseEntity<OutboundWebhookDeliveryRead> adminTestWebhook(
            @PathVariable("webhook_id") long webhookId,
            @Valid @RequestBody OutboundWebhookTestRequest body
    );
}
