// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.SystemUpdateRequest;
import eu.royalblackwater.api.dto.SystemUpdateRequestResult;
import eu.royalblackwater.api.dto.SystemUpdateStatus;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

public interface AdminSystemApi {
    @GetMapping("/api/admin/system/update")
    ResponseEntity<SystemUpdateStatus> adminSystemUpdateStatus();

    @PostMapping("/api/admin/system/update")
    ResponseEntity<SystemUpdateRequestResult> adminRequestSystemUpdate(
            @Valid @RequestBody SystemUpdateRequest body
    );
}
