// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.ForumThreadSummary;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;

public interface AdminForumApi {
    @GetMapping("/api/admin/forum/threads")
    ResponseEntity<List<ForumThreadSummary>> adminListForumThreads(
            @RequestParam(name = "search", required = false) String search,
            @RequestParam(name = "category", required = false) String category,
            @RequestParam(name = "limit", defaultValue = "50") long limit,
            @RequestParam(name = "offset", defaultValue = "0") long offset
    );

    @DeleteMapping("/api/admin/forum/threads/{thread_id}")
    ResponseEntity<Void> adminDeleteForumThread(
            @PathVariable("thread_id") long threadId
    );
}
