// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.RaidHelperDestinationRead;
import eu.royalblackwater.api.dto.RaidHelperDestinationTestRequest;
import eu.royalblackwater.api.dto.RaidHelperDestinationWrite;
import eu.royalblackwater.api.dto.RaidHelperProfileCreate;
import eu.royalblackwater.api.dto.RaidHelperProfileRead;
import eu.royalblackwater.api.dto.RaidHelperProfileTestResult;
import eu.royalblackwater.api.dto.RaidHelperProfileWrite;
import eu.royalblackwater.api.dto.RaidHelperTemplateRead;
import eu.royalblackwater.api.dto.RaidHelperTemplateWrite;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;

public interface AdminRaidHelperApi {
    @GetMapping("/api/admin/raid-helper/destinations")
    ResponseEntity<List<RaidHelperDestinationRead>> destinations();

    @PostMapping("/api/admin/raid-helper/destinations")
    ResponseEntity<RaidHelperDestinationRead> destinationCreate(
            @Valid @RequestBody RaidHelperDestinationWrite body
    );

    @DeleteMapping("/api/admin/raid-helper/destinations/{destination_id}")
    ResponseEntity<Void> destinationDelete(
            @PathVariable("destination_id") long destinationId
    );

    @PutMapping("/api/admin/raid-helper/destinations/{destination_id}")
    ResponseEntity<RaidHelperDestinationRead> destinationUpdate(
            @PathVariable("destination_id") long destinationId,
            @Valid @RequestBody RaidHelperDestinationWrite body
    );

    @PostMapping("/api/admin/raid-helper/destinations/{destination_id}/test")
    ResponseEntity<RaidHelperProfileTestResult> destinationTest(
            @PathVariable("destination_id") long destinationId,
            @Valid @RequestBody RaidHelperDestinationTestRequest body
    );

    @GetMapping("/api/admin/raid-helper/profiles")
    ResponseEntity<List<RaidHelperProfileRead>> profiles();

    @PostMapping("/api/admin/raid-helper/profiles")
    ResponseEntity<RaidHelperProfileRead> profileCreate(
            @Valid @RequestBody RaidHelperProfileCreate body
    );

    @DeleteMapping("/api/admin/raid-helper/profiles/{profile_id}")
    ResponseEntity<Void> profileDelete(
            @PathVariable("profile_id") long profileId
    );

    @PutMapping("/api/admin/raid-helper/profiles/{profile_id}")
    ResponseEntity<RaidHelperProfileRead> profileUpdate(
            @PathVariable("profile_id") long profileId,
            @Valid @RequestBody RaidHelperProfileWrite body
    );

    @PostMapping("/api/admin/raid-helper/profiles/{profile_id}/test")
    ResponseEntity<RaidHelperProfileTestResult> profileTest(
            @PathVariable("profile_id") long profileId
    );

    @GetMapping("/api/admin/raid-helper/templates")
    ResponseEntity<List<RaidHelperTemplateRead>> templates();

    @PostMapping("/api/admin/raid-helper/templates")
    ResponseEntity<RaidHelperTemplateRead> templateCreate(
            @Valid @RequestBody RaidHelperTemplateWrite body
    );

    @DeleteMapping("/api/admin/raid-helper/templates/{template_id}")
    ResponseEntity<Void> templateDelete(
            @PathVariable("template_id") long templateId
    );

    @PutMapping("/api/admin/raid-helper/templates/{template_id}")
    ResponseEntity<RaidHelperTemplateRead> templateUpdate(
            @PathVariable("template_id") long templateId,
            @Valid @RequestBody RaidHelperTemplateWrite body
    );
}
