// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.IpBlockCreate;
import eu.royalblackwater.api.dto.IpBlockRead;
import eu.royalblackwater.api.dto.IpBlockSummary;
import eu.royalblackwater.api.dto.IpBlockUnblock;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

public interface AdminIpBlocksApi {
    @GetMapping("/api/admin/ip-blocks")
    ResponseEntity<List<IpBlockRead>> adminListIpBlocks(
            @RequestParam(name = "status", defaultValue = "active") String status,
            @RequestParam(name = "search", required = false) String search,
            @RequestParam(name = "limit", defaultValue = "200") long limit
    );

    @PostMapping("/api/admin/ip-blocks")
    ResponseEntity<IpBlockRead> adminCreateIpBlock(
            @Valid @RequestBody IpBlockCreate body
    );

    @GetMapping("/api/admin/ip-blocks/summary")
    ResponseEntity<IpBlockSummary> adminIpBlockSummary();

    @PostMapping("/api/admin/ip-blocks/{block_id}/unblock")
    ResponseEntity<IpBlockRead> adminUnblockIp(
            @PathVariable("block_id") long blockId,
            @Valid @RequestBody IpBlockUnblock body
    );
}
