// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.BackupConfigurationRequest;
import eu.royalblackwater.api.dto.BackupControlRequestResult;
import eu.royalblackwater.api.dto.BackupControlStatus;
import eu.royalblackwater.api.dto.BackupDiscoveryRequest;
import eu.royalblackwater.api.dto.BackupEnrollmentResponseRequest;
import eu.royalblackwater.api.dto.DatabaseRestoreRequest;
import eu.royalblackwater.api.dto.FilesRestoreRequest;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;

public interface AdminBackupsApi {
    @DeleteMapping("/api/admin/backups/configuration")
    ResponseEntity<BackupControlRequestResult> adminDeleteBackupConfiguration();

    @PutMapping("/api/admin/backups/configuration")
    ResponseEntity<BackupControlRequestResult> adminConfigureBackupHost(
            @Valid @RequestBody BackupConfigurationRequest body
    );

    @PostMapping("/api/admin/backups/discover")
    ResponseEntity<BackupControlRequestResult> adminDiscoverBackupHost(
            @Valid @RequestBody BackupDiscoveryRequest body
    );

    @PostMapping("/api/admin/backups/enrollment/apply")
    ResponseEntity<BackupControlRequestResult> adminApplyBackupEnrollment(
            @Valid @RequestBody BackupEnrollmentResponseRequest body
    );

    @PostMapping("/api/admin/backups/enrollment/prepare")
    ResponseEntity<BackupControlRequestResult> adminPrepareBackupEnrollment();

    @PostMapping("/api/admin/backups/key/prepare")
    ResponseEntity<BackupControlRequestResult> adminPrepareBackupUploadKey();

    @PostMapping("/api/admin/backups/local/files/restore")
    ResponseEntity<BackupControlRequestResult> adminRestoreLocalFilesBackup(
            @Valid @RequestBody FilesRestoreRequest body
    );

    @PostMapping("/api/admin/backups/local/restore")
    ResponseEntity<BackupControlRequestResult> adminRestoreLocalDatabaseBackup(
            @Valid @RequestBody DatabaseRestoreRequest body
    );

    @PostMapping("/api/admin/backups/local/scan")
    ResponseEntity<BackupControlRequestResult> adminScanLocalDatabaseBackups();

    @PostMapping("/api/admin/backups/run")
    ResponseEntity<BackupControlRequestResult> adminRunApplicationBackup();

    @GetMapping("/api/admin/backups/status")
    ResponseEntity<BackupControlStatus> adminBackupStatus();

    @PostMapping("/api/admin/backups/test")
    ResponseEntity<BackupControlRequestResult> adminTestBackupConnection();
}
