// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.DataSubjectRequestRead;
import eu.royalblackwater.api.dto.DataSubjectRequestResolve;
import eu.royalblackwater.api.dto.PrivacyContactRead;
import eu.royalblackwater.api.dto.PrivacyContactResolve;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;

public interface AdminPrivacyRequestsApi {
    @GetMapping("/api/admin/privacy-requests")
    ResponseEntity<List<DataSubjectRequestRead>> listPrivacyRequests();

    @GetMapping("/api/admin/privacy-requests/contacts")
    ResponseEntity<List<PrivacyContactRead>> listPrivacyContacts();

    @PutMapping("/api/admin/privacy-requests/contacts/{request_id}")
    ResponseEntity<PrivacyContactRead> resolvePrivacyContact(
            @PathVariable("request_id") long requestId,
            @Valid @RequestBody PrivacyContactResolve body
    );

    @PutMapping("/api/admin/privacy-requests/{request_id}")
    ResponseEntity<DataSubjectRequestRead> resolvePrivacyRequest(
            @PathVariable("request_id") long requestId,
            @Valid @RequestBody DataSubjectRequestResolve body
    );
}
