// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.BuildRoleCreate;
import eu.royalblackwater.api.dto.BuildRoleRead;
import eu.royalblackwater.api.dto.BuildRoleUpdate;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;

public interface AdminBuildRolesApi {
    @GetMapping("/api/admin/build-roles")
    ResponseEntity<List<BuildRoleRead>> adminListBuildRoles();

    @PostMapping("/api/admin/build-roles")
    ResponseEntity<BuildRoleRead> adminCreateBuildRole(
            @Valid @RequestBody BuildRoleCreate body
    );

    @DeleteMapping("/api/admin/build-roles/{slug}")
    ResponseEntity<Void> adminDeleteBuildRole(
            @PathVariable("slug") String slug
    );

    @PutMapping("/api/admin/build-roles/{slug}")
    ResponseEntity<BuildRoleRead> adminUpdateBuildRole(
            @PathVariable("slug") String slug,
            @Valid @RequestBody BuildRoleUpdate body
    );
}
