// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.BuildRead;
import eu.royalblackwater.api.dto.BuildRoleAssignment;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

public interface AdminBuildsApi {
    @GetMapping("/api/admin/builds")
    ResponseEntity<List<BuildRead>> adminListBuilds(
            @RequestParam(name = "search", required = false) String search,
            @RequestParam(name = "build_type", required = false) String buildType
    );

    @DeleteMapping("/api/admin/builds/{build_id}")
    ResponseEntity<Void> adminDeleteBuild(
            @PathVariable("build_id") long buildId
    );

    @PutMapping("/api/admin/builds/{build_id}/role")
    ResponseEntity<BuildRead> adminAssignBuildRole(
            @PathVariable("build_id") long buildId,
            @Valid @RequestBody BuildRoleAssignment body
    );
}
