// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.LoginRequest;
import eu.royalblackwater.api.dto.LoginResponse;
import eu.royalblackwater.api.dto.PasswordChangeRequest;
import eu.royalblackwater.api.dto.PasswordChangeResponse;
import eu.royalblackwater.api.dto.RegisterRequest;
import eu.royalblackwater.api.dto.RegisterResponse;
import eu.royalblackwater.api.dto.UserRead;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

public interface AuthApi {
    @PostMapping("/api/auth/change-password")
    ResponseEntity<PasswordChangeResponse> changePassword(
            @Valid @RequestBody PasswordChangeRequest body
    );

    @PostMapping("/api/auth/login")
    ResponseEntity<LoginResponse> login(
            @Valid @RequestBody LoginRequest body
    );

    @PostMapping("/api/auth/logout")
    ResponseEntity<Void> logout();

    @GetMapping("/api/auth/me")
    ResponseEntity<UserRead> me();

    @PostMapping("/api/auth/register")
    ResponseEntity<RegisterResponse> register(
            @Valid @RequestBody RegisterRequest body
    );
}
