// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.BuildCreate;
import eu.royalblackwater.api.dto.BuildOptionsCatalog;
import eu.royalblackwater.api.dto.BuildPage;
import eu.royalblackwater.api.dto.BuildPrintoutRead;
import eu.royalblackwater.api.dto.BuildRead;
import eu.royalblackwater.api.dto.BuildRoleRead;
import eu.royalblackwater.api.dto.BuildUpdate;
import eu.royalblackwater.api.dto.BuildVoteState;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.core.io.Resource;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

public interface BuildsApi {
    @GetMapping("/api/builds")
    ResponseEntity<BuildPage> getBuilds(
            @RequestParam(name = "search", required = false) String search,
            @RequestParam(name = "build_type", required = false) String buildType,
            @RequestParam(name = "classification", required = false) String classification,
            @RequestParam(name = "limit", defaultValue = "50") long limit,
            @RequestParam(name = "offset", defaultValue = "0") long offset
    );

    @PostMapping("/api/builds")
    ResponseEntity<BuildRead> postBuild(
            @Valid @RequestBody BuildCreate body
    );

    @GetMapping("/api/builds/mine")
    ResponseEntity<BuildPage> getMyBuilds(
            @RequestParam(name = "search", required = false) String search,
            @RequestParam(name = "build_type", required = false) String buildType,
            @RequestParam(name = "classification", required = false) String classification,
            @RequestParam(name = "limit", defaultValue = "50") long limit,
            @RequestParam(name = "offset", defaultValue = "0") long offset
    );

    @DeleteMapping("/api/builds/mine/{build_id}")
    ResponseEntity<Void> deleteMyBuild(
            @PathVariable("build_id") long buildId
    );

    @PutMapping("/api/builds/mine/{build_id}")
    ResponseEntity<BuildRead> putMyBuild(
            @PathVariable("build_id") long buildId,
            @Valid @RequestBody BuildUpdate body
    );

    @GetMapping("/api/builds/options")
    ResponseEntity<BuildOptionsCatalog> getBuildOptions(
            @RequestParam(name = "ship_id", required = false) Long shipId
    );

    @GetMapping("/api/builds/roles")
    ResponseEntity<List<BuildRoleRead>> getBuildRoles();

    @GetMapping("/api/builds/{build_id}")
    ResponseEntity<BuildRead> getBuildDetail(
            @PathVariable("build_id") long buildId
    );

    @GetMapping("/api/builds/{build_id}/printout")
    ResponseEntity<Resource> getBuildPrintout(
            @PathVariable("build_id") long buildId
    );

    @PutMapping(value = "/api/builds/{build_id}/printout", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    ResponseEntity<BuildPrintoutRead> putBuildPrintout(
            @PathVariable("build_id") long buildId,
            @RequestParam(name = "notify_discord", defaultValue = "false") boolean notifyDiscord,
            @RequestPart("image") MultipartFile upload
    );

    @DeleteMapping("/api/builds/{build_id}/upvote")
    ResponseEntity<BuildVoteState> deleteBuildUpvote(
            @PathVariable("build_id") long buildId
    );

    @PostMapping("/api/builds/{build_id}/upvote")
    ResponseEntity<BuildVoteState> postBuildUpvote(
            @PathVariable("build_id") long buildId
    );
}
