// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.FleetEventCreate;
import eu.royalblackwater.api.dto.FleetEventRead;
import eu.royalblackwater.api.dto.FleetEventUpdate;
import jakarta.validation.Valid;
import java.time.LocalDateTime;
import java.util.List;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

public interface CalendarApi {
    @GetMapping("/api/calendar/events")
    ResponseEntity<List<FleetEventRead>> getEvents(
            @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @RequestParam(name = "start", required = false) LocalDateTime start,
            @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) @RequestParam(name = "end", required = false) LocalDateTime end,
            @RequestParam(name = "category", required = false) String category,
            @RequestParam(name = "squad_id", required = false) Long squadId,
            @RequestParam(name = "fleet_only", defaultValue = "false") boolean fleetOnly
    );

    @PostMapping("/api/calendar/events")
    ResponseEntity<FleetEventRead> postEvent(
            @Valid @RequestBody FleetEventCreate body
    );

    @DeleteMapping("/api/calendar/events/{event_id}")
    ResponseEntity<Void> deleteEvent(
            @PathVariable("event_id") long eventId
    );

    @GetMapping("/api/calendar/events/{event_id}")
    ResponseEntity<FleetEventRead> getEventDetail(
            @PathVariable("event_id") long eventId
    );

    @PutMapping("/api/calendar/events/{event_id}")
    ResponseEntity<FleetEventRead> putEvent(
            @PathVariable("event_id") long eventId,
            @Valid @RequestBody FleetEventUpdate body
    );

    @PostMapping("/api/calendar/events/{event_id}/raid-helper/retry")
    ResponseEntity<FleetEventRead> retryRaidHelperEvent(
            @PathVariable("event_id") long eventId
    );
}
