// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.RaidHelperOptionDestination;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

public interface CalendarRaidHelperApi {
    @GetMapping("/api/calendar/raid-helper/options")
    ResponseEntity<List<RaidHelperOptionDestination>> options(
            @RequestParam(name = "category", required = true) String category,
            @RequestParam(name = "squad_id", required = false) Long squadId
    );
}
