// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.FleetCreate;
import eu.royalblackwater.api.dto.FleetDetail;
import eu.royalblackwater.api.dto.FleetJoinRequest;
import eu.royalblackwater.api.dto.FleetMembershipRead;
import eu.royalblackwater.api.dto.FleetMembershipSelfRead;
import eu.royalblackwater.api.dto.FleetMembershipUpdate;
import eu.royalblackwater.api.dto.FleetPublicRead;
import eu.royalblackwater.api.dto.FleetRead;
import eu.royalblackwater.api.dto.FleetRoleCreate;
import eu.royalblackwater.api.dto.FleetRoleRead;
import eu.royalblackwater.api.dto.FleetRoleUpdate;
import eu.royalblackwater.api.dto.FleetUpdate;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

public interface FleetsApi {
    @GetMapping("/api/fleets")
    ResponseEntity<List<FleetRead>> getFleets();

    @PostMapping("/api/fleets")
    ResponseEntity<FleetRead> postFleet(
            @Valid @RequestBody FleetCreate body
    );

    @PostMapping("/api/fleets/join")
    ResponseEntity<FleetMembershipRead> postFleetJoin(
            @Valid @RequestBody FleetJoinRequest body
    );

    @GetMapping("/api/fleets/manageable")
    ResponseEntity<List<FleetRead>> getManageableFleets();

    @GetMapping("/api/fleets/memberships/me")
    ResponseEntity<List<FleetMembershipSelfRead>> getMyFleetMemberships();

    @GetMapping("/api/fleets/public/official")
    ResponseEntity<FleetPublicRead> getPublicOfficialFleet();

    @GetMapping("/api/fleets/{fleet_id}")
    ResponseEntity<FleetDetail> getFleetDetail(
            @PathVariable("fleet_id") long fleetId
    );

    @PutMapping("/api/fleets/{fleet_id}")
    ResponseEntity<FleetRead> putFleet(
            @PathVariable("fleet_id") long fleetId,
            @Valid @RequestBody FleetUpdate body
    );

    @PostMapping("/api/fleets/{fleet_id}/leaders/{user_id}")
    ResponseEntity<FleetMembershipRead> postFleetLeader(
            @PathVariable("fleet_id") long fleetId,
            @PathVariable("user_id") long userId,
            @Valid @RequestBody FleetMembershipUpdate body
    );

    @GetMapping("/api/fleets/{fleet_id}/manage")
    ResponseEntity<FleetDetail> getFleetManagementDetail(
            @PathVariable("fleet_id") long fleetId
    );

    @PutMapping("/api/fleets/{fleet_id}/memberships/{membership_id}")
    ResponseEntity<FleetMembershipRead> putMembership(
            @PathVariable("fleet_id") long fleetId,
            @PathVariable("membership_id") long membershipId,
            @Valid @RequestBody FleetMembershipUpdate body
    );

    @GetMapping("/api/fleets/{fleet_id}/roles")
    ResponseEntity<List<FleetRoleRead>> getFleetRoles(
            @PathVariable("fleet_id") long fleetId,
            @RequestParam(name = "include_inactive", defaultValue = "false") boolean includeInactive
    );

    @PostMapping("/api/fleets/{fleet_id}/roles")
    ResponseEntity<FleetRoleRead> postFleetRole(
            @PathVariable("fleet_id") long fleetId,
            @Valid @RequestBody FleetRoleCreate body
    );

    @DeleteMapping("/api/fleets/{fleet_id}/roles/{role_id}")
    ResponseEntity<Void> deleteRole(
            @PathVariable("fleet_id") long fleetId,
            @PathVariable("role_id") long roleId
    );

    @PutMapping("/api/fleets/{fleet_id}/roles/{role_id}")
    ResponseEntity<FleetRoleRead> putFleetRole(
            @PathVariable("fleet_id") long fleetId,
            @PathVariable("role_id") long roleId,
            @Valid @RequestBody FleetRoleUpdate body
    );
}
