// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.ForumPostCreate;
import eu.royalblackwater.api.dto.ForumPostRead;
import eu.royalblackwater.api.dto.ForumPostUpdate;
import eu.royalblackwater.api.dto.ForumThreadCreate;
import eu.royalblackwater.api.dto.ForumThreadRead;
import eu.royalblackwater.api.dto.ForumThreadSummary;
import eu.royalblackwater.api.dto.ForumThreadUpdate;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

public interface ForumApi {
    @DeleteMapping("/api/forum/posts/{post_id}")
    ResponseEntity<Void> deleteForumPost(
            @PathVariable("post_id") long postId
    );

    @PutMapping("/api/forum/posts/{post_id}")
    ResponseEntity<ForumPostRead> putPost(
            @PathVariable("post_id") long postId,
            @Valid @RequestBody ForumPostUpdate body
    );

    @GetMapping("/api/forum/threads")
    ResponseEntity<List<ForumThreadSummary>> getThreads(
            @RequestParam(name = "search", required = false) String search,
            @RequestParam(name = "category", required = false) String category,
            @RequestParam(name = "limit", defaultValue = "50") long limit,
            @RequestParam(name = "offset", defaultValue = "0") long offset
    );

    @PostMapping("/api/forum/threads")
    ResponseEntity<ForumThreadRead> postThread(
            @Valid @RequestBody ForumThreadCreate body
    );

    @GetMapping("/api/forum/threads/{thread_id}")
    ResponseEntity<ForumThreadRead> getThreadDetail(
            @PathVariable("thread_id") long threadId
    );

    @PutMapping("/api/forum/threads/{thread_id}")
    ResponseEntity<ForumThreadRead> putThread(
            @PathVariable("thread_id") long threadId,
            @Valid @RequestBody ForumThreadUpdate body
    );

    @PostMapping("/api/forum/threads/{thread_id}/posts")
    ResponseEntity<ForumPostRead> postReply(
            @PathVariable("thread_id") long threadId,
            @Valid @RequestBody ForumPostCreate body
    );
}
