// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.GroupCreate;
import eu.royalblackwater.api.dto.GroupJoinRequest;
import eu.royalblackwater.api.dto.GroupRead;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

public interface GroupsApi {
    @GetMapping("/api/groups")
    ResponseEntity<List<GroupRead>> getGroups(
            @RequestParam(name = "search", required = false) String search,
            @RequestParam(name = "focus", required = false) String focus,
            @RequestParam(name = "min_ship_rate", required = false) Long minShipRate,
            @RequestParam(name = "max_ship_rate", required = false) Long maxShipRate
    );

    @PostMapping("/api/groups")
    ResponseEntity<GroupRead> postGroup(
            @Valid @RequestBody GroupCreate body
    );

    @GetMapping("/api/groups/mine")
    ResponseEntity<List<GroupRead>> getMyGroups(
            @RequestParam(name = "search", required = false) String search
    );

    @GetMapping("/api/groups/{group_id}")
    ResponseEntity<GroupRead> getGroupDetail(
            @PathVariable("group_id") long groupId
    );

    @PostMapping("/api/groups/{group_id}/close")
    ResponseEntity<Void> postGroupClose(
            @PathVariable("group_id") long groupId
    );

    @PostMapping("/api/groups/{group_id}/join")
    ResponseEntity<GroupRead> postGroupJoin(
            @PathVariable("group_id") long groupId,
            @Valid @RequestBody GroupJoinRequest body
    );
}
