// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.GuideCreate;
import eu.royalblackwater.api.dto.GuideRead;
import eu.royalblackwater.api.dto.GuideSummary;
import eu.royalblackwater.api.dto.GuideUpdate;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

public interface GuidesApi {
    @GetMapping("/api/guides")
    ResponseEntity<List<GuideSummary>> getGuides(
            @RequestParam(name = "search", required = false) String search,
            @RequestParam(name = "category", required = false) String category,
            @RequestParam(name = "limit", defaultValue = "50") long limit,
            @RequestParam(name = "offset", defaultValue = "0") long offset
    );

    @PostMapping("/api/guides")
    ResponseEntity<GuideRead> postGuide(
            @Valid @RequestBody GuideCreate body
    );

    @DeleteMapping("/api/guides/{guide_id}")
    ResponseEntity<Void> deleteOwnGuide(
            @PathVariable("guide_id") long guideId
    );

    @GetMapping("/api/guides/{guide_id}")
    ResponseEntity<GuideRead> getGuideDetail(
            @PathVariable("guide_id") long guideId
    );

    @PutMapping("/api/guides/{guide_id}")
    ResponseEntity<GuideRead> putGuide(
            @PathVariable("guide_id") long guideId,
            @Valid @RequestBody GuideUpdate body
    );
}
