// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.HealthStatusRead;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;

public interface HealthApi {
    @GetMapping("/api/health")
    ResponseEntity<HealthStatusRead> healthCheck();

    @GetMapping("/api/health/ready")
    ResponseEntity<HealthStatusRead> readinessCheck();
}
