// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.LegalNoticePublicRead;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;

public interface LegalNoticeApi {
    @GetMapping("/api/legal-notice")
    ResponseEntity<LegalNoticePublicRead> publicLegalNotice();
}
