// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.NewcomerGuideRead;
import eu.royalblackwater.api.dto.NewcomerGuideUpdate;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;

public interface NewcomerGuideApi {
    @GetMapping("/api/newcomer-guide")
    ResponseEntity<NewcomerGuideRead> readNewcomerGuide();

    @PutMapping("/api/newcomer-guide")
    ResponseEntity<NewcomerGuideRead> replaceNewcomerGuide(
            @Valid @RequestBody NewcomerGuideUpdate body
    );
}
