// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.CookieConsentChoice;
import eu.royalblackwater.api.dto.CookieConsentPolicy;
import eu.royalblackwater.api.dto.CookieConsentRead;
import eu.royalblackwater.api.dto.DataSubjectRequestCreate;
import eu.royalblackwater.api.dto.DataSubjectRequestRead;
import eu.royalblackwater.api.dto.PersonalDataExportRead;
import eu.royalblackwater.api.dto.PrivacyContactCreate;
import eu.royalblackwater.api.dto.PrivacyContactReceipt;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

public interface PrivacyApi {
    @PostMapping("/api/privacy/contact")
    ResponseEntity<PrivacyContactReceipt> createPrivacyContact(
            @Valid @RequestBody PrivacyContactCreate body
    );

    @GetMapping("/api/privacy/cookie-consent")
    ResponseEntity<CookieConsentRead> getCookieConsent();

    @PostMapping("/api/privacy/cookie-consent")
    ResponseEntity<CookieConsentRead> saveCookieConsent(
            @Valid @RequestBody CookieConsentChoice body
    );

    @GetMapping("/api/privacy/cookie-policy")
    ResponseEntity<CookieConsentPolicy> getCookiePolicy();

    @GetMapping("/api/privacy/data-export")
    ResponseEntity<PersonalDataExportRead> exportPersonalData();

    @GetMapping("/api/privacy/requests")
    ResponseEntity<List<DataSubjectRequestRead>> listMyDataSubjectRequests();

    @PostMapping("/api/privacy/requests")
    ResponseEntity<DataSubjectRequestRead> createDataSubjectRequest(
            @Valid @RequestBody DataSubjectRequestCreate body
    );
}
