// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.ProfilePreferenceOptionsRead;
import eu.royalblackwater.api.dto.ProfileUpdate;
import eu.royalblackwater.api.dto.UserRead;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;

public interface ProfileApi {
    @GetMapping("/api/profile")
    ResponseEntity<UserRead> getProfile();

    @PutMapping("/api/profile")
    ResponseEntity<UserRead> putProfile(
            @Valid @RequestBody ProfileUpdate body
    );

    @GetMapping("/api/profile/preferences/options")
    ResponseEntity<ProfilePreferenceOptionsRead> getPreferenceOptions();
}
