// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.ShipRead;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;

public interface ShipsApi {
    @GetMapping("/api/ships")
    ResponseEntity<List<ShipRead>> listShips(
            @RequestParam(name = "search", required = false) String search,
            @RequestParam(name = "rate", required = false) Long rate,
            @RequestParam(name = "ship_type", required = false) String shipType,
            @RequestParam(name = "limit", defaultValue = "100") long limit,
            @RequestParam(name = "offset", defaultValue = "0") long offset
    );
}
