// Generated by infrastructure/scripts/generation/generate_spring_routes.py; do not edit manually.
package eu.royalblackwater.api.contract.api;

import eu.royalblackwater.api.dto.SquadCreate;
import eu.royalblackwater.api.dto.SquadDetailRead;
import eu.royalblackwater.api.dto.SquadMemberCreate;
import eu.royalblackwater.api.dto.SquadMemberUpdate;
import eu.royalblackwater.api.dto.SquadRosterMemberRead;
import eu.royalblackwater.api.dto.SquadSummaryRead;
import eu.royalblackwater.api.dto.SquadUpdate;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

public interface SquadsApi {
    @GetMapping("/api/squads")
    ResponseEntity<List<SquadSummaryRead>> getSquads(
            @RequestParam(name = "search", required = false) String search,
            @RequestParam(name = "fleet_id", required = false) Long fleetId,
            @RequestParam(name = "include_inactive", defaultValue = "false") boolean includeInactive,
            @RequestParam(name = "limit", defaultValue = "100") long limit,
            @RequestParam(name = "offset", defaultValue = "0") long offset
    );

    @PostMapping("/api/squads")
    ResponseEntity<SquadDetailRead> postSquad(
            @Valid @RequestBody SquadCreate body
    );

    @GetMapping("/api/squads/mine")
    ResponseEntity<List<SquadSummaryRead>> getMySquads();

    @GetMapping("/api/squads/roster")
    ResponseEntity<List<SquadRosterMemberRead>> getSquadRoster();

    @DeleteMapping("/api/squads/{squad_id}")
    ResponseEntity<Void> deleteSquad(
            @PathVariable("squad_id") long squadId
    );

    @GetMapping("/api/squads/{squad_id}")
    ResponseEntity<SquadDetailRead> getSquadDetail(
            @PathVariable("squad_id") long squadId
    );

    @PutMapping("/api/squads/{squad_id}")
    ResponseEntity<SquadDetailRead> putSquad(
            @PathVariable("squad_id") long squadId,
            @Valid @RequestBody SquadUpdate body
    );

    @PostMapping("/api/squads/{squad_id}/members")
    ResponseEntity<SquadDetailRead> postSquadMember(
            @PathVariable("squad_id") long squadId,
            @Valid @RequestBody SquadMemberCreate body
    );

    @DeleteMapping("/api/squads/{squad_id}/members/{member_id}")
    ResponseEntity<SquadDetailRead> deleteSquadMember(
            @PathVariable("squad_id") long squadId,
            @PathVariable("member_id") long memberId
    );

    @PutMapping("/api/squads/{squad_id}/members/{member_id}")
    ResponseEntity<SquadDetailRead> putSquadMember(
            @PathVariable("squad_id") long squadId,
            @PathVariable("member_id") long memberId,
            @Valid @RequestBody SquadMemberUpdate body
    );
}
