#!/usr/bin/env python3
"""Generate the Java build-stat catalog from its language-neutral contract."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
SOURCE=ROOT/'contracts/build-stat-catalog.json'
TARGET=ROOT/'spring-api/src/main/java/eu/royalblackwater/api/builds/BuildStatCatalog.java'
ORDER=('key','label','category','base_field','unit','pct_effect','flat_effect','calculation_flat_effect','precision','positive_is_good','source','pct_base_field')
def java(value):
    if value is None:return 'null'
    if isinstance(value,bool):return str(value).lower()
    if isinstance(value,str):return '"'+value.replace('\\','\\\\').replace('"','\\"')+'"'
    return str(value)
def render():
    payload=json.loads(SOURCE.read_text())
    if payload.get('schema_version')!=1 or not isinstance(payload.get('stats'),list):raise SystemExit('Invalid build stat contract')
    rows=[]; keys=set()
    for row in payload['stats']:
        key=row.get('key')
        if not key or key in keys:raise SystemExit(f'Duplicate/invalid stat key: {key}')
        keys.add(key); rows.append('            new BuildStatDefinition('+', '.join(java(row.get(name)) for name in ORDER)+')')
    return '''// Generated by infrastructure/scripts/generation/generate_build_stat_catalog.py; do not edit manually.
package eu.royalblackwater.api.builds;

import java.util.List;

public final class BuildStatCatalog {
    public static final List<BuildStatDefinition> ALL = List.of(
%s
    );

    private BuildStatCatalog() { }
}
''' % ',\n'.join(rows)
def main():
    content=render()
    import sys
    if '--check' in sys.argv:
        if not TARGET.is_file() or TARGET.read_text()!=content:raise SystemExit('BuildStatCatalog.java is stale')
    else: TARGET.write_text(content)
if __name__=='__main__':main()
