#!/usr/bin/env python3
"""Generate the Java build-stat catalog from one-definition-per-file reference data."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "spring-api/src/main/reference/build-stats"
TARGET = ROOT / "spring-api/src/main/java/eu/royalblackwater/api/builds/service/BuildStatCatalog.java"
ORDER = ("key", "label", "category", "base_field", "unit", "pct_effect", "flat_effect",
         "calculation_flat_effect", "precision", "positive_is_good", "source", "pct_base_field")


def java(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return str(value)


def definitions() -> list[dict]:
    rows: list[dict] = []
    keys: set[str] = set()
    fragments = sorted(SOURCE.glob("*.json"))
    if not fragments:
        raise SystemExit("No build-stat catalog fragments found")
    for fragment in fragments:
        row = json.loads(fragment.read_text(encoding="utf-8"))
        key = row.get("key") if isinstance(row, dict) else None
        if not key or key in keys:
            raise SystemExit(f"Duplicate/invalid stat key: {key}")
        if not fragment.stem.endswith("-" + key):
            raise SystemExit(f"Build-stat filename must end with its key: {fragment.relative_to(ROOT)}")
        keys.add(key)
        rows.append(row)
    return rows


def render():
    rows = [
        "            new BuildStatDefinition(" + ", ".join(java(row.get(name)) for name in ORDER) + ")"
        for row in definitions()
    ]
    return '''// Generated by infrastructure/scripts/generation/generate_build_stat_catalog.py; do not edit manually.
package eu.royalblackwater.api.builds.service;

import eu.royalblackwater.api.builds.dto.BuildStatDefinition;
import java.util.List;

public final class BuildStatCatalog {
    public static final List<BuildStatDefinition> ALL = List.of(
%s
    );

    private BuildStatCatalog() { }
}
''' % ',\n'.join(rows)


def main():
    content = render()
    import sys
    if "--check" in sys.argv:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != content:
            raise SystemExit("BuildStatCatalog.java is stale")
    else:
        TARGET.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
