#!/usr/bin/env python3
"""Generate the exhaustive human-readable API endpoint reference."""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
CONTRACT = ROOT / "openapi/openapi.json"
TARGET = ROOT / "docs/reference/API_ENDPOINTS.md"
METHODS = ("get", "post", "put", "patch", "delete")


def render() -> str:
    contract = json.loads(CONTRACT.read_text(encoding="utf-8"))
    groups: dict[str, list[tuple[str, str, str, str]]] = defaultdict(list)
    for path, path_item in contract.get("paths", {}).items():
        for method in METHODS:
            operation = path_item.get(method)
            if not isinstance(operation, dict):
                continue
            tag = (operation.get("tags") or ["other"])[0]
            groups[tag].append((method.upper(), path, operation.get("summary", ""), operation["operationId"]))

    lines = [
        "# API endpoint reference",
        "",
        "<!-- Generated by infrastructure/scripts/generation/generate_api_reference.py; do not edit manually. -->",
        "",
        f"Contract version: `{contract['info']['version']}`. Canonical source: `openapi/source/`; assembled artifact: `openapi/openapi.json`.",
        "",
        "Request/response schemas, validation constraints and parameter definitions remain in the canonical",
        "OpenAPI 3.1 contract. Access is enforced by Spring Security and documented in `API.md`.",
        "",
    ]
    for tag in sorted(groups):
        lines.extend((f"## {tag}", "", "| Method | Path | Summary | Operation ID |", "| --- | --- | --- | --- |"))
        for method, path, summary, operation_id in sorted(groups[tag], key=lambda item: (item[1], item[0])):
            lines.append(f"| `{method}` | `{path}` | {summary} | `{operation_id}` |")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding="utf-8") != expected:
            raise SystemExit("Generated API endpoint reference is stale")
    else:
        TARGET.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
