CREATE TABLE warehouse_resources (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 100,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT warehouse_resource_name_check CHECK (length(btrim(name)) BETWEEN 1 AND 120),
    CONSTRAINT warehouse_resource_sort_order_check CHECK (sort_order BETWEEN 0 AND 100000)
);

CREATE UNIQUE INDEX warehouse_resources_name_unique_idx ON warehouse_resources(lower(name));
CREATE INDEX warehouse_resources_active_order_idx
    ON warehouse_resources(is_active, sort_order, lower(name));

-- Preserve resources already entered before the managed catalog existed.
INSERT INTO warehouse_resources (name, sort_order, is_active, created_at, updated_at)
SELECT resource, (10000 + row_number() OVER (ORDER BY lower(resource)))::integer, TRUE,
       CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (SELECT DISTINCT ON (lower(resource)) resource
      FROM warehouse_entries ORDER BY lower(resource), resource) existing;

-- Cargo, raw/processed materials, trade goods and operational currencies.
INSERT INTO warehouse_resources (name, sort_order, is_active, created_at, updated_at) VALUES
    ('Animals', 10, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Battlemark', 20, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Beam', 30, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Beer', 40, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Blueprint Fragment', 50, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Bronze', 60, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Bulkhead', 70, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Canvas', 80, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Captives', 90, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Chest', 100, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Cinnamon', 110, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Coal', 120, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Coffee', 130, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Copper', 140, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Copper Ore', 150, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Dates', 160, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Escudo', 170, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Fabric', 180, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Fish', 190, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Fresh Meat', 200, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Gold', 210, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Grain', 220, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Grog', 230, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Imperial Blueprint', 240, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Iron', 250, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Iron Ore', 260, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Leather', 270, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Mango', 280, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Nuts', 290, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Oil', 300, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Paprika', 310, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Pepper', 320, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Pineapples', 330, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Pirate Token', 340, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Plate', 350, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Provision', 360, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Resin', 370, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Rugs', 380, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Rum', 390, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Saffron', 400, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Salt', 410, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Silk', 420, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Supplies', 430, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Sugar', 440, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Tackles', 450, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Tobacco', 460, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Vanilla', 470, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Voodoo Skull', 480, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Water', 490, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Whale Oil', 500, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Wine', 510, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Wood', 520, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Wreckage', 530, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;
