-- Generated once from immutable V1 by scripts/migration/generate_modular_flyway_baseline.py.
-- New databases start at B2 and apply this focused schema part. Existing V1 databases
-- execute it safely because CREATE TABLE/INDEX statements are idempotent.
-- Migration responsibility: 7__schema_indexes.

CREATE UNIQUE INDEX IF NOT EXISTS ix_build_features_code ON build_features (code);
CREATE INDEX IF NOT EXISTS ix_build_item_categories_id ON build_item_categories (id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_build_item_categories_key ON build_item_categories (key);
CREATE UNIQUE INDEX IF NOT EXISTS ix_build_item_categories_seed_key ON build_item_categories (seed_key);
CREATE INDEX IF NOT EXISTS ix_build_roles_sort_order ON build_roles (sort_order);
CREATE UNIQUE INDEX IF NOT EXISTS ix_fleet_roles_code ON fleet_roles (code);
CREATE INDEX IF NOT EXISTS ix_fleet_roles_is_active ON fleet_roles (is_active);
CREATE INDEX IF NOT EXISTS ix_fleet_roles_is_leadership ON fleet_roles (is_leadership);
CREATE INDEX IF NOT EXISTS ix_fleet_roles_is_system ON fleet_roles (is_system);
CREATE INDEX IF NOT EXISTS ix_fleet_roles_rank ON fleet_roles (rank);
CREATE INDEX IF NOT EXISTS ix_fleets_focus ON fleets (focus);
CREATE INDEX IF NOT EXISTS ix_fleets_id ON fleets (id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_fleets_name ON fleets (name);
CREATE UNIQUE INDEX IF NOT EXISTS ix_fleets_slug ON fleets (slug);
CREATE INDEX IF NOT EXISTS ix_raid_helper_profiles_is_active ON raid_helper_profiles (is_active);
CREATE INDEX IF NOT EXISTS ix_raid_helper_profiles_server_id ON raid_helper_profiles (server_id);
CREATE INDEX IF NOT EXISTS ix_security_signal_buckets_client_ip ON security_signal_buckets (client_ip);
CREATE INDEX IF NOT EXISTS ix_security_signal_buckets_day ON security_signal_buckets (day);
CREATE INDEX IF NOT EXISTS ix_security_signal_buckets_id ON security_signal_buckets (id);
CREATE INDEX IF NOT EXISTS ix_security_signal_buckets_signal ON security_signal_buckets (signal);
CREATE INDEX IF NOT EXISTS ix_ships_id ON ships (id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_ships_name ON ships (name);
CREATE INDEX IF NOT EXISTS ix_ships_rate ON ships (rate);
CREATE UNIQUE INDEX IF NOT EXISTS ix_ships_seed_key ON ships (seed_key);
CREATE UNIQUE INDEX IF NOT EXISTS ix_site_roles_code ON site_roles (code);
CREATE INDEX IF NOT EXISTS ix_site_roles_rank ON site_roles (rank);
CREATE UNIQUE INDEX IF NOT EXISTS ix_squad_roles_code ON squad_roles (code);
CREATE INDEX IF NOT EXISTS ix_squad_roles_rank ON squad_roles (rank);
CREATE UNIQUE INDEX IF NOT EXISTS ix_weapon_classes_code ON weapon_classes (code);
CREATE INDEX IF NOT EXISTS ix_weapon_classes_rank ON weapon_classes (rank);
CREATE UNIQUE INDEX IF NOT EXISTS ix_weapon_slot_types_code ON weapon_slot_types (code);
CREATE INDEX IF NOT EXISTS ix_build_feature_effects_effect_key ON build_feature_effects (effect_key);
CREATE INDEX IF NOT EXISTS ix_build_feature_effects_feature_id ON build_feature_effects (feature_id);
CREATE INDEX IF NOT EXISTS ix_build_item_options_category_id ON build_item_options (category_id);
CREATE INDEX IF NOT EXISTS ix_build_item_options_id ON build_item_options (id);
CREATE INDEX IF NOT EXISTS ix_build_item_options_name ON build_item_options (name);
CREATE INDEX IF NOT EXISTS ix_build_item_options_option_kind ON build_item_options (option_kind);
CREATE UNIQUE INDEX IF NOT EXISTS ix_build_item_options_seed_key ON build_item_options (seed_key);
CREATE INDEX IF NOT EXISTS ix_build_item_options_weapon_class_id ON build_item_options (weapon_class_id);
CREATE INDEX IF NOT EXISTS ix_raid_helper_templates_is_active ON raid_helper_templates (is_active);
CREATE INDEX IF NOT EXISTS ix_raid_helper_templates_profile_id ON raid_helper_templates (profile_id);
CREATE INDEX IF NOT EXISTS ix_ship_rate_weapon_class_rules_weapon_class_id ON ship_rate_weapon_class_rules (weapon_class_id);
CREATE INDEX IF NOT EXISTS ix_ship_weapon_mounts_max_weapon_class_id ON ship_weapon_mounts (max_weapon_class_id);
CREATE INDEX IF NOT EXISTS ix_ship_weapon_mounts_ship_id ON ship_weapon_mounts (ship_id);
CREATE INDEX IF NOT EXISTS ix_ship_weapon_mounts_slot_type_id ON ship_weapon_mounts (slot_type_id);
CREATE INDEX IF NOT EXISTS ix_users_id ON users (id);
CREATE INDEX IF NOT EXISTS ix_users_is_bootstrap_admin ON users (is_bootstrap_admin);
CREATE INDEX IF NOT EXISTS ix_users_site_role_id ON users (site_role_id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username ON users (username);
CREATE INDEX IF NOT EXISTS ix_audit_logs_action ON audit_logs (action);
CREATE INDEX IF NOT EXISTS ix_audit_logs_actor_role ON audit_logs (actor_role);
CREATE INDEX IF NOT EXISTS ix_audit_logs_actor_user_id ON audit_logs (actor_user_id);
CREATE INDEX IF NOT EXISTS ix_audit_logs_actor_username ON audit_logs (actor_username);
CREATE INDEX IF NOT EXISTS ix_audit_logs_created_at ON audit_logs (created_at);
CREATE INDEX IF NOT EXISTS ix_audit_logs_entity_id ON audit_logs (entity_id);
CREATE INDEX IF NOT EXISTS ix_audit_logs_entity_type ON audit_logs (entity_type);
CREATE INDEX IF NOT EXISTS ix_audit_logs_id ON audit_logs (id);
CREATE INDEX IF NOT EXISTS ix_auth_sessions_expires_at ON auth_sessions (expires_at);
CREATE INDEX IF NOT EXISTS ix_auth_sessions_id ON auth_sessions (id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_auth_sessions_token_hash ON auth_sessions (token_hash);
CREATE INDEX IF NOT EXISTS ix_auth_sessions_user_id ON auth_sessions (user_id);
CREATE INDEX IF NOT EXISTS ix_build_item_effects_effect_key ON build_item_effects (effect_key);
CREATE INDEX IF NOT EXISTS ix_build_item_effects_id ON build_item_effects (id);
CREATE INDEX IF NOT EXISTS ix_build_item_effects_option_id ON build_item_effects (option_id);
CREATE INDEX IF NOT EXISTS ix_build_item_option_slot_types_option_id ON build_item_option_slot_types (option_id);
CREATE INDEX IF NOT EXISTS ix_build_item_option_slot_types_slot_type_id ON build_item_option_slot_types (slot_type_id);
CREATE INDEX IF NOT EXISTS ix_builds_build_name ON builds (build_name);
CREATE INDEX IF NOT EXISTS ix_builds_build_type ON builds (build_type);
CREATE INDEX IF NOT EXISTS ix_builds_id ON builds (id);
CREATE INDEX IF NOT EXISTS ix_builds_is_official_template ON builds (is_official_template);
CREATE INDEX IF NOT EXISTS ix_builds_owner_id ON builds (owner_id);
CREATE INDEX IF NOT EXISTS ix_builds_research_upgrade_feature_id ON builds (research_upgrade_feature_id);
CREATE INDEX IF NOT EXISTS ix_builds_ship_id ON builds (ship_id);
CREATE INDEX IF NOT EXISTS ix_cookie_consent_decisions_consent_key ON cookie_consent_decisions (consent_key);
CREATE INDEX IF NOT EXISTS ix_cookie_consent_decisions_created_at ON cookie_consent_decisions (created_at);
CREATE INDEX IF NOT EXISTS ix_cookie_consent_decisions_user_id ON cookie_consent_decisions (user_id);
CREATE INDEX IF NOT EXISTS ix_cookie_consent_key_created ON cookie_consent_decisions (consent_key, created_at);
CREATE INDEX IF NOT EXISTS ix_data_subject_requests_created_at ON data_subject_requests (created_at);
CREATE INDEX IF NOT EXISTS ix_data_subject_requests_request_type ON data_subject_requests (request_type);
CREATE INDEX IF NOT EXISTS ix_data_subject_requests_status ON data_subject_requests (status);
CREATE INDEX IF NOT EXISTS ix_data_subject_requests_subject_user_id ON data_subject_requests (subject_user_id);
CREATE INDEX IF NOT EXISTS ix_fleet_memberships_fleet_id ON fleet_memberships (fleet_id);
CREATE INDEX IF NOT EXISTS ix_fleet_memberships_fleet_role_id ON fleet_memberships (fleet_role_id);
CREATE INDEX IF NOT EXISTS ix_fleet_memberships_id ON fleet_memberships (id);
CREATE INDEX IF NOT EXISTS ix_fleet_memberships_status ON fleet_memberships (status);
CREATE INDEX IF NOT EXISTS ix_fleet_memberships_user_id ON fleet_memberships (user_id);
CREATE INDEX IF NOT EXISTS ix_forum_threads_category ON forum_threads (category);
CREATE INDEX IF NOT EXISTS ix_forum_threads_id ON forum_threads (id);
CREATE INDEX IF NOT EXISTS ix_forum_threads_owner_id ON forum_threads (owner_id);
CREATE INDEX IF NOT EXISTS ix_forum_threads_title ON forum_threads (title);
CREATE INDEX IF NOT EXISTS ix_groups_expires_at ON groups (expires_at);
CREATE INDEX IF NOT EXISTS ix_groups_focus ON groups (focus);
CREATE INDEX IF NOT EXISTS ix_groups_id ON groups (id);
CREATE INDEX IF NOT EXISTS ix_groups_owner_id ON groups (owner_id);
CREATE INDEX IF NOT EXISTS ix_groups_scheduled_start_at ON groups (scheduled_start_at);
CREATE INDEX IF NOT EXISTS ix_groups_status ON groups (status);
CREATE INDEX IF NOT EXISTS ix_groups_title ON groups (title);
CREATE INDEX IF NOT EXISTS ix_guides_category ON guides (category);
CREATE INDEX IF NOT EXISTS ix_guides_id ON guides (id);
CREATE INDEX IF NOT EXISTS ix_guides_is_published ON guides (is_published);
CREATE INDEX IF NOT EXISTS ix_guides_owner_id ON guides (owner_id);
CREATE INDEX IF NOT EXISTS ix_guides_title ON guides (title);
CREATE INDEX IF NOT EXISTS ix_ip_blocks_created_at ON ip_blocks (created_at);
CREATE INDEX IF NOT EXISTS ix_ip_blocks_created_by_user_id ON ip_blocks (created_by_user_id);
CREATE INDEX IF NOT EXISTS ix_ip_blocks_created_by_username ON ip_blocks (created_by_username);
CREATE INDEX IF NOT EXISTS ix_ip_blocks_expires_at ON ip_blocks (expires_at);
CREATE INDEX IF NOT EXISTS ix_ip_blocks_id ON ip_blocks (id);
CREATE INDEX IF NOT EXISTS ix_ip_blocks_ip_address ON ip_blocks (ip_address);
CREATE INDEX IF NOT EXISTS ix_ip_blocks_unblocked_at ON ip_blocks (unblocked_at);
CREATE INDEX IF NOT EXISTS ix_ip_blocks_unblocked_by_user_id ON ip_blocks (unblocked_by_user_id);
CREATE INDEX IF NOT EXISTS ix_outbound_webhooks_broadcast_enabled ON outbound_webhooks (broadcast_enabled);
CREATE INDEX IF NOT EXISTS ix_outbound_webhooks_created_at ON outbound_webhooks (created_at);
CREATE INDEX IF NOT EXISTS ix_outbound_webhooks_created_by_user_id ON outbound_webhooks (created_by_user_id);
CREATE INDEX IF NOT EXISTS ix_outbound_webhooks_id ON outbound_webhooks (id);
CREATE INDEX IF NOT EXISTS ix_outbound_webhooks_is_active ON outbound_webhooks (is_active);
CREATE INDEX IF NOT EXISTS ix_outbound_webhooks_name ON outbound_webhooks (name);
CREATE INDEX IF NOT EXISTS ix_outbound_webhooks_scope_id ON outbound_webhooks (scope_id);
CREATE INDEX IF NOT EXISTS ix_outbound_webhooks_scope_type ON outbound_webhooks (scope_type);
CREATE INDEX IF NOT EXISTS ix_outbound_webhooks_updated_at ON outbound_webhooks (updated_at);
CREATE INDEX IF NOT EXISTS ix_privacy_contact_requests_created_at ON privacy_contact_requests (created_at);
CREATE INDEX IF NOT EXISTS ix_privacy_contact_requests_status ON privacy_contact_requests (status);
CREATE INDEX IF NOT EXISTS ix_privacy_contact_requests_user_id ON privacy_contact_requests (user_id);
CREATE INDEX IF NOT EXISTS ix_registration_requests_created_at ON registration_requests (created_at);
CREATE INDEX IF NOT EXISTS ix_registration_requests_created_user_id ON registration_requests (created_user_id);
CREATE INDEX IF NOT EXISTS ix_registration_requests_fleet_id ON registration_requests (fleet_id);
CREATE INDEX IF NOT EXISTS ix_registration_requests_id ON registration_requests (id);
CREATE INDEX IF NOT EXISTS ix_registration_requests_reviewed_by_id ON registration_requests (reviewed_by_id);
CREATE INDEX IF NOT EXISTS ix_registration_requests_status ON registration_requests (status);
CREATE INDEX IF NOT EXISTS ix_registration_requests_username ON registration_requests (username);
CREATE INDEX IF NOT EXISTS ix_ship_upgrade_effect_overrides_effect_key ON ship_upgrade_effect_overrides (effect_key);
CREATE INDEX IF NOT EXISTS ix_ship_upgrade_effect_overrides_id ON ship_upgrade_effect_overrides (id);
CREATE INDEX IF NOT EXISTS ix_ship_upgrade_effect_overrides_option_id ON ship_upgrade_effect_overrides (option_id);
CREATE INDEX IF NOT EXISTS ix_ship_upgrade_effect_overrides_ship_id ON ship_upgrade_effect_overrides (ship_id);
CREATE INDEX IF NOT EXISTS ix_squads_created_by_id ON squads (created_by_id);
CREATE INDEX IF NOT EXISTS ix_squads_fleet_id ON squads (fleet_id);
CREATE INDEX IF NOT EXISTS ix_squads_id ON squads (id);
CREATE INDEX IF NOT EXISTS ix_squads_is_active ON squads (is_active);
CREATE INDEX IF NOT EXISTS ix_squads_name ON squads (name);
CREATE INDEX IF NOT EXISTS ix_squads_slug ON squads (slug);
CREATE INDEX IF NOT EXISTS ix_stored_files_id ON stored_files (id);
CREATE INDEX IF NOT EXISTS ix_stored_files_is_public ON stored_files (is_public);
CREATE INDEX IF NOT EXISTS ix_stored_files_owner_id ON stored_files (owner_id);
CREATE UNIQUE INDEX IF NOT EXISTS ix_stored_files_stored_name ON stored_files (stored_name);
CREATE INDEX IF NOT EXISTS ix_stored_files_usage_context ON stored_files (usage_context);
CREATE INDEX IF NOT EXISTS ix_build_classifications_tag_build_id ON build_classifications (tag, build_id);
CREATE INDEX IF NOT EXISTS ix_build_file_attachments_build_id ON build_file_attachments (build_id);
CREATE INDEX IF NOT EXISTS ix_build_file_attachments_file_id ON build_file_attachments (file_id);
CREATE INDEX IF NOT EXISTS ix_build_file_attachments_id ON build_file_attachments (id);
CREATE INDEX IF NOT EXISTS ix_build_slots_build_id ON build_slots (build_id);
CREATE INDEX IF NOT EXISTS ix_build_slots_id ON build_slots (id);
CREATE INDEX IF NOT EXISTS ix_build_slots_option_id ON build_slots (option_id);
CREATE INDEX IF NOT EXISTS ix_build_slots_slot_type ON build_slots (slot_type);
CREATE INDEX IF NOT EXISTS ix_build_votes_build_id ON build_votes (build_id);
CREATE INDEX IF NOT EXISTS ix_build_votes_id ON build_votes (id);
CREATE INDEX IF NOT EXISTS ix_build_votes_user_id ON build_votes (user_id);
CREATE INDEX IF NOT EXISTS ix_fleet_events_active_start ON fleet_events (is_cancelled, start_at, id);
CREATE INDEX IF NOT EXISTS ix_fleet_events_category ON fleet_events (category);
CREATE INDEX IF NOT EXISTS ix_fleet_events_end_at ON fleet_events (end_at);
CREATE INDEX IF NOT EXISTS ix_fleet_events_id ON fleet_events (id);
CREATE INDEX IF NOT EXISTS ix_fleet_events_is_cancelled ON fleet_events (is_cancelled);
CREATE INDEX IF NOT EXISTS ix_fleet_events_owner_id ON fleet_events (owner_id);
CREATE INDEX IF NOT EXISTS ix_fleet_events_raid_helper_enabled ON fleet_events (raid_helper_enabled);
CREATE INDEX IF NOT EXISTS ix_fleet_events_squad_active_start ON fleet_events (squad_id, is_cancelled, start_at, id);
CREATE INDEX IF NOT EXISTS ix_fleet_events_squad_id ON fleet_events (squad_id);
CREATE INDEX IF NOT EXISTS ix_fleet_events_start_at ON fleet_events (start_at);
CREATE INDEX IF NOT EXISTS ix_fleet_events_title ON fleet_events (title);
CREATE INDEX IF NOT EXISTS ix_forum_posts_author_id ON forum_posts (author_id);
CREATE INDEX IF NOT EXISTS ix_forum_posts_id ON forum_posts (id);
CREATE INDEX IF NOT EXISTS ix_forum_posts_thread_id ON forum_posts (thread_id);
CREATE INDEX IF NOT EXISTS ix_group_members_build_id ON group_members (build_id);
CREATE INDEX IF NOT EXISTS ix_group_members_group_id ON group_members (group_id);
CREATE INDEX IF NOT EXISTS ix_group_members_id ON group_members (id);
CREATE INDEX IF NOT EXISTS ix_group_members_is_active ON group_members (is_active);
CREATE INDEX IF NOT EXISTS ix_group_members_ship_id ON group_members (ship_id);
CREATE INDEX IF NOT EXISTS ix_group_members_user_id ON group_members (user_id);
CREATE INDEX IF NOT EXISTS ix_guide_attachments_file_id ON guide_attachments (file_id);
CREATE INDEX IF NOT EXISTS ix_guide_attachments_guide_id ON guide_attachments (guide_id);
CREATE INDEX IF NOT EXISTS ix_guide_attachments_id ON guide_attachments (id);
CREATE INDEX IF NOT EXISTS ix_guide_build_references_build_id ON guide_build_references (build_id);
CREATE INDEX IF NOT EXISTS ix_guide_build_references_guide_id ON guide_build_references (guide_id);
CREATE INDEX IF NOT EXISTS ix_guide_build_references_id ON guide_build_references (id);
CREATE INDEX IF NOT EXISTS ix_newcomer_guide_blocks_id ON newcomer_guide_blocks (id);
CREATE INDEX IF NOT EXISTS ix_newcomer_guide_blocks_page_id ON newcomer_guide_blocks (page_id);
CREATE INDEX IF NOT EXISTS ix_outbound_webhook_deliveries_created_at ON outbound_webhook_deliveries (created_at);
CREATE INDEX IF NOT EXISTS ix_outbound_webhook_deliveries_delivered_at ON outbound_webhook_deliveries (delivered_at);
CREATE UNIQUE INDEX IF NOT EXISTS ix_outbound_webhook_deliveries_delivery_id ON outbound_webhook_deliveries (delivery_id);
CREATE INDEX IF NOT EXISTS ix_outbound_webhook_deliveries_event_type ON outbound_webhook_deliveries (event_type);
CREATE INDEX IF NOT EXISTS ix_outbound_webhook_deliveries_id ON outbound_webhook_deliveries (id);
CREATE INDEX IF NOT EXISTS ix_outbound_webhook_deliveries_last_attempt_at ON outbound_webhook_deliveries (last_attempt_at);
CREATE INDEX IF NOT EXISTS ix_outbound_webhook_deliveries_resource_id ON outbound_webhook_deliveries (resource_id);
CREATE INDEX IF NOT EXISTS ix_outbound_webhook_deliveries_resource_type ON outbound_webhook_deliveries (resource_type);
CREATE INDEX IF NOT EXISTS ix_outbound_webhook_deliveries_status ON outbound_webhook_deliveries (status);
CREATE INDEX IF NOT EXISTS ix_outbound_webhook_deliveries_webhook_id ON outbound_webhook_deliveries (webhook_id);
CREATE INDEX IF NOT EXISTS ix_webhook_deliveries_created_id ON outbound_webhook_deliveries (created_at, id);
CREATE INDEX IF NOT EXISTS ix_webhook_deliveries_status_created_id ON outbound_webhook_deliveries (status, created_at, id);
CREATE INDEX IF NOT EXISTS ix_webhook_deliveries_webhook_created_id ON outbound_webhook_deliveries (webhook_id, created_at, id);
CREATE INDEX IF NOT EXISTS ix_raid_helper_destinations_is_active ON raid_helper_destinations (is_active);
CREATE INDEX IF NOT EXISTS ix_raid_helper_destinations_profile_id ON raid_helper_destinations (profile_id);
CREATE INDEX IF NOT EXISTS ix_raid_helper_destinations_scope ON raid_helper_destinations (scope_type, squad_id, is_active);
CREATE INDEX IF NOT EXISTS ix_raid_helper_destinations_squad_id ON raid_helper_destinations (squad_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_raid_helper_destinations_fleet_channel ON raid_helper_destinations (profile_id, channel_id) WHERE scope_type = 'fleet';
CREATE UNIQUE INDEX IF NOT EXISTS uq_raid_helper_destinations_squad_channel ON raid_helper_destinations (profile_id, channel_id, squad_id) WHERE scope_type = 'squad';
CREATE INDEX IF NOT EXISTS ix_squad_members_fleet_membership_id ON squad_members (fleet_membership_id);
CREATE INDEX IF NOT EXISTS ix_squad_members_id ON squad_members (id);
CREATE INDEX IF NOT EXISTS ix_squad_members_squad_id ON squad_members (squad_id);
CREATE INDEX IF NOT EXISTS ix_squad_members_squad_role_id ON squad_members (squad_role_id);
CREATE INDEX IF NOT EXISTS ix_user_profile_role_preferences_fleet_role_id ON user_profile_role_preferences (fleet_role_id);
CREATE INDEX IF NOT EXISTS ix_user_profile_role_preferences_user_id ON user_profile_role_preferences (user_id);
CREATE INDEX IF NOT EXISTS ix_user_profile_ship_preferences_ship_id ON user_profile_ship_preferences (ship_id);
CREATE INDEX IF NOT EXISTS ix_user_profile_ship_preferences_user_id ON user_profile_ship_preferences (user_id);
CREATE INDEX IF NOT EXISTS ix_forum_post_attachments_file_id ON forum_post_attachments (file_id);
CREATE INDEX IF NOT EXISTS ix_forum_post_attachments_id ON forum_post_attachments (id);
CREATE INDEX IF NOT EXISTS ix_forum_post_attachments_post_id ON forum_post_attachments (post_id);
CREATE INDEX IF NOT EXISTS ix_newcomer_guide_resources_block_id ON newcomer_guide_resources (block_id);
CREATE INDEX IF NOT EXISTS ix_newcomer_guide_resources_id ON newcomer_guide_resources (id);
CREATE INDEX IF NOT EXISTS ix_raid_helper_event_links_destination_id ON raid_helper_event_links (destination_id);
CREATE INDEX IF NOT EXISTS ix_raid_helper_event_links_event_id ON raid_helper_event_links (event_id);
CREATE INDEX IF NOT EXISTS ix_raid_helper_event_links_external_event_id ON raid_helper_event_links (external_event_id);
CREATE INDEX IF NOT EXISTS ix_raid_helper_event_links_status_updated ON raid_helper_event_links (status, updated_at);
CREATE INDEX IF NOT EXISTS ix_raid_helper_event_links_template_id ON raid_helper_event_links (template_id);
