import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

import { createServer } from 'vite'

const root = fileURLToPath(new URL('..', import.meta.url))
const outputDirectory = fileURLToPath(new URL('../src/locales/generated/', import.meta.url))
const server = await createServer({
  root,
  logLevel: 'silent',
  server: { middlewareMode: true },
  appType: 'custom',
})

function moduleSource(locale, messages, optionTerms) {
  return [
    '// Generated by scripts/generate-locales.mjs. Do not edit directly.',
    `export const locale = ${JSON.stringify(locale)}`,
    `export const messages = ${JSON.stringify(messages)}`,
    `export const optionTerms = ${JSON.stringify(optionTerms || {})}`,
    'export default { locale, messages, optionTerms }',
    '',
  ].join('\n')
}

try {
  const [{ messages }, { optionTermGlossaries }] = await Promise.all([
    server.ssrLoadModule('/src/locales/messages/index.js'),
    server.ssrLoadModule('/src/locales/glossaries/optionTerms.js'),
  ])
  await mkdir(outputDirectory, { recursive: true })
  await Promise.all(Object.entries(messages).map(([locale, localeMessages]) => (
    writeFile(
      new URL(`../src/locales/generated/${locale}.js`, import.meta.url),
      moduleSource(locale, localeMessages, optionTermGlossaries[locale]),
      'utf8',
    )
  )))
  console.log(`Generated ${Object.keys(messages).length} locale runtime modules.`)
} finally {
  await server.close()
}
