import { mkdir, writeFile } from 'node:fs/promises'

import { optionTermGlossaries } from '../src/locales/glossaries/optionTerms.js'
import { messages } from '../src/locales/messages/index.js'

const outputDirectory = new URL('../src/locales/generated/', import.meta.url)

function moduleSource(locale, localeMessages, optionTerms) {
  return [
    '// Generated by scripts/generate-locales.mjs. Do not edit directly.',
    `export const locale = ${JSON.stringify(locale)}`,
    `export const messages = ${JSON.stringify(localeMessages)}`,
    `export const optionTerms = ${JSON.stringify(optionTerms || {})}`,
    'export default { locale, messages, optionTerms }',
    '',
  ].join('\n')
}

await mkdir(outputDirectory, { recursive: true })
await Promise.all(Object.entries(messages).map(([locale, localeMessages]) => (
  writeFile(
    new URL(`../src/locales/generated/${locale}.js`, import.meta.url),
    moduleSource(locale, localeMessages, optionTermGlossaries[locale]),
    'utf8',
  )
)))
console.log(`Generated ${Object.keys(messages).length} locale runtime modules.`)
