// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.List;

public record AuditLogRead(
        @NotNull String action,
        @NotNull String actorRole,
        Long actorUserId,
        @NotNull String actorUsername,
        List<String> changedFields,
        @NotNull LocalDateTime createdAt,
        @NotNull String entityId,
        @NotNull String entityType,
        long id,
        @NotNull String summary) { }
