// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public record BackupEnrollmentResponseRequest(
        @NotNull @Size(min = 2, max = 32768) String responseJson) { }
