// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;

public record Body_post_file_api_files_post(
        @NotNull byte[] file) { }
