// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public record BuildRoleAssignment(
        @NotNull @Size(min = 1, max = 32) String buildType) { }
