// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public record BuildPrintoutRead(
        boolean changed,
        @NotNull String checksum,
        long sizeBytes,
        @NotNull LocalDateTime updatedAt,
        @NotNull String url) { }
