// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Min;

public record BuildVoteState(
        long buildId,
        boolean hasUpvoted,
        @Min(0) long upvoteCount) { }
