// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public record BuildRoleUpdate(
        String description,
        @NotNull @Size(min = 1, max = 80) String label,
        @Min(-10000) @Max(10000) Long sortOrder) { }
