// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;
import java.util.List;

public record BuildRead(
        @Size(max = 16) List<InventorySlot> ammunitionSlots,
        @NotNull @Size(min = 1, max = 140) String buildName,
        @NotNull String buildRoleLabel,
        @Size(max = 32) String buildType,
        @Size(max = 6) List<String> classificationTags,
        @Size(max = 3) List<InventorySlot> consumableSlots,
        @NotNull LocalDateTime createdAt,
        String details,
        @Size(max = 12) List<InventorySlot> frontWeaponSlots,
        Boolean hasUpvoted,
        @Size(max = 32) List<InventorySlot> holdSlots,
        long id,
        Boolean isOfficialTemplate,
        String lantern,
        @Min(0) Long mercenaries,
        Boolean mortarModificationInstalled,
        @Size(max = 8) List<InventorySlot> mortarWeaponSlots,
        @Min(0) Long musketeers,
        Long ownerId,
        @Size(max = 12) List<InventorySlot> portWeaponSlots,
        String printoutChecksum,
        String printoutUrl,
        @Size(max = 12) List<InventorySlot> rearWeaponSlots,
        Boolean researchUpgradeSlotUnlocked,
        @Min(0) Long sailors,
        String sails,
        @NotNull ShipRead ship,
        long shipId,
        @NotNull ShipStats shipStats,
        @Min(0) Long soldiers,
        @Size(max = 5) List<InventorySlot> specialCrewSlots,
        @Size(max = 8) List<InventorySlot> specialWeaponSlots,
        @Size(max = 12) List<InventorySlot> starboardWeaponSlots,
        @NotNull LocalDateTime updatedAt,
        @JsonProperty("upgrade_1") String upgrade1,
        @JsonProperty("upgrade_2") String upgrade2,
        @JsonProperty("upgrade_3") String upgrade3,
        @JsonProperty("upgrade_4") String upgrade4,
        @JsonProperty("upgrade_5") String upgrade5,
        @JsonProperty("upgrade_6") String upgrade6,
        @JsonProperty("upgrade_7") String upgrade7,
        @JsonProperty("upgrade_8") String upgrade8,
        Long upvoteCount) { }
