// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import java.util.List;

public record BuildPage(
        List<BuildSummaryRead> items,
        Long limit,
        Long offset,
        Long total) { }
