// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;

public record CalendarSquadRead(
        long id,
        @NotNull String name,
        @NotNull String slug) { }
