// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public record CookieConsentRead(
        Boolean analytics,
        LocalDateTime decidedAt,
        Boolean externalMedia,
        Boolean hasDecision,
        Boolean necessary,
        @NotNull String policyVersion,
        Boolean preferences) { }
