// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

public record CookieConsentChoice(
        Boolean analytics,
        Boolean externalMedia,
        Boolean necessary,
        Boolean preferences) { }
