// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;

public record DataSubjectRequestCreate(
        String confirmation,
        String details,
        @NotNull String requestType) { }
