// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public record DataSubjectRequestRead(
        @NotNull LocalDateTime createdAt,
        String details,
        Long handledByUserId,
        long id,
        @NotNull String requestType,
        String resolutionNote,
        LocalDateTime resolvedAt,
        @NotNull String status,
        long subjectUserId,
        @NotNull String subjectUsername) { }
