// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.util.List;

public record FilesRestoreRequest(
        @NotNull String approvalToken,
        @NotNull @Size(min = 64, max = 64) String backupId,
        @NotNull @Size(min = 1, max = 4) List<String> components,
        @NotNull String confirmation) { }
