// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.List;

public record FleetDetail(
        Long activeMembersCount,
        @NotNull LocalDateTime createdAt,
        String description,
        @NotNull String focus,
        long id,
        boolean isActive,
        List<FleetMembershipRead> leaders,
        List<FleetMembershipRead> memberships,
        @NotNull String name,
        Long pendingMembersCount,
        @NotNull String slug,
        long sortOrder,
        String standingOrders,
        @NotNull LocalDateTime updatedAt) { }
