// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

public record FleetRoleUpdate(
        Boolean canManageFleet,
        Boolean canManageMembers,
        Boolean isActive,
        Boolean isLeadership,
        String label,
        Long rank) { }
