// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public record FleetRoleCreate(
        Boolean canManageFleet,
        Boolean canManageMembers,
        @NotNull @Size(min = 2, max = 40) String code,
        Boolean isLeadership,
        @NotNull @Size(min = 2, max = 80) String label,
        @Min(1) @Max(79) long rank) { }
