// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.util.List;

public record FleetPublicRead(
        Long activeMembersCount,
        String description,
        @NotNull String focus,
        long id,
        List<FleetPublicLeaderRead> leaders,
        @NotNull String name,
        @NotNull String slug,
        String standingOrders) { }
