// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.List;

public record FleetEventRead(
        boolean allDay,
        Boolean canManage,
        @NotNull String category,
        @NotNull LocalDateTime createdAt,
        String description,
        @NotNull LocalDateTime endAt,
        long id,
        boolean isCancelled,
        String location,
        @NotNull UserReferenceRead owner,
        long ownerId,
        Boolean raidHelperEnabled,
        List<RaidHelperEventLinkRead> raidHelperLinks,
        String scopeName,
        String scopeType,
        CalendarSquadRead squad,
        Long squadId,
        @NotNull LocalDateTime startAt,
        @NotNull String title,
        @NotNull LocalDateTime updatedAt) { }
