// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

public record FleetMembershipUpdate(
        String adminNote,
        String assignment,
        String note,
        String role,
        String status) { }
