// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.util.List;

public record ForumPostUpdate(
        @NotNull @Size(min = 1, max = 8000) String body,
        @Size(max = 12) List<Long> fileIds) { }
