// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.List;

public record ForumPostRead(
        List<FileRead> attachments,
        @NotNull UserReferenceRead author,
        long authorId,
        @NotNull String body,
        @NotNull LocalDateTime createdAt,
        long id,
        long threadId,
        @NotNull LocalDateTime updatedAt) { }
