// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;
import java.util.List;

public record GroupRead(
        long activeMembersCount,
        String activityPlan,
        Boolean allowGuests,
        LocalDateTime closedAt,
        String contactNote,
        @NotNull LocalDateTime createdAt,
        String description,
        String expectations,
        @NotNull LocalDateTime expiresAt,
        String fleetRestriction,
        @Size(max = 80) String focus,
        long id,
        boolean isJoinable,
        @Min(2) @Max(50) Long maxMembers,
        Long maxShipRate,
        List<GroupMemberRead> members,
        Long minShipRate,
        @NotNull UserReferenceRead owner,
        long ownerId,
        LocalDateTime scheduledEndAt,
        LocalDateTime scheduledStartAt,
        long spotsLeft,
        @NotNull String status,
        @NotNull @Size(min = 1, max = 140) String title,
        @NotNull LocalDateTime updatedAt) { }
