// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;

public record GroupMemberRead(
        BuildRead build,
        Long buildId,
        @NotNull @Size(min = 1, max = 120) String displayName,
        String fleetName,
        long id,
        boolean isActive,
        boolean isGuest,
        @NotNull LocalDateTime joinedAt,
        LocalDateTime leftAt,
        String note,
        ShipRead ship,
        Long shipId,
        String shipName,
        Long shipRate,
        Long userId) { }
