// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.List;

public record GuideRead(
        Long attachmentCount,
        List<FileRead> attachments,
        @NotNull String body,
        Long buildReferenceCount,
        List<BuildRead> builds,
        @NotNull String category,
        @NotNull LocalDateTime createdAt,
        long id,
        @NotNull UserReferenceRead owner,
        long ownerId,
        String summary,
        @NotNull String title,
        @NotNull LocalDateTime updatedAt) { }
