// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public record GuideSummary(
        Long attachmentCount,
        Long buildReferenceCount,
        @NotNull String category,
        @NotNull LocalDateTime createdAt,
        long id,
        @NotNull UserReferenceRead owner,
        long ownerId,
        String summary,
        @NotNull String title,
        @NotNull LocalDateTime updatedAt) { }
