// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import java.util.List;

public record HTTPValidationError(
        List<ValidationError> detail) { }
