// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public record InventorySlot(
        @NotNull @Size(min = 1, max = 160) String item,
        @Min(1) @Max(999999) Long quantity) { }
