// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

public record IpBlockSummary(
        Long active,
        Long expired,
        Long permanent,
        Long temporary,
        Long total,
        Long unblocked) { }
