// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;

public record IpBlockCreate(
        LocalDateTime expiresAt,
        @NotNull @Size(min = 2, max = 64) String ipAddress,
        String notes,
        @NotNull @Size(min = 3, max = 240) String reason) { }
