// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.util.List;
import java.util.Map;

public record MasterDataOptionUpdate(
        List<String> allowedSlotTypes,
        @Min(1) long categoryId,
        String imageUrl,
        Boolean isActive,
        @NotNull @Size(min = 1, max = 160) String name,
        String notes,
        String optionKind,
        @Min(0) @Max(100000) Long sortOrder,
        String source,
        Map<String, Double> statEffects,
        Double weaponCaliberInches,
        String weaponClass,
        MasterDataWeaponPerformance weaponPerformance) { }
