// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

public record MasterDataOverview(
        long categoryCount,
        long inactiveCount,
        long optionCount,
        long overriddenCount,
        long shipCount) { }
