// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public record MasterDataShipMortarModification(
        @Max(0) long broadsideCapacityDelta,
        @Max(0) long crewCapacityDelta,
        @Max(0) long durabilityDelta,
        Double holdCapacityPct,
        Double maneuverabilityDelta,
        @Max(20) double maxCaliberInches,
        @Max(8) long mortarCapacity,
        @NotNull @Size(min = 1, max = 500) String source,
        Double speedPct) { }
