// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Min;

public record MasterDataWeaponPerformance(
        @Min(0) double baseDamage,
        double reloadSeconds) { }
