// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

public record MasterDataCategoryCreate(
        Boolean isActive,
        @NotNull @Size(min = 1, max = 40) @Pattern(regexp = "^[a-z][a-z0-9_]*$") String key,
        @NotNull @Size(min = 1, max = 80) String label,
        @Min(0) @Max(100000) Long sortOrder) { }
