// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.util.List;

public record NewcomerGuideBlockInput(
        @NotNull String blockType,
        String body,
        @Size(max = 30) List<NewcomerGuideResourceInput> resources,
        @NotNull @Size(min = 1, max = 180) String title) { }
