// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.util.List;

public record NewcomerGuideUpdate(
        @Size(max = 30) List<NewcomerGuideBlockInput> blocks,
        @Size(max = 4000) String intro,
        @NotNull @Size(min = 1, max = 180) String title) { }
