// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.List;

public record NewcomerGuideRead(
        List<NewcomerGuideBlockRead> blocks,
        long id,
        @NotNull String intro,
        @NotNull String title,
        @NotNull LocalDateTime updatedAt,
        String updatedBy) { }
