// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Size;

public record OutboundWebhookTestRequest(
        @Size(max = 80) String eventType) { }
