// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

public record OutboundWebhookSummary(
        Long active,
        Long failedDeliveries,
        Long failing,
        Long successfulDeliveries,
        Long total) { }
