// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public record PasswordChangeRequest(
        @NotNull @Size(min = 1, max = 200) String currentPassword,
        @NotNull @Size(min = 12, max = 200) String newPassword) { }
