// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public record PrivacyContactResolve(
        @NotNull String decision,
        @NotNull @Size(min = 3, max = 4000) String resolutionNote) { }
