// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public record PrivacyContactCreate(
        @NotNull @Size(min = 10, max = 4000) String message,
        @NotNull @Size(min = 3, max = 254) String replyEmail,
        @NotNull @Size(min = 3, max = 160) String subject,
        @Size(max = 0) String website) { }
