// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

public record RaidHelperDispatchSelection(
        long destinationId,
        String leaderId,
        long templateId) { }
