// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

public record RaidHelperDestinationTestRequest(
        Long templateId,
        Boolean useMinimalPayload) { }
