// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public record RaidHelperEventLinkRead(
        long destinationId,
        @NotNull String destinationName,
        String errorMessage,
        String externalEventId,
        long id,
        @NotNull String lastOperation,
        @NotNull String profileName,
        @NotNull String status,
        LocalDateTime syncedAt,
        long templateId,
        @NotNull String templateName) { }
