// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;
import java.util.List;

public record RaidHelperTemplateRead(
        @Size(max = 2000) String announcementTemplate,
        List<String> categories,
        @NotNull LocalDateTime createdAt,
        @Size(max = 4000) String descriptionTemplate,
        long id,
        Boolean isActive,
        Boolean isDefault,
        @NotNull @Size(min = 1, max = 120) String name,
        @Size(min = 2, max = 12000) String payloadTemplateJson,
        long profileId,
        @NotNull String profileName,
        @Size(max = 80) String raidTemplateId,
        String scopeType,
        @Size(min = 1, max = 300) String titleTemplate,
        @NotNull LocalDateTime updatedAt,
        Boolean usesPremiumFeatures) { }
