// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public record RegistrationRequestPublic(
        @NotNull LocalDateTime createdAt,
        @NotNull String displayName,
        String fleetApplicationNote,
        Long fleetId,
        long id,
        @NotNull String status,
        @NotNull String username,
        Boolean wantsFleetMembership) { }
