// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import java.util.Map;

public record SecurityDashboard(
        List<SecurityDayBucket> days,
        List<SecurityIpRow> ips,
        Map<String, Long> signalCounts,
        Map<String, Long> threatCounts,
        @NotNull String threatLevel,
        @Min(0) @Max(100) long threatScore,
        long totalEvents,
        long uniqueIps) { }
