// Generated by scripts/migration/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;

public record SecurityReasonBreakdown(
        long eventCount,
        @NotNull String reason,
        @NotNull String requestTarget,
        @NotNull String signal) { }
