// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;

public record ShipRead(
        double armor,
        Long broadsideWeaponCapacity,
        long crewCapacity,
        Long dedicatedSpecialWeaponCapacity,
        long displacementTons,
        long durability,
        Long frontSpecialWeaponCapacity,
        Long frontWeaponCapacity,
        boolean hasLantern,
        long holdCapacity,
        long id,
        String imageUrl,
        boolean isActive,
        double maneuverability,
        Number maxMortarCaliberInches,
        ShipMortarModificationRead mortarModification,
        Long mortarWeaponCapacity,
        @NotNull String name,
        long rate,
        Long rearSpecialWeaponCapacity,
        Long rearWeaponCapacity,
        long sailSlots,
        long sailorMinimum,
        @NotNull String shipType,
        String source,
        Long specialWeaponCapacity,
        double speedKnots,
        double speedMinKnots,
        long upgradeSlots,
        String weaponLayout) { }
