// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

public record ShipRateWeaponClassRuleRead(
        @Min(1) @Max(7) long rate,
        @NotNull @Size(min = 1, max = 24) String weaponClass) { }
