// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.util.List;

public record SquadRosterMemberRead(
        @NotNull String displayName,
        long fleetMembershipId,
        @NotNull String fleetRole,
        List<Long> squadIds,
        long userId) { }
