// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public record SquadSummaryRead(
        boolean canAdminister,
        boolean canManage,
        @NotNull LocalDateTime createdAt,
        String currentUserRole,
        String description,
        long fleetId,
        String focus,
        long id,
        boolean isActive,
        boolean isMember,
        SquadMemberRead leader,
        Long maxMembers,
        long memberCount,
        @NotNull String name,
        @NotNull String slug,
        @NotNull LocalDateTime updatedAt) { }
