// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;

public record StatEffectDefinitionRead(
        @NotNull String category,
        @NotNull String key,
        @NotNull String label,
        @Min(0) @Max(6) long precision,
        @NotNull String translationKey,
        String unit,
        @NotNull String valueType) { }
