// Generated by infrastructure/scripts/generation/generate_java_contracts.py; do not edit manually.
package eu.royalblackwater.api.contract;

import jakarta.validation.constraints.NotNull;

public record WeaponSlotTypeRead(
        @NotNull String code,
        @NotNull String label,
        long sortOrder) { }
