export const optionTermGlossaries = {
  de: {
    'Ammunition Cradles': 'Munitionswiegen', 'Cellars': 'Keller', 'Double Hold': 'Doppelter Laderaum', 'Emergency Powder Charge': 'Notfall-Pulverladung', 'Extra Bunks': 'Zusätzliche Kojen', 'Fortified Gun Ports': 'Verstärkte Geschützpforten', 'Fortified Ports': 'Verstärkte Pforten', 'Incendiary Mixture': 'Brandmischung', 'Iron Ram': 'Eisenramme', 'Lightweight Hull': 'Leichter Rumpf', 'Long-Range Mortars': 'Langstrecken-Mörser', 'Maneuverable Helm': 'Wendiges Ruder', 'Reinforced Masts': 'Verstärkte Masten', 'Repair Arsenal': 'Reparaturarsenal', 'Structural Expansion': 'Strukturerweiterung', 'Strong Beams': 'Starke Balken', 'Sturdy Frames': 'Robuste Spanten', 'Swivel Mortars': 'Schwenkmörser', 'Teak Frames': 'Teakspanten',
    'Cheap Sails': 'Billige Segel', 'Stitched Sails': 'Genähte Segel', 'Ultra-light Sails': 'Ultraleichte Segel', 'Storm Sails': 'Sturmsegel', 'Elite Sails': 'Elite-Segel', 'Tacking Sails': 'Wendesegel', 'Reefed Sails': 'Gereffte Segel', 'Tarpaulin Sails': 'Planensegel', 'Raiding Sails': 'Überfallsegel', 'Imported Sails': 'Importierte Segel', 'Blue Lantern': 'Blaue Laterne', 'Bright Lantern': 'Helle Laterne', 'Golden Lantern': 'Goldene Laterne', 'Green Lantern': 'Grüne Laterne', 'Lilac Lantern': 'Fliederfarbene Laterne', 'Red Lantern': 'Rote Laterne', 'White Lantern': 'Weiße Laterne', 'Yellow Lantern': 'Gelbe Laterne', 'Ice Lantern': 'Eislaterne', 'Storm Lantern': 'Sturmlaterne',
    'Heavy Shots': 'Schwere Kugeln', 'Saxon Shots': 'Sächsische Kugeln', 'Bar Shots': 'Stangenschüsse', 'Burning Arrows': 'Brennende Pfeile', 'Fire Ship': 'Brandschiff', 'Grapeshot': 'Kartätschen', 'Heated Shots': 'Glühende Kugeln', 'Large Phosphorous Mine': 'Große Phosphormine', 'Large Shrapnel Mines': 'Große Schrapnellminen', 'Phosphorous Shots': 'Phosphorschüsse', 'Round Shots': 'Runde Kugeln', 'Shrapnel Rounds': 'Schrapnellgeschosse', 'Small Flaming Barrels': 'Kleine Brandfässer', 'Small Gunpowder Barrels': 'Kleine Schießpulverfässer', 'Small Phosphorous Barrels': 'Kleine Phosphorfässer', 'Strike Rounds': 'Treffergeschosse',
    'Repair Kit': 'Reparaturset', 'Patches': 'Flicken', 'Additional Sails': 'Zusatzsegel', 'Double Powder': 'Doppelpulver', 'Signal Flare': 'Signalrakete', 'Ration': 'Ration', 'Smoke Bomb': 'Rauchbombe', 'Smoke Screen': 'Rauchwand', 'Bribery': 'Bestechung', 'Field Kit': 'Feldset', 'Horn': 'Horn', 'Powder Charge': 'Pulverladung', 'Poseidon\'s Hook': 'Poseidons Haken',
    'Animals': 'Tiere', 'Beam': 'Balken', 'Beer': 'Bier', 'Bulkhead': 'Schott', 'Canvas': 'Segeltuch', 'Chest': 'Kiste', 'Coal': 'Kohle', 'Copper Ore': 'Kupfererz', 'Dates': 'Datteln', 'Fabric': 'Stoff', 'Fresh Meat': 'Frischfleisch', 'Grain': 'Getreide', 'Iron Ore': 'Eisenerz', 'Leather': 'Leder', 'Nuts': 'Nüsse', 'Oil': 'Öl', 'Pineapples': 'Ananas', 'Provision': 'Proviant', 'Resin': 'Harz', 'Rugs': 'Teppiche', 'Salt': 'Salz', 'Silk': 'Seide', 'Supplies': 'Vorräte', 'Tobacco': 'Tabak', 'Water': 'Wasser', 'Whale Oil': 'Walöl', 'Wine': 'Wein', 'Wood': 'Holz', 'Wreckage': 'Wrackteile',
  },
  fr: {
    'Ammunition Cradles': 'Berceaux de munitions', 'Cellars': 'Celliers', 'Double Hold': 'Double cale', 'Emergency Powder Charge': 'Charge de poudre d’urgence', 'Extra Bunks': 'Couchettes supplémentaires', 'Fortified Gun Ports': 'Sabords renforcés', 'Fortified Ports': 'Sabords fortifiés', 'Incendiary Mixture': 'Mélange incendiaire', 'Iron Ram': 'Éperon de fer', 'Lightweight Hull': 'Coque légère', 'Long-Range Mortars': 'Mortiers longue portée', 'Maneuverable Helm': 'Gouvernail maniable', 'Reinforced Masts': 'Mâts renforcés', 'Repair Arsenal': 'Arsenal de réparation', 'Structural Expansion': 'Extension structurelle', 'Strong Beams': 'Poutres solides', 'Sturdy Frames': 'Membrures robustes', 'Swivel Mortars': 'Mortiers pivotants', 'Teak Frames': 'Membrures en teck',
    'Cheap Sails': 'Voiles bon marché', 'Stitched Sails': 'Voiles cousues', 'Ultra-light Sails': 'Voiles ultralégères', 'Storm Sails': 'Voiles de tempête', 'Elite Sails': 'Voiles d’élite', 'Tacking Sails': 'Voiles de virement', 'Reefed Sails': 'Voiles arisées', 'Tarpaulin Sails': 'Voiles bâchées', 'Raiding Sails': 'Voiles de raid', 'Imported Sails': 'Voiles importées', 'Blue Lantern': 'Lanterne bleue', 'Bright Lantern': 'Lanterne brillante', 'Golden Lantern': 'Lanterne dorée', 'Green Lantern': 'Lanterne verte', 'Lilac Lantern': 'Lanterne lilas', 'Red Lantern': 'Lanterne rouge', 'White Lantern': 'Lanterne blanche', 'Yellow Lantern': 'Lanterne jaune', 'Ice Lantern': 'Lanterne de glace', 'Storm Lantern': 'Lanterne tempête',
    'Heavy Shots': 'Boulets lourds', 'Saxon Shots': 'Boulets saxons', 'Bar Shots': 'Boulets ramés', 'Burning Arrows': 'Flèches enflammées', 'Fire Ship': 'Brûlot', 'Grapeshot': 'Mitraille', 'Heated Shots': 'Boulets chauffés', 'Large Phosphorous Mine': 'Grande mine au phosphore', 'Large Shrapnel Mines': 'Grandes mines à shrapnels', 'Phosphorous Shots': 'Boulets au phosphore', 'Round Shots': 'Boulets ronds', 'Shrapnel Rounds': 'Obus à shrapnels', 'Small Flaming Barrels': 'Petits tonneaux incendiaires', 'Small Gunpowder Barrels': 'Petits tonneaux de poudre', 'Small Phosphorous Barrels': 'Petits tonneaux au phosphore', 'Strike Rounds': 'Projectiles de frappe',
    'Repair Kit': 'Kit de réparation', 'Patches': 'Rustines', 'Additional Sails': 'Voiles supplémentaires', 'Double Powder': 'Double poudre', 'Signal Flare': 'Fusée de signalisation', 'Ration': 'Ration', 'Smoke Bomb': 'Bombe fumigène', 'Smoke Screen': 'Écran de fumée', 'Bribery': 'Pot-de-vin', 'Field Kit': 'Kit de terrain', 'Horn': 'Corne', 'Powder Charge': 'Charge de poudre', 'Poseidon\'s Hook': 'Crochet de Poséidon',
    'Animals': 'Animaux', 'Beam': 'Poutre', 'Beer': 'Bière', 'Bulkhead': 'Cloison', 'Canvas': 'Toile', 'Chest': 'Coffre', 'Coal': 'Charbon', 'Copper Ore': 'Minerai de cuivre', 'Dates': 'Dattes', 'Fabric': 'Tissu', 'Fresh Meat': 'Viande fraîche', 'Grain': 'Grain', 'Iron Ore': 'Minerai de fer', 'Leather': 'Cuir', 'Nuts': 'Noix', 'Oil': 'Huile', 'Pineapples': 'Ananas', 'Provision': 'Provisions', 'Resin': 'Résine', 'Rugs': 'Tapis', 'Salt': 'Sel', 'Silk': 'Soie', 'Supplies': 'Ravitaillement', 'Tobacco': 'Tabac', 'Water': 'Eau', 'Whale Oil': 'Huile de baleine', 'Wine': 'Vin', 'Wood': 'Bois', 'Wreckage': 'Débris',
  },
  es: {
    'Ammunition Cradles': 'Soportes de munición', 'Cellars': 'Bodegas inferiores', 'Double Hold': 'Doble bodega', 'Emergency Powder Charge': 'Carga de pólvora de emergencia', 'Extra Bunks': 'Literas extra', 'Fortified Gun Ports': 'Portas reforzadas', 'Fortified Ports': 'Portas fortificadas', 'Incendiary Mixture': 'Mezcla incendiaria', 'Iron Ram': 'Espolón de hierro', 'Lightweight Hull': 'Casco ligero', 'Long-Range Mortars': 'Morteros de largo alcance', 'Maneuverable Helm': 'Timón maniobrable', 'Reinforced Masts': 'Mástiles reforzados', 'Repair Arsenal': 'Arsenal de reparación', 'Structural Expansion': 'Expansión estructural', 'Strong Beams': 'Vigas fuertes', 'Sturdy Frames': 'Cuadernas robustas', 'Swivel Mortars': 'Morteros giratorios', 'Teak Frames': 'Cuadernas de teca',
    'Cheap Sails': 'Velas baratas', 'Stitched Sails': 'Velas cosidas', 'Ultra-light Sails': 'Velas ultraligeras', 'Storm Sails': 'Velas de tormenta', 'Elite Sails': 'Velas de élite', 'Tacking Sails': 'Velas de virada', 'Reefed Sails': 'Velas rizadas', 'Tarpaulin Sails': 'Velas de lona', 'Raiding Sails': 'Velas de incursión', 'Imported Sails': 'Velas importadas', 'Blue Lantern': 'Linterna azul', 'Bright Lantern': 'Linterna brillante', 'Golden Lantern': 'Linterna dorada', 'Green Lantern': 'Linterna verde', 'Lilac Lantern': 'Linterna lila', 'Red Lantern': 'Linterna roja', 'White Lantern': 'Linterna blanca', 'Yellow Lantern': 'Linterna amarilla', 'Ice Lantern': 'Linterna de hielo', 'Storm Lantern': 'Linterna de tormenta',
    'Heavy Shots': 'Proyectiles pesados', 'Saxon Shots': 'Proyectiles sajones', 'Bar Shots': 'Tiros de barra', 'Burning Arrows': 'Flechas ardientes', 'Fire Ship': 'Brulote', 'Grapeshot': 'Metralla', 'Heated Shots': 'Tiros al rojo vivo', 'Large Phosphorous Mine': 'Mina grande de fósforo', 'Large Shrapnel Mines': 'Minas grandes de metralla', 'Phosphorous Shots': 'Tiros de fósforo', 'Round Shots': 'Balas redondas', 'Shrapnel Rounds': 'Proyectiles de metralla', 'Small Flaming Barrels': 'Barriles incendiarios pequeños', 'Small Gunpowder Barrels': 'Barriles pequeños de pólvora', 'Small Phosphorous Barrels': 'Barriles pequeños de fósforo', 'Strike Rounds': 'Proyectiles de impacto',
    'Repair Kit': 'Kit de reparación', 'Patches': 'Parches', 'Additional Sails': 'Velas adicionales', 'Double Powder': 'Pólvora doble', 'Signal Flare': 'Bengala de señal', 'Ration': 'Ración', 'Smoke Bomb': 'Bomba de humo', 'Smoke Screen': 'Pantalla de humo', 'Bribery': 'Soborno', 'Field Kit': 'Kit de campo', 'Horn': 'Cuerno', 'Powder Charge': 'Carga de pólvora', 'Poseidon\'s Hook': 'Gancho de Poseidón',
    'Animals': 'Animales', 'Beam': 'Viga', 'Beer': 'Cerveza', 'Bulkhead': 'Mamparo', 'Canvas': 'Lona', 'Chest': 'Cofre', 'Coal': 'Carbón', 'Copper Ore': 'Mineral de cobre', 'Dates': 'Dátiles', 'Fabric': 'Tela', 'Fresh Meat': 'Carne fresca', 'Grain': 'Grano', 'Iron Ore': 'Mineral de hierro', 'Leather': 'Cuero', 'Nuts': 'Nueces', 'Oil': 'Aceite', 'Pineapples': 'Piñas', 'Provision': 'Provisiones', 'Resin': 'Resina', 'Rugs': 'Alfombras', 'Salt': 'Sal', 'Silk': 'Seda', 'Supplies': 'Suministros', 'Tobacco': 'Tabaco', 'Water': 'Agua', 'Whale Oil': 'Aceite de ballena', 'Wine': 'Vino', 'Wood': 'Madera', 'Wreckage': 'Restos',
  },
  pt: {
    'Ammunition Cradles': 'Suportes de munição', 'Cellars': 'Porões inferiores', 'Double Hold': 'Porão duplo', 'Emergency Powder Charge': 'Carga de pólvora de emergência', 'Extra Bunks': 'Beliches extras', 'Fortified Gun Ports': 'Portinholas reforçadas', 'Fortified Ports': 'Portas fortificadas', 'Incendiary Mixture': 'Mistura incendiária', 'Iron Ram': 'Aríete de ferro', 'Lightweight Hull': 'Casco leve', 'Long-Range Mortars': 'Morteiros de longo alcance', 'Maneuverable Helm': 'Leme manobrável', 'Reinforced Masts': 'Mastros reforçados', 'Repair Arsenal': 'Arsenal de reparo', 'Structural Expansion': 'Expansão estrutural', 'Strong Beams': 'Vigas fortes', 'Sturdy Frames': 'Armações robustas', 'Swivel Mortars': 'Morteiros giratórios', 'Teak Frames': 'Armações de teca',
    'Cheap Sails': 'Velas baratas', 'Stitched Sails': 'Velas costuradas', 'Ultra-light Sails': 'Velas ultraleves', 'Storm Sails': 'Velas de tempestade', 'Elite Sails': 'Velas de elite', 'Tacking Sails': 'Velas de viragem', 'Reefed Sails': 'Velas rizadas', 'Tarpaulin Sails': 'Velas de lona', 'Raiding Sails': 'Velas de ataque', 'Imported Sails': 'Velas importadas', 'Blue Lantern': 'Lanterna azul', 'Bright Lantern': 'Lanterna brilhante', 'Golden Lantern': 'Lanterna dourada', 'Green Lantern': 'Lanterna verde', 'Lilac Lantern': 'Lanterna lilás', 'Red Lantern': 'Lanterna vermelha', 'White Lantern': 'Lanterna branca', 'Yellow Lantern': 'Lanterna amarela', 'Ice Lantern': 'Lanterna de gelo', 'Storm Lantern': 'Lanterna de tempestade',
    'Heavy Shots': 'Tiros pesados', 'Saxon Shots': 'Tiros saxões', 'Bar Shots': 'Tiros de barra', 'Burning Arrows': 'Flechas flamejantes', 'Fire Ship': 'Navio incendiário', 'Grapeshot': 'Metralha', 'Heated Shots': 'Tiros aquecidos', 'Large Phosphorous Mine': 'Mina grande de fósforo', 'Large Shrapnel Mines': 'Minas grandes de estilhaços', 'Phosphorous Shots': 'Tiros de fósforo', 'Round Shots': 'Tiros redondos', 'Shrapnel Rounds': 'Projéteis de estilhaços', 'Small Flaming Barrels': 'Barris incendiários pequenos', 'Small Gunpowder Barrels': 'Barris pequenos de pólvora', 'Small Phosphorous Barrels': 'Barris pequenos de fósforo', 'Strike Rounds': 'Projéteis de impacto',
    'Repair Kit': 'Kit de reparo', 'Patches': 'Remendos', 'Additional Sails': 'Velas adicionais', 'Double Powder': 'Pólvora dupla', 'Signal Flare': 'Sinalizador', 'Ration': 'Ração', 'Smoke Bomb': 'Bomba de fumaça', 'Smoke Screen': 'Cortina de fumaça', 'Bribery': 'Suborno', 'Field Kit': 'Kit de campo', 'Horn': 'Chifre', 'Powder Charge': 'Carga de pólvora', 'Poseidon\'s Hook': 'Gancho de Poseidon',
    'Animals': 'Animais', 'Beam': 'Viga', 'Beer': 'Cerveja', 'Bulkhead': 'Antepara', 'Canvas': 'Lona', 'Chest': 'Baú', 'Coal': 'Carvão', 'Copper Ore': 'Minério de cobre', 'Dates': 'Tâmaras', 'Fabric': 'Tecido', 'Fresh Meat': 'Carne fresca', 'Grain': 'Grãos', 'Iron Ore': 'Minério de ferro', 'Leather': 'Couro', 'Nuts': 'Nozes', 'Oil': 'Óleo', 'Pineapples': 'Abacaxis', 'Provision': 'Provisões', 'Resin': 'Resina', 'Rugs': 'Tapetes', 'Salt': 'Sal', 'Silk': 'Seda', 'Supplies': 'Suprimentos', 'Tobacco': 'Tabaco', 'Water': 'Água', 'Whale Oil': 'Óleo de baleia', 'Wine': 'Vinho', 'Wood': 'Madeira', 'Wreckage': 'Destroços',
  },
  ru: {
    'Ammunition Cradles': 'Лотки для боеприпасов', 'Cellars': 'Погреба', 'Double Hold': 'Двойной трюм', 'Emergency Powder Charge': 'Аварийный пороховой заряд', 'Extra Bunks': 'Дополнительные койки', 'Fortified Gun Ports': 'Усиленные пушечные порты', 'Fortified Ports': 'Укреплённые порты', 'Incendiary Mixture': 'Зажигательная смесь', 'Iron Ram': 'Железный таран', 'Lightweight Hull': 'Облегчённый корпус', 'Long-Range Mortars': 'Дальнобойные мортиры', 'Maneuverable Helm': 'Манёвренный руль', 'Reinforced Masts': 'Усиленные мачты', 'Repair Arsenal': 'Ремонтный арсенал', 'Structural Expansion': 'Структурное расширение', 'Strong Beams': 'Прочные балки', 'Sturdy Frames': 'Крепкие шпангоуты', 'Swivel Mortars': 'Поворотные мортиры', 'Teak Frames': 'Тиковые шпангоуты',
    'Cheap Sails': 'Дешёвые паруса', 'Stitched Sails': 'Сшитые паруса', 'Ultra-light Sails': 'Сверхлёгкие паруса', 'Storm Sails': 'Штормовые паруса', 'Elite Sails': 'Элитные паруса', 'Tacking Sails': 'Лавировочные паруса', 'Reefed Sails': 'Зарифленные паруса', 'Tarpaulin Sails': 'Брезентовые паруса', 'Raiding Sails': 'Рейдерские паруса', 'Imported Sails': 'Импортные паруса', 'Blue Lantern': 'Синий фонарь', 'Bright Lantern': 'Яркий фонарь', 'Golden Lantern': 'Золотой фонарь', 'Green Lantern': 'Зелёный фонарь', 'Lilac Lantern': 'Сиреневый фонарь', 'Red Lantern': 'Красный фонарь', 'White Lantern': 'Белый фонарь', 'Yellow Lantern': 'Жёлтый фонарь', 'Ice Lantern': 'Ледяной фонарь', 'Storm Lantern': 'Штормовой фонарь',
    'Heavy Shots': 'Тяжёлые ядра', 'Saxon Shots': 'Саксонские ядра', 'Bar Shots': 'Книппели', 'Burning Arrows': 'Горящие стрелы', 'Fire Ship': 'Брандер', 'Grapeshot': 'Картечь', 'Heated Shots': 'Калёные ядра', 'Large Phosphorous Mine': 'Большая фосфорная мина', 'Large Shrapnel Mines': 'Большие шрапнельные мины', 'Phosphorous Shots': 'Фосфорные ядра', 'Round Shots': 'Круглые ядра', 'Shrapnel Rounds': 'Шрапнельные снаряды', 'Small Flaming Barrels': 'Малые горящие бочки', 'Small Gunpowder Barrels': 'Малые пороховые бочки', 'Small Phosphorous Barrels': 'Малые фосфорные бочки', 'Strike Rounds': 'Ударные снаряды',
    'Repair Kit': 'Ремкомплект', 'Patches': 'Заплаты', 'Additional Sails': 'Дополнительные паруса', 'Double Powder': 'Двойной порох', 'Signal Flare': 'Сигнальная ракета', 'Ration': 'Рацион', 'Smoke Bomb': 'Дымовая бомба', 'Smoke Screen': 'Дымовая завеса', 'Bribery': 'Взятка', 'Field Kit': 'Полевой набор', 'Horn': 'Горн', 'Powder Charge': 'Пороховой заряд', 'Poseidon\'s Hook': 'Крюк Посейдона',
    'Animals': 'Животные', 'Beam': 'Балка', 'Beer': 'Пиво', 'Bulkhead': 'Переборка', 'Canvas': 'Парусина', 'Chest': 'Сундук', 'Coal': 'Уголь', 'Copper Ore': 'Медная руда', 'Dates': 'Финики', 'Fabric': 'Ткань', 'Fresh Meat': 'Свежее мясо', 'Grain': 'Зерно', 'Iron Ore': 'Железная руда', 'Leather': 'Кожа', 'Nuts': 'Орехи', 'Oil': 'Масло', 'Pineapples': 'Ананасы', 'Provision': 'Провизия', 'Resin': 'Смола', 'Rugs': 'Ковры', 'Salt': 'Соль', 'Silk': 'Шёлк', 'Supplies': 'Припасы', 'Tobacco': 'Табак', 'Water': 'Вода', 'Whale Oil': 'Китовый жир', 'Wine': 'Вино', 'Wood': 'Дерево', 'Wreckage': 'Обломки',
  },
  cn: {
    'Ammunition Cradles': '弹药托架', 'Cellars': '地窖', 'Double Hold': '双层货舱', 'Emergency Powder Charge': '应急火药装药', 'Extra Bunks': '额外床位', 'Fortified Gun Ports': '强化炮门', 'Fortified Ports': '加固炮门', 'Incendiary Mixture': '燃烧混合物', 'Iron Ram': '铁质撞角', 'Lightweight Hull': '轻量船体', 'Long-Range Mortars': '远程迫击炮', 'Maneuverable Helm': '机动舵', 'Reinforced Masts': '强化桅杆', 'Repair Arsenal': '维修军械库', 'Structural Expansion': '结构扩展', 'Strong Beams': '坚固横梁', 'Sturdy Frames': '坚固肋骨', 'Swivel Mortars': '旋转迫击炮', 'Teak Frames': '柚木肋骨',
    'Cheap Sails': '廉价船帆', 'Stitched Sails': '缝制船帆', 'Ultra-light Sails': '超轻船帆', 'Storm Sails': '风暴船帆', 'Elite Sails': '精英船帆', 'Tacking Sails': '抢风船帆', 'Reefed Sails': '缩帆', 'Tarpaulin Sails': '篷布船帆', 'Raiding Sails': '突袭船帆', 'Imported Sails': '进口船帆', 'Blue Lantern': '蓝色灯笼', 'Bright Lantern': '明亮灯笼', 'Golden Lantern': '金色灯笼', 'Green Lantern': '绿色灯笼', 'Lilac Lantern': '淡紫色灯笼', 'Red Lantern': '红色灯笼', 'White Lantern': '白色灯笼', 'Yellow Lantern': '黄色灯笼', 'Ice Lantern': '冰灯笼', 'Storm Lantern': '风暴灯笼',
    'Heavy Shots': '重型炮弹', 'Saxon Shots': '萨克森炮弹', 'Bar Shots': '链杆弹', 'Burning Arrows': '燃烧箭', 'Fire Ship': '火船', 'Grapeshot': '霰弹', 'Heated Shots': '炽热炮弹', 'Large Phosphorous Mine': '大型磷矿雷', 'Large Shrapnel Mines': '大型破片雷', 'Phosphorous Shots': '磷炮弹', 'Round Shots': '圆炮弹', 'Shrapnel Rounds': '破片弹', 'Small Flaming Barrels': '小型燃烧桶', 'Small Gunpowder Barrels': '小型火药桶', 'Small Phosphorous Barrels': '小型磷桶', 'Strike Rounds': '冲击弹',
    'Repair Kit': '维修包', 'Patches': '补丁', 'Additional Sails': '备用帆', 'Double Powder': '双倍火药', 'Signal Flare': '信号弹', 'Ration': '口粮', 'Smoke Bomb': '烟雾弹', 'Smoke Screen': '烟幕', 'Bribery': '贿赂', 'Field Kit': '野战包', 'Horn': '号角', 'Powder Charge': '火药装药', 'Poseidon\'s Hook': '波塞冬之钩',
    'Animals': '动物', 'Beam': '横梁', 'Beer': '啤酒', 'Bulkhead': '隔舱板', 'Canvas': '帆布', 'Chest': '箱子', 'Coal': '煤炭', 'Copper Ore': '铜矿石', 'Dates': '椰枣', 'Fabric': '织物', 'Fresh Meat': '鲜肉', 'Grain': '谷物', 'Iron Ore': '铁矿石', 'Leather': '皮革', 'Nuts': '坚果', 'Oil': '油', 'Pineapples': '菠萝', 'Provision': '补给', 'Resin': '树脂', 'Rugs': '地毯', 'Salt': '盐', 'Silk': '丝绸', 'Supplies': '物资', 'Tobacco': '烟草', 'Water': '水', 'Whale Oil': '鲸油', 'Wine': '葡萄酒', 'Wood': '木材', 'Wreckage': '残骸',
  },
}
