const en = {
  title: 'Your data rights', description: 'Export your stored data, correct your profile directly or submit a reviewed correction or deletion request.', export: 'Download data export', exportReady: 'Your export is ready.', exportError: 'The export could not be created.', loadError: 'Privacy requests could not be loaded.', requestType: 'Request type', correction: 'Correction', deletion: 'Account deletion', details: 'What should be corrected or deleted?', confirmation: 'Enter {username} to confirm deletion', submit: 'Submit request', requestCreated: 'Privacy request submitted.', requestError: 'Privacy request could not be submitted.', types: { correction: 'Correction', deletion: 'Deletion' }, status: { pending: 'Pending review', completed: 'Completed', rejected: 'Rejected' }, adminTitle: 'Privacy requests', adminDescription: 'Review correction and deletion requests with an auditable decision.', empty: 'No privacy requests.', resolutionNote: 'Resolution note', complete: 'Complete', reject: 'Reject',
}

const de = {
  title: 'Deine Datenschutzrechte', description: 'Exportiere deine gespeicherten Daten, berichtige dein Profil direkt oder stelle einen geprüften Berichtigungs- oder Löschantrag.', export: 'Datenexport herunterladen', exportReady: 'Dein Export ist bereit.', exportError: 'Der Export konnte nicht erstellt werden.', loadError: 'Datenschutzanträge konnten nicht geladen werden.', requestType: 'Antragsart', correction: 'Berichtigung', deletion: 'Accountlöschung', details: 'Was soll berichtigt oder gelöscht werden?', confirmation: 'Zur Löschbestätigung {username} eingeben', submit: 'Antrag absenden', requestCreated: 'Datenschutzantrag wurde eingereicht.', requestError: 'Datenschutzantrag konnte nicht eingereicht werden.', types: { correction: 'Berichtigung', deletion: 'Löschung' }, status: { pending: 'In Prüfung', completed: 'Abgeschlossen', rejected: 'Abgelehnt' }, adminTitle: 'Datenschutzanträge', adminDescription: 'Berichtigungs- und Löschanträge nachvollziehbar bearbeiten.', empty: 'Keine Datenschutzanträge.', resolutionNote: 'Bearbeitungsvermerk', complete: 'Abschließen', reject: 'Ablehnen',
}

export const dataRightsMessages = {
  en: { privacy: { data: en } }, de: { privacy: { data: de } },
  fr: { privacy: { data: { ...en, title: 'Vos droits sur les données', export: 'Télécharger les données', requestType: 'Type de demande', correction: 'Rectification', deletion: 'Suppression du compte', submit: 'Envoyer la demande', requestCreated: 'Demande envoyée.', requestError: 'La demande n’a pas pu être envoyée.', types: { correction: 'Rectification', deletion: 'Suppression' }, status: { pending: 'En attente', completed: 'Terminée', rejected: 'Refusée' }, adminTitle: 'Demandes de confidentialité', resolutionNote: 'Note de traitement', complete: 'Terminer' } } },
  es: { privacy: { data: { ...en, title: 'Tus derechos de datos', export: 'Descargar datos', requestType: 'Tipo de solicitud', correction: 'Corrección', deletion: 'Eliminar cuenta', submit: 'Enviar solicitud', requestCreated: 'Solicitud enviada.', requestError: 'No se pudo enviar la solicitud.', types: { correction: 'Corrección', deletion: 'Eliminación' }, status: { pending: 'Pendiente', completed: 'Completada', rejected: 'Rechazada' }, adminTitle: 'Solicitudes de privacidad', resolutionNote: 'Nota de resolución', complete: 'Completar' } } },
  pt: { privacy: { data: { ...en, title: 'Os seus direitos de dados', export: 'Transferir dados', requestType: 'Tipo de pedido', correction: 'Correção', deletion: 'Eliminar conta', submit: 'Enviar pedido', requestCreated: 'Pedido enviado.', requestError: 'Não foi possível enviar o pedido.', types: { correction: 'Correção', deletion: 'Eliminação' }, status: { pending: 'Pendente', completed: 'Concluído', rejected: 'Rejeitado' }, adminTitle: 'Pedidos de privacidade', resolutionNote: 'Nota de resolução', complete: 'Concluir' } } },
  ru: { privacy: { data: { ...en, title: 'Ваши права на данные', export: 'Скачать данные', requestType: 'Тип запроса', correction: 'Исправление', deletion: 'Удаление аккаунта', submit: 'Отправить запрос', requestCreated: 'Запрос отправлен.', requestError: 'Не удалось отправить запрос.', types: { correction: 'Исправление', deletion: 'Удаление' }, status: { pending: 'На рассмотрении', completed: 'Выполнено', rejected: 'Отклонено' }, adminTitle: 'Запросы конфиденциальности', resolutionNote: 'Комментарий', complete: 'Выполнить' } } },
  cn: { privacy: { data: { ...en, title: '您的数据权利', export: '下载数据', requestType: '请求类型', correction: '更正', deletion: '删除账户', submit: '提交请求', requestCreated: '请求已提交。', requestError: '无法提交请求。', types: { correction: '更正', deletion: '删除' }, status: { pending: '待审核', completed: '已完成', rejected: '已拒绝' }, adminTitle: '隐私请求', resolutionNote: '处理说明', complete: '完成' } } },
}
