export const legalNoticeMessages = {
  en: {
    legalNotice: {
      public: {
        eyebrow: 'Provider information', title: 'Legal Notice', subtitle: 'Information about the person or organization responsible for this website.',
        footerLink: 'Legal Notice', loading: 'Loading legal notice ...', loadError: 'The legal notice could not be loaded.', retry: 'Try again',
        draftTitle: 'Legal notice in preparation', draftText: 'The provider information is currently maintained as a draft and has not been published yet.',
        draftLegalHint: 'This is a technical publication status and not a statement about whether statutory information duties apply.', updated: 'Last updated: {date}',
      },
      admin: {
        eyebrow: 'Administration', title: 'Legal Notice', navigation: 'Legal Notice', subtitle: 'Prepare provider information from environment defaults and publish it when complete.',
        configurationTitle: 'Provider information', configurationHint: 'Environment values initialize this document. Administrator changes are stored in the database and survive updates.',
        legalWarningTitle: 'Legal review required', legalWarningText: 'This form supports preparation but does not determine whether an information duty already applies. In Germany, § 18 MStV can require name and address for telemedia that are not exclusively personal or family-related; § 5 DDG may add further information duties where applicable.',
        loading: 'Loading provider information ...', loadError: 'Provider information could not be loaded.', saveError: 'Provider information could not be saved.', saved: 'Provider information saved.',
        publish: 'Publish legal notice', publishHint: 'Only publish after the mandatory fields and all applicable optional sections have been reviewed.',
        editorialHint: 'Complete this section only if a person responsible for journalistic-editorial content must be named.',
        disputeHint: 'Do not copy outdated EU dispute-resolution wording. Add a reviewed statement only where it applies.',
        save: 'Save', saving: 'Saving ...', reload: 'Discard local changes', preview: 'Open public page', resetEnvironment: 'Restore .env values',
        resetConfirm: 'Replace all administrator changes with the current .env values?', resetSuccess: 'Environment values restored.', resetError: 'Environment values could not be restored.',
        updatedBy: 'Last changed by {user} on {date}.', sources: { environment: '.env defaults', admin: 'Administrator values' },
      },
      sections: { provider: 'Provider and address', contact: 'Contact', register: 'Register information', tax: 'Tax information', supervision: 'Supervisory authority', editorial: 'Editorial responsibility', dispute: 'Consumer dispute resolution', additional: 'Additional information' },
      fields: { providerName: 'Name / organization', legalForm: 'Legal form', representedBy: 'Represented by', street: 'Street and house number', postalCode: 'Postal code', city: 'City', country: 'Country', email: 'Email', phone: 'Telephone', registerName: 'Register', registerCourt: 'Register court', registerNumber: 'Register number', vatId: 'VAT identification number', businessId: 'Business identification number', supervisoryAuthority: 'Competent supervisory authority', editorialName: 'Responsible person', disputeResolution: 'Dispute-resolution statement', additionalInformation: 'Additional provider information' },
    },
  },
  de: {
    legalNotice: {
      public: {
        eyebrow: 'Anbieterangaben', title: 'Impressum', subtitle: 'Angaben zur verantwortlichen Person oder Organisation dieses Webangebots.',
        footerLink: 'Impressum', loading: 'Impressum wird geladen ...', loadError: 'Das Impressum konnte nicht geladen werden.', retry: 'Erneut versuchen',
        draftTitle: 'Impressum in Vorbereitung', draftText: 'Die Anbieterangaben werden derzeit als Entwurf gepflegt und sind noch nicht veröffentlicht.',
        draftLegalHint: 'Dies ist nur ein technischer Veröffentlichungsstatus und keine Aussage darüber, ob bereits gesetzliche Informationspflichten bestehen.', updated: 'Zuletzt aktualisiert: {date}',
      },
      admin: {
        eyebrow: 'Administration', title: 'Impressum', navigation: 'Impressum', subtitle: 'Anbieterangaben aus den Umgebungswerten vorbereiten und nach Prüfung veröffentlichen.',
        configurationTitle: 'Anbieterangaben', configurationHint: 'Die .env-Werte initialisieren diesen Inhalt. Änderungen durch Administratoren werden dauerhaft in der Datenbank gespeichert und durch Updates nicht überschrieben.',
        legalWarningTitle: 'Rechtliche Prüfung erforderlich', legalWarningText: 'Dieses Formular unterstützt die Vorbereitung, entscheidet aber nicht, ob bereits eine Pflicht besteht. In Deutschland kann § 18 MStV Name und Anschrift für Telemedien verlangen, die nicht ausschließlich persönlichen oder familiären Zwecken dienen; § 5 DDG kann gegebenenfalls weitere Angaben verlangen.',
        loading: 'Anbieterangaben werden geladen ...', loadError: 'Die Anbieterangaben konnten nicht geladen werden.', saveError: 'Die Anbieterangaben konnten nicht gespeichert werden.', saved: 'Anbieterangaben gespeichert.',
        publish: 'Impressum veröffentlichen', publishHint: 'Erst veröffentlichen, nachdem Pflichtfelder und alle einschlägigen optionalen Bereiche geprüft wurden.',
        editorialHint: 'Diesen Abschnitt nur vollständig ausfüllen, wenn eine verantwortliche Person für journalistisch-redaktionelle Inhalte zu benennen ist.',
        disputeHint: 'Keine veralteten EU-Streitbeilegungstexte übernehmen. Nur eine rechtlich geprüfte und einschlägige Erklärung eintragen.',
        save: 'Speichern', saving: 'Speichert ...', reload: 'Lokale Änderungen verwerfen', preview: 'Öffentliche Seite öffnen', resetEnvironment: '.env-Werte wiederherstellen',
        resetConfirm: 'Alle Administratoränderungen durch die aktuellen .env-Werte ersetzen?', resetSuccess: 'Umgebungswerte wiederhergestellt.', resetError: 'Die Umgebungswerte konnten nicht wiederhergestellt werden.',
        updatedBy: 'Zuletzt geändert von {user} am {date}.', sources: { environment: '.env-Vorgaben', admin: 'Administratorwerte' },
      },
      sections: { provider: 'Anbieter und Anschrift', contact: 'Kontakt', register: 'Registerangaben', tax: 'Steuerangaben', supervision: 'Aufsichtsbehörde', editorial: 'Redaktionell verantwortlich', dispute: 'Verbraucherstreitbeilegung', additional: 'Weitere Angaben' },
      fields: { providerName: 'Name / Organisation', legalForm: 'Rechtsform', representedBy: 'Vertreten durch', street: 'Straße und Hausnummer', postalCode: 'Postleitzahl', city: 'Ort', country: 'Land', email: 'E-Mail', phone: 'Telefon', registerName: 'Register', registerCourt: 'Registergericht', registerNumber: 'Registernummer', vatId: 'Umsatzsteuer-Identifikationsnummer', businessId: 'Wirtschafts-Identifikationsnummer', supervisoryAuthority: 'Zuständige Aufsichtsbehörde', editorialName: 'Verantwortliche Person', disputeResolution: 'Erklärung zur Streitbeilegung', additionalInformation: 'Weitere Anbieterangaben' },
    },
  },
  fr: {
    legalNotice: {
      public: { eyebrow: 'Informations sur le fournisseur', title: 'Mentions légales', subtitle: 'Informations sur la personne ou l’organisation responsable de ce site.', footerLink: 'Mentions légales', loading: 'Chargement des mentions légales ...', loadError: 'Les mentions légales n’ont pas pu être chargées.', retry: 'Réessayer', draftTitle: 'Mentions légales en préparation', draftText: 'Les informations du fournisseur sont actuellement conservées comme brouillon et ne sont pas encore publiées.', draftLegalHint: 'Il s’agit d’un statut technique de publication, et non d’une déclaration sur l’application d’obligations légales.', updated: 'Dernière mise à jour : {date}' },
      admin: { eyebrow: 'Administration', title: 'Mentions légales', navigation: 'Mentions légales', subtitle: 'Préparer les informations du fournisseur depuis les valeurs d’environnement et les publier après vérification.', configurationTitle: 'Informations du fournisseur', configurationHint: 'Les valeurs .env initialisent ce document. Les modifications administrateur sont enregistrées en base de données et survivent aux mises à jour.', legalWarningTitle: 'Vérification juridique requise', legalWarningText: 'Ce formulaire aide à préparer les informations, mais ne détermine pas si une obligation existe déjà. En Allemagne, le § 18 MStV peut exiger le nom et l’adresse des télémédias qui ne servent pas exclusivement à des fins personnelles ou familiales ; le § 5 DDG peut ajouter d’autres obligations.', loading: 'Chargement des informations ...', loadError: 'Les informations n’ont pas pu être chargées.', saveError: 'Les informations n’ont pas pu être enregistrées.', saved: 'Informations enregistrées.', publish: 'Publier les mentions légales', publishHint: 'Publier uniquement après vérification des champs obligatoires et des sections facultatives applicables.', editorialHint: 'Compléter cette section uniquement si un responsable des contenus journalistiques et éditoriaux doit être nommé.', disputeHint: 'Ne pas reprendre d’ancien texte européen de règlement des litiges. Ajouter uniquement une déclaration vérifiée et applicable.', save: 'Enregistrer', saving: 'Enregistrement ...', reload: 'Annuler les changements locaux', preview: 'Ouvrir la page publique', resetEnvironment: 'Restaurer les valeurs .env', resetConfirm: 'Remplacer toutes les modifications administrateur par les valeurs .env actuelles ?', resetSuccess: 'Valeurs d’environnement restaurées.', resetError: 'Les valeurs d’environnement n’ont pas pu être restaurées.', updatedBy: 'Dernière modification par {user} le {date}.', sources: { environment: 'Valeurs .env', admin: 'Valeurs administrateur' } },
      sections: { provider: 'Fournisseur et adresse', contact: 'Contact', register: 'Informations du registre', tax: 'Informations fiscales', supervision: 'Autorité de contrôle', editorial: 'Responsabilité éditoriale', dispute: 'Règlement des litiges de consommation', additional: 'Informations supplémentaires' },
      fields: { providerName: 'Nom / organisation', legalForm: 'Forme juridique', representedBy: 'Représenté par', street: 'Rue et numéro', postalCode: 'Code postal', city: 'Ville', country: 'Pays', email: 'E-mail', phone: 'Téléphone', registerName: 'Registre', registerCourt: 'Tribunal du registre', registerNumber: 'Numéro de registre', vatId: 'Numéro de TVA', businessId: 'Numéro d’identification économique', supervisoryAuthority: 'Autorité de contrôle compétente', editorialName: 'Personne responsable', disputeResolution: 'Déclaration de règlement des litiges', additionalInformation: 'Informations supplémentaires sur le fournisseur' },
    },
  },
  es: {
    legalNotice: {
      public: { eyebrow: 'Información del proveedor', title: 'Aviso legal', subtitle: 'Información sobre la persona u organización responsable de este sitio web.', footerLink: 'Aviso legal', loading: 'Cargando el aviso legal ...', loadError: 'No se pudo cargar el aviso legal.', retry: 'Reintentar', draftTitle: 'Aviso legal en preparación', draftText: 'La información del proveedor se mantiene actualmente como borrador y aún no se ha publicado.', draftLegalHint: 'Este es un estado técnico de publicación y no una afirmación sobre la aplicación de obligaciones legales.', updated: 'Última actualización: {date}' },
      admin: { eyebrow: 'Administración', title: 'Aviso legal', navigation: 'Aviso legal', subtitle: 'Preparar la información del proveedor desde las variables de entorno y publicarla tras su revisión.', configurationTitle: 'Información del proveedor', configurationHint: 'Los valores de .env inicializan este documento. Los cambios de administrador se guardan en la base de datos y sobreviven a las actualizaciones.', legalWarningTitle: 'Se requiere revisión jurídica', legalWarningText: 'Este formulario ayuda a preparar la información, pero no determina si ya existe una obligación. En Alemania, el § 18 MStV puede exigir nombre y dirección para telemedios que no sirvan exclusivamente a fines personales o familiares; el § 5 DDG puede añadir más obligaciones.', loading: 'Cargando información ...', loadError: 'No se pudo cargar la información.', saveError: 'No se pudo guardar la información.', saved: 'Información guardada.', publish: 'Publicar el aviso legal', publishHint: 'Publicar solo después de revisar los campos obligatorios y todas las secciones opcionales aplicables.', editorialHint: 'Completa esta sección solo si debe nombrarse a una persona responsable del contenido periodístico-editorial.', disputeHint: 'No copies textos obsoletos de resolución de litigios de la UE. Añade solo una declaración revisada y aplicable.', save: 'Guardar', saving: 'Guardando ...', reload: 'Descartar cambios locales', preview: 'Abrir página pública', resetEnvironment: 'Restaurar valores .env', resetConfirm: '¿Sustituir todos los cambios de administrador por los valores .env actuales?', resetSuccess: 'Valores de entorno restaurados.', resetError: 'No se pudieron restaurar los valores de entorno.', updatedBy: 'Último cambio por {user} el {date}.', sources: { environment: 'Valores .env', admin: 'Valores de administrador' } },
      sections: { provider: 'Proveedor y dirección', contact: 'Contacto', register: 'Datos registrales', tax: 'Datos fiscales', supervision: 'Autoridad supervisora', editorial: 'Responsabilidad editorial', dispute: 'Resolución de litigios de consumo', additional: 'Información adicional' },
      fields: { providerName: 'Nombre / organización', legalForm: 'Forma jurídica', representedBy: 'Representado por', street: 'Calle y número', postalCode: 'Código postal', city: 'Ciudad', country: 'País', email: 'Correo electrónico', phone: 'Teléfono', registerName: 'Registro', registerCourt: 'Tribunal registral', registerNumber: 'Número de registro', vatId: 'Número de identificación de IVA', businessId: 'Número de identificación empresarial', supervisoryAuthority: 'Autoridad supervisora competente', editorialName: 'Persona responsable', disputeResolution: 'Declaración de resolución de litigios', additionalInformation: 'Información adicional del proveedor' },
    },
  },
  pt: {
    legalNotice: {
      public: { eyebrow: 'Informações do fornecedor', title: 'Aviso legal', subtitle: 'Informações sobre a pessoa ou organização responsável por este site.', footerLink: 'Aviso legal', loading: 'A carregar o aviso legal ...', loadError: 'Não foi possível carregar o aviso legal.', retry: 'Tentar novamente', draftTitle: 'Aviso legal em preparação', draftText: 'As informações do fornecedor estão atualmente guardadas como rascunho e ainda não foram publicadas.', draftLegalHint: 'Este é um estado técnico de publicação, não uma declaração sobre a aplicação de obrigações legais.', updated: 'Última atualização: {date}' },
      admin: { eyebrow: 'Administração', title: 'Aviso legal', navigation: 'Aviso legal', subtitle: 'Preparar as informações do fornecedor a partir dos valores de ambiente e publicá-las após revisão.', configurationTitle: 'Informações do fornecedor', configurationHint: 'Os valores .env inicializam este documento. As alterações do administrador são guardadas na base de dados e sobrevivem às atualizações.', legalWarningTitle: 'Revisão jurídica necessária', legalWarningText: 'Este formulário ajuda na preparação, mas não determina se já existe uma obrigação. Na Alemanha, o § 18 MStV pode exigir nome e morada para telemédia que não sirvam exclusivamente fins pessoais ou familiares; o § 5 DDG pode acrescentar outras obrigações.', loading: 'A carregar informações ...', loadError: 'Não foi possível carregar as informações.', saveError: 'Não foi possível guardar as informações.', saved: 'Informações guardadas.', publish: 'Publicar o aviso legal', publishHint: 'Publicar apenas depois de rever os campos obrigatórios e todas as secções opcionais aplicáveis.', editorialHint: 'Preencha esta secção apenas se tiver de ser indicada uma pessoa responsável por conteúdo jornalístico-editorial.', disputeHint: 'Não copie textos europeus desatualizados de resolução de litígios. Adicione apenas uma declaração revista e aplicável.', save: 'Guardar', saving: 'A guardar ...', reload: 'Descartar alterações locais', preview: 'Abrir página pública', resetEnvironment: 'Restaurar valores .env', resetConfirm: 'Substituir todas as alterações do administrador pelos valores .env atuais?', resetSuccess: 'Valores de ambiente restaurados.', resetError: 'Não foi possível restaurar os valores de ambiente.', updatedBy: 'Última alteração por {user} em {date}.', sources: { environment: 'Valores .env', admin: 'Valores do administrador' } },
      sections: { provider: 'Fornecedor e morada', contact: 'Contacto', register: 'Informações de registo', tax: 'Informações fiscais', supervision: 'Autoridade supervisora', editorial: 'Responsabilidade editorial', dispute: 'Resolução de litígios de consumo', additional: 'Informações adicionais' },
      fields: { providerName: 'Nome / organização', legalForm: 'Forma jurídica', representedBy: 'Representado por', street: 'Rua e número', postalCode: 'Código postal', city: 'Cidade', country: 'País', email: 'E-mail', phone: 'Telefone', registerName: 'Registo', registerCourt: 'Tribunal de registo', registerNumber: 'Número de registo', vatId: 'Número de identificação de IVA', businessId: 'Número de identificação empresarial', supervisoryAuthority: 'Autoridade supervisora competente', editorialName: 'Pessoa responsável', disputeResolution: 'Declaração de resolução de litígios', additionalInformation: 'Informações adicionais do fornecedor' },
    },
  },
  ru: {
    legalNotice: {
      public: { eyebrow: 'Сведения о владельце', title: 'Правовая информация', subtitle: 'Сведения о лице или организации, ответственных за этот сайт.', footerLink: 'Правовая информация', loading: 'Загрузка правовой информации ...', loadError: 'Не удалось загрузить правовую информацию.', retry: 'Повторить', draftTitle: 'Правовая информация готовится', draftText: 'Сведения о владельце пока сохранены как черновик и ещё не опубликованы.', draftLegalHint: 'Это технический статус публикации, а не заявление о наличии или отсутствии законодательных обязанностей.', updated: 'Последнее обновление: {date}' },
      admin: { eyebrow: 'Администрирование', title: 'Правовая информация', navigation: 'Правовая информация', subtitle: 'Подготовьте сведения из переменных окружения и опубликуйте их после проверки.', configurationTitle: 'Сведения о владельце', configurationHint: 'Значения .env создают исходный документ. Изменения администратора хранятся в базе данных и сохраняются после обновлений.', legalWarningTitle: 'Требуется юридическая проверка', legalWarningText: 'Форма помогает подготовить сведения, но не определяет, возникла ли обязанность. В Германии § 18 MStV может требовать имя и адрес для телемедиа, не предназначенных исключительно для личных или семейных целей; § 5 DDG может добавлять другие требования.', loading: 'Загрузка сведений ...', loadError: 'Не удалось загрузить сведения.', saveError: 'Не удалось сохранить сведения.', saved: 'Сведения сохранены.', publish: 'Опубликовать правовую информацию', publishHint: 'Публикуйте только после проверки обязательных полей и всех применимых дополнительных разделов.', editorialHint: 'Заполняйте этот раздел только тогда, когда требуется назвать ответственного за журналистско-редакционный контент.', disputeHint: 'Не копируйте устаревший текст ЕС об урегулировании споров. Добавляйте только проверенное и применимое заявление.', save: 'Сохранить', saving: 'Сохранение ...', reload: 'Отменить локальные изменения', preview: 'Открыть публичную страницу', resetEnvironment: 'Восстановить значения .env', resetConfirm: 'Заменить все изменения администратора текущими значениями .env?', resetSuccess: 'Значения окружения восстановлены.', resetError: 'Не удалось восстановить значения окружения.', updatedBy: 'Последнее изменение: {user}, {date}.', sources: { environment: 'Значения .env', admin: 'Значения администратора' } },
      sections: { provider: 'Владелец и адрес', contact: 'Контакты', register: 'Регистрационные сведения', tax: 'Налоговые сведения', supervision: 'Надзорный орган', editorial: 'Редакционная ответственность', dispute: 'Урегулирование потребительских споров', additional: 'Дополнительные сведения' },
      fields: { providerName: 'Имя / организация', legalForm: 'Организационно-правовая форма', representedBy: 'Представитель', street: 'Улица и номер дома', postalCode: 'Почтовый индекс', city: 'Город', country: 'Страна', email: 'Электронная почта', phone: 'Телефон', registerName: 'Реестр', registerCourt: 'Регистрирующий суд', registerNumber: 'Регистрационный номер', vatId: 'Идентификационный номер НДС', businessId: 'Идентификационный номер предприятия', supervisoryAuthority: 'Компетентный надзорный орган', editorialName: 'Ответственное лицо', disputeResolution: 'Заявление об урегулировании споров', additionalInformation: 'Дополнительные сведения о владельце' },
    },
  },
  cn: {
    legalNotice: {
      public: { eyebrow: '服务提供者信息', title: '法律声明', subtitle: '关于负责本网站的个人或组织的信息。', footerLink: '法律声明', loading: '正在加载法律声明……', loadError: '无法加载法律声明。', retry: '重试', draftTitle: '法律声明准备中', draftText: '服务提供者信息目前作为草稿保存，尚未发布。', draftLegalHint: '这只是技术上的发布状态，并不表示法定义务是否适用。', updated: '最后更新：{date}' },
      admin: { eyebrow: '管理', title: '法律声明', navigation: '法律声明', subtitle: '根据环境变量准备服务提供者信息，并在审核后发布。', configurationTitle: '服务提供者信息', configurationHint: '.env 值用于初始化文档。管理员更改保存在数据库中，应用更新不会覆盖。', legalWarningTitle: '需要法律审核', legalWarningText: '此表单仅协助准备信息，不能判断义务是否已经产生。在德国，非纯粹个人或家庭用途的在线媒体可能需要根据 MStV 第18条提供姓名和地址；适用时，DDG 第5条可能要求更多信息。', loading: '正在加载信息……', loadError: '无法加载信息。', saveError: '无法保存信息。', saved: '信息已保存。', publish: '发布法律声明', publishHint: '仅在必填字段和所有适用的可选部分均已审核后发布。', editorialHint: '仅在必须指定新闻编辑内容负责人时填写此部分。', disputeHint: '请勿复制已过时的欧盟争议解决文字，仅添加经过审核且适用的声明。', save: '保存', saving: '正在保存……', reload: '放弃本地更改', preview: '打开公开页面', resetEnvironment: '恢复 .env 值', resetConfirm: '是否用当前 .env 值替换所有管理员更改？', resetSuccess: '环境变量值已恢复。', resetError: '无法恢复环境变量值。', updatedBy: '最后由 {user} 于 {date} 修改。', sources: { environment: '.env 默认值', admin: '管理员值' } },
      sections: { provider: '提供者和地址', contact: '联系方式', register: '注册信息', tax: '税务信息', supervision: '监管机构', editorial: '编辑责任', dispute: '消费者争议解决', additional: '其他信息' },
      fields: { providerName: '姓名 / 组织', legalForm: '法律形式', representedBy: '代表人', street: '街道和门牌号', postalCode: '邮政编码', city: '城市', country: '国家', email: '电子邮件', phone: '电话', registerName: '登记册', registerCourt: '登记法院', registerNumber: '注册编号', vatId: '增值税识别号', businessId: '企业识别号', supervisoryAuthority: '主管监管机构', editorialName: '负责人', disputeResolution: '争议解决声明', additionalInformation: '其他提供者信息' },
    },
  },
}
