export const masterDataMessages = {
  en: {
    masterData: {
      mortarModification: { title: 'Mortar Modification', available: 'This ship supports the permanent conversion', hint: 'This is a permanent ship conversion, not an upgrade-slot item. Enter all added mortar capacity and exchanged ship values explicitly.', mortarCapacity: 'Added mortar slots', broadsideDelta: 'Gun positions per broadside', durabilityDelta: 'Durability change', speedPercent: 'Speed change (%)', maneuverabilityDelta: 'Maneuverability change', holdPercent: 'Hold change (%)', crewDelta: 'Crew-capacity change' },
      eyebrow: 'Administration', title: 'Master data', subtitle: 'Maintain Build Designer catalogs, ship values, weapon mounts and image references without losing changes during future seed runs.', back: 'Back to staff panel', loading: 'Loading master data ...', loadError: 'Master data could not be loaded.', saveError: 'The record could not be saved.', saved: 'Master data saved.', new: 'New record', restore: 'Restore seed default', deactivate: 'Deactivate', allCategories: 'All categories', customRecord: 'Custom record', effectsHint: 'JSON object, for example {"speed_pct": 5, "crew_capacity": 10}.', effectsError: 'Stat effects must be a JSON object.',
      tabs: { options: 'Equipment options', ships: 'Ships', categories: 'Categories' },
      metrics: { categories: 'Categories', options: 'Options', ships: 'Ships', overrides: 'Admin overrides', inactive: 'Inactive' },
      seedStatus: { seeded: 'Seed default', overridden: 'Admin override', custom: 'Custom' },
      categories: { title: 'Build categories', edit: 'Edit category', create: 'Create category' },
      options: { title: 'Catalog options', edit: 'Edit option', create: 'Create option' },
      ships: { title: 'Ship catalog', edit: 'Edit ship', create: 'Create ship' },
      shipUpgradeOverrides: { title: 'Ship-specific upgrade values', hint: 'Store only the effect keys that differ for this ship. Unlisted keys continue to inherit the global upgrade values.', upgrade: 'Upgrade', defaultEffects: 'Global default effects', overrideEffects: 'Ship override (JSON)', add: 'Add ship override', remove: 'Remove', empty: 'This ship currently uses the global value of every upgrade.' },
      fields: { key: 'Key', label: 'Label', sortOrder: 'Sort order', active: 'Active', category: 'Category', name: 'Name', kind: 'Option type', source: 'Source / revision', notes: 'Notes', imageUrl: 'Image URL', weaponClass: 'Weapon class', caliber: 'Maximum caliber (in)', allowedSlots: 'Allowed weapon slots', effects: 'Stat effects', type: 'Ship type', sailSlots: 'Sail slots', upgradeSlots: 'Upgrade slots', durability: 'Durability', speed: 'Speed (kn)', baseSpeed: 'Base speed (kn)', cruiseMaxSpeed: 'Cruise max. speed (kn)', maneuverability: 'Maneuverability', armor: 'Armor', holdCapacity: 'Hold capacity', displacement: 'Displacement (t)', crewCapacity: 'Crew capacity', sailorMinimum: 'Minimum sailors', weaponMounts: 'Weapon mounts', capacity: 'Capacity', specialWeaponCapacity: 'Special-weapon capacity', lantern: 'Lantern available' },
    },
  },
  de: {
    masterData: {
      mortarModification: { title: 'Mörser-Modifikation', available: 'Dieses Schiff unterstützt den dauerhaften Umbau', hint: 'Dies ist ein dauerhafter Schiffumbau und kein Upgrade-Slot. Zusätzliche Mörserplätze und eingetauschte Schiffswerte vollständig eintragen.', mortarCapacity: 'Zusätzliche Mörserplätze', broadsideDelta: 'Kanonenplätze je Breitseite', durabilityDelta: 'Änderung Haltbarkeit', speedPercent: 'Änderung Geschwindigkeit (%)', maneuverabilityDelta: 'Änderung Manövrierbarkeit', holdPercent: 'Änderung Laderaum (%)', crewDelta: 'Änderung Besatzungskapazität' },
      eyebrow: 'Administration', title: 'Stammdatenverwaltung', subtitle: 'Build-Designer-Kataloge, Schiffswerte, Waffen-Mounts und Bildreferenzen bearbeiten, ohne Änderungen bei späteren Seed-Läufen zu verlieren.', back: 'Zurück zum Team-Panel', loading: 'Stammdaten werden geladen ...', loadError: 'Stammdaten konnten nicht geladen werden.', saveError: 'Der Datensatz konnte nicht gespeichert werden.', saved: 'Stammdaten gespeichert.', new: 'Neuer Datensatz', restore: 'Seed-Standard wiederherstellen', deactivate: 'Deaktivieren', allCategories: 'Alle Kategorien', customRecord: 'Eigener Datensatz', effectsHint: 'JSON-Objekt, zum Beispiel {"speed_pct": 5, "crew_capacity": 10}.', effectsError: 'Statuseffekte müssen ein JSON-Objekt sein.',
      tabs: { options: 'Ausrüstungsoptionen', ships: 'Schiffe', categories: 'Kategorien' },
      metrics: { categories: 'Kategorien', options: 'Optionen', ships: 'Schiffe', overrides: 'Admin-Overrides', inactive: 'Inaktiv' },
      seedStatus: { seeded: 'Seed-Standard', overridden: 'Admin-Override', custom: 'Eigener Eintrag' },
      categories: { title: 'Build-Kategorien', edit: 'Kategorie bearbeiten', create: 'Kategorie anlegen' },
      options: { title: 'Katalogoptionen', edit: 'Option bearbeiten', create: 'Option anlegen' },
      ships: { title: 'Schiffskatalog', edit: 'Schiff bearbeiten', create: 'Schiff anlegen' },
      shipUpgradeOverrides: { title: 'Schiffsspezifische Upgrade-Werte', hint: 'Nur abweichende Effektwerte hinterlegen. Nicht aufgeführte Schlüssel übernehmen weiterhin den globalen Upgrade-Wert.', upgrade: 'Verbesserung', defaultEffects: 'Globale Standardwerte', overrideEffects: 'Schiffs-Override (JSON)', add: 'Schiffs-Override hinzufügen', remove: 'Entfernen', empty: 'Dieses Schiff verwendet aktuell bei allen Upgrades die globalen Werte.' },
      fields: { key: 'Schlüssel', label: 'Bezeichnung', sortOrder: 'Sortierung', active: 'Aktiv', category: 'Kategorie', name: 'Bezeichnung', kind: 'Optionstyp', source: 'Quelle / Revision', notes: 'Notizen', imageUrl: 'Bild-URL', weaponClass: 'Waffenklasse', caliber: 'Maximales Kaliber (Zoll)', allowedSlots: 'Erlaubte Waffenplätze', effects: 'Statuseffekte', type: 'Schiffstyp', sailSlots: 'Segelplätze', upgradeSlots: 'Upgrade-Plätze', durability: 'Haltbarkeit', speed: 'Geschwindigkeit (kn)', baseSpeed: 'Basisgeschwindigkeit (kn)', cruiseMaxSpeed: 'Maximale Reisegeschwindigkeit (kn)', maneuverability: 'Manövrierbarkeit', armor: 'Panzerung', holdCapacity: 'Laderaumkapazität', displacement: 'Verdrängung (t)', crewCapacity: 'Besatzungskapazität', sailorMinimum: 'Mindestanzahl Matrosen', weaponMounts: 'Waffen-Mounts', capacity: 'Kapazität', specialWeaponCapacity: 'Kapazität für Spezialwaffen', lantern: 'Laterne verfügbar' },
    },
  },
  fr: {
    masterData: {
      mortarModification: { title: 'Modification mortier', available: 'Ce navire accepte la conversion permanente', hint: 'Il s’agit d’une conversion permanente du navire, pas d’un emplacement d’amélioration. Saisissez explicitement les mortiers ajoutés et les valeurs échangées.', mortarCapacity: 'Emplacements de mortier ajoutés', broadsideDelta: 'Canons par bordée', durabilityDelta: 'Variation de durabilité', speedPercent: 'Variation de vitesse (%)', maneuverabilityDelta: 'Variation de maniabilité', holdPercent: 'Variation de cale (%)', crewDelta: 'Variation de capacité d’équipage' },
      eyebrow: 'Administration', title: 'Données de référence', subtitle: 'Gérez les catalogues du concepteur, les valeurs des navires, les montures d’armes et les images sans perdre les modifications lors des prochains seeds.', back: 'Retour au panneau du staff', loading: 'Chargement des données de référence ...', loadError: 'Impossible de charger les données de référence.', saveError: 'Impossible d’enregistrer la fiche.', saved: 'Données de référence enregistrées.', new: 'Nouvelle fiche', restore: 'Restaurer le seed', deactivate: 'Désactiver', allCategories: 'Toutes les catégories', customRecord: 'Fiche personnalisée', effectsHint: 'Objet JSON, par exemple {"speed_pct": 5, "crew_capacity": 10}.', effectsError: 'Les effets doivent être un objet JSON.',
      tabs: { options: 'Options d’équipement', ships: 'Navires', categories: 'Catégories' }, metrics: { categories: 'Catégories', options: 'Choix', ships: 'Navires', overrides: 'Modifications admin', inactive: 'Inactifs' }, seedStatus: { seeded: 'Valeur du seed', overridden: 'Modification admin', custom: 'Personnalisé' }, categories: { title: 'Catégories de builds', edit: 'Modifier la catégorie', create: 'Créer une catégorie' }, options: { title: 'Options du catalogue', edit: 'Modifier l’option', create: 'Créer une option' }, ships: { title: 'Catalogue des navires', edit: 'Modifier le navire', create: 'Créer un navire' },
      shipUpgradeOverrides: { title: 'Valeurs d’amélioration par navire', hint: 'Enregistrez uniquement les effets différents pour ce navire. Les autres valeurs restent héritées du catalogue global.', upgrade: 'Amélioration', defaultEffects: 'Valeurs globales', overrideEffects: 'Valeurs du navire (JSON)', add: 'Ajouter une valeur', remove: 'Supprimer', empty: 'Ce navire utilise les valeurs globales pour toutes les améliorations.' },
      fields: { key: 'Clé', label: 'Libellé', sortOrder: 'Ordre', active: 'Actif', category: 'Catégorie', name: 'Nom', kind: 'Type d’option', source: 'Source / révision', notes: 'Notes', imageUrl: 'URL de l’image', weaponClass: 'Classe d’arme', caliber: 'Calibre maximal (po)', allowedSlots: 'Emplacements autorisés', effects: 'Effets de statistiques', type: 'Type de navire', sailSlots: 'Emplacements de voiles', upgradeSlots: 'Emplacements d’amélioration', durability: 'Durabilité', speed: 'Vitesse (nd)', baseSpeed: 'Vitesse de base (nd)', cruiseMaxSpeed: 'Vitesse de croisière maximale (nd)', maneuverability: 'Maniabilité', armor: 'Armure', holdCapacity: 'Capacité de cale', displacement: 'Déplacement (t)', crewCapacity: 'Capacité d’équipage', sailorMinimum: 'Marins minimum', weaponMounts: 'Montures d’armes', capacity: 'Capacité', specialWeaponCapacity: 'Capacité d’armes spéciales', lantern: 'Lanterne disponible' },
    },
  },
  es: {
    masterData: {
      mortarModification: { title: 'Modificación de mortero', available: 'Este barco admite la conversión permanente', hint: 'Es una conversión permanente del barco, no una ranura de mejora. Introduce explícitamente los morteros añadidos y los valores intercambiados.', mortarCapacity: 'Ranuras de mortero añadidas', broadsideDelta: 'Cañones por banda', durabilityDelta: 'Cambio de durabilidad', speedPercent: 'Cambio de velocidad (%)', maneuverabilityDelta: 'Cambio de maniobrabilidad', holdPercent: 'Cambio de bodega (%)', crewDelta: 'Cambio de capacidad de tripulación' },
      eyebrow: 'Administración', title: 'Datos maestros', subtitle: 'Gestiona catálogos del diseñador, valores de barcos, montajes de armas e imágenes sin perder cambios en futuros seeds.', back: 'Volver al panel del equipo', loading: 'Cargando datos maestros ...', loadError: 'No se pudieron cargar los datos maestros.', saveError: 'No se pudo guardar el registro.', saved: 'Datos maestros guardados.', new: 'Nuevo registro', restore: 'Restaurar seed', deactivate: 'Desactivar', allCategories: 'Todas las categorías', customRecord: 'Registro personalizado', effectsHint: 'Objeto JSON, por ejemplo {"speed_pct": 5, "crew_capacity": 10}.', effectsError: 'Los efectos deben ser un objeto JSON.',
      tabs: { options: 'Opciones de equipo', ships: 'Barcos', categories: 'Categorías' }, metrics: { categories: 'Categorías', options: 'Opciones', ships: 'Barcos', overrides: 'Cambios de admin', inactive: 'Inactivos' }, seedStatus: { seeded: 'Valor del seed', overridden: 'Cambio de admin', custom: 'Personalizado' }, categories: { title: 'Categorías de builds', edit: 'Editar categoría', create: 'Crear categoría' }, options: { title: 'Opciones del catálogo', edit: 'Editar opción', create: 'Crear opción' }, ships: { title: 'Catálogo de barcos', edit: 'Editar barco', create: 'Crear barco' },
      shipUpgradeOverrides: { title: 'Valores de mejora por barco', hint: 'Guarda solo los efectos distintos para este barco. Los demás valores se heredan del catálogo global.', upgrade: 'Mejora', defaultEffects: 'Valores globales', overrideEffects: 'Valores del barco (JSON)', add: 'Añadir valor', remove: 'Eliminar', empty: 'Este barco usa los valores globales de todas las mejoras.' },
      fields: { key: 'Clave', label: 'Etiqueta', sortOrder: 'Orden', active: 'Activo', category: 'Categoría', name: 'Nombre', kind: 'Tipo de opción', source: 'Fuente / revisión', notes: 'Notas', imageUrl: 'URL de imagen', weaponClass: 'Clase de arma', caliber: 'Calibre máximo (in)', allowedSlots: 'Ranuras permitidas', effects: 'Efectos de estadísticas', type: 'Tipo de barco', sailSlots: 'Ranuras de velas', upgradeSlots: 'Ranuras de mejora', durability: 'Durabilidad', speed: 'Velocidad (kn)', baseSpeed: 'Velocidad base (kn)', cruiseMaxSpeed: 'Velocidad máxima de crucero (kn)', maneuverability: 'Maniobrabilidad', armor: 'Blindaje', holdCapacity: 'Capacidad de bodega', displacement: 'Desplazamiento (t)', crewCapacity: 'Capacidad de tripulación', sailorMinimum: 'Marineros mínimos', weaponMounts: 'Montajes de armas', capacity: 'Capacidad', specialWeaponCapacity: 'Capacidad de armas especiales', lantern: 'Linterna disponible' },
    },
  },
  pt: {
    masterData: {
      mortarModification: { title: 'Modificação de morteiro', available: 'Este navio aceita a conversão permanente', hint: 'É uma conversão permanente do navio, não um espaço de melhoria. Introduza explicitamente os morteiros adicionados e os valores trocados.', mortarCapacity: 'Espaços de morteiro adicionados', broadsideDelta: 'Canhões por bordo', durabilityDelta: 'Alteração de durabilidade', speedPercent: 'Alteração de velocidade (%)', maneuverabilityDelta: 'Alteração de manobrabilidade', holdPercent: 'Alteração do porão (%)', crewDelta: 'Alteração da capacidade da tripulação' },
      eyebrow: 'Administração', title: 'Dados mestre', subtitle: 'Gira catálogos do designer, valores de navios, montagens de armas e imagens sem perder alterações em futuros seeds.', back: 'Voltar ao painel da equipa', loading: 'A carregar dados mestre ...', loadError: 'Não foi possível carregar os dados mestre.', saveError: 'Não foi possível guardar o registo.', saved: 'Dados mestre guardados.', new: 'Novo registo', restore: 'Restaurar seed', deactivate: 'Desativar', allCategories: 'Todas as categorias', customRecord: 'Registo personalizado', effectsHint: 'Objeto JSON, por exemplo {"speed_pct": 5, "crew_capacity": 10}.', effectsError: 'Os efeitos devem ser um objeto JSON.',
      tabs: { options: 'Opções de equipamento', ships: 'Navios', categories: 'Categorias' }, metrics: { categories: 'Categorias', options: 'Opções', ships: 'Navios', overrides: 'Alterações de admin', inactive: 'Inativos' }, seedStatus: { seeded: 'Valor do seed', overridden: 'Alteração de admin', custom: 'Personalizado' }, categories: { title: 'Categorias de builds', edit: 'Editar categoria', create: 'Criar categoria' }, options: { title: 'Opções do catálogo', edit: 'Editar opção', create: 'Criar opção' }, ships: { title: 'Catálogo de navios', edit: 'Editar navio', create: 'Criar navio' },
      shipUpgradeOverrides: { title: 'Valores de melhoria por navio', hint: 'Guarde apenas os efeitos diferentes neste navio. Os restantes valores continuam a herdar o catálogo global.', upgrade: 'Melhoria', defaultEffects: 'Valores globais', overrideEffects: 'Valores do navio (JSON)', add: 'Adicionar valor', remove: 'Remover', empty: 'Este navio usa os valores globais de todas as melhorias.' },
      fields: { key: 'Chave', label: 'Etiqueta', sortOrder: 'Ordem', active: 'Ativo', category: 'Categoria', name: 'Nome', kind: 'Tipo de opção', source: 'Fonte / revisão', notes: 'Notas', imageUrl: 'URL da imagem', weaponClass: 'Classe de arma', caliber: 'Calibre máximo (pol)', allowedSlots: 'Espaços permitidos', effects: 'Efeitos de atributos', type: 'Tipo de navio', sailSlots: 'Espaços de velas', upgradeSlots: 'Espaços de melhoria', durability: 'Durabilidade', speed: 'Velocidade (kn)', baseSpeed: 'Velocidade base (kn)', cruiseMaxSpeed: 'Velocidade máxima de cruzeiro (kn)', maneuverability: 'Manobrabilidade', armor: 'Armadura', holdCapacity: 'Capacidade do porão', displacement: 'Deslocamento (t)', crewCapacity: 'Capacidade da tripulação', sailorMinimum: 'Marinheiros mínimos', weaponMounts: 'Montagens de armas', capacity: 'Capacidade', specialWeaponCapacity: 'Capacidade de armas especiais', lantern: 'Lanterna disponível' },
    },
  },
  ru: {
    masterData: {
      mortarModification: { title: 'Миномётная модификация', available: 'Корабль поддерживает постоянную переделку', hint: 'Это постоянная переделка корабля, а не слот улучшения. Укажите добавленные миномёты и все изменяемые параметры.', mortarCapacity: 'Добавленные миномётные слоты', broadsideDelta: 'Орудия на каждом борту', durabilityDelta: 'Изменение прочности', speedPercent: 'Изменение скорости (%)', maneuverabilityDelta: 'Изменение манёвренности', holdPercent: 'Изменение трюма (%)', crewDelta: 'Изменение вместимости экипажа' },
      eyebrow: 'Администрирование', title: 'Справочные данные', subtitle: 'Управляйте каталогами конструктора, параметрами кораблей, орудийными слотами и изображениями без потери правок при следующих seed-запусках.', back: 'Назад в панель персонала', loading: 'Загрузка справочных данных ...', loadError: 'Не удалось загрузить справочные данные.', saveError: 'Не удалось сохранить запись.', saved: 'Справочные данные сохранены.', new: 'Новая запись', restore: 'Восстановить seed', deactivate: 'Деактивировать', allCategories: 'Все категории', customRecord: 'Пользовательская запись', effectsHint: 'Объект JSON, например {"speed_pct": 5, "crew_capacity": 10}.', effectsError: 'Эффекты должны быть объектом JSON.',
      tabs: { options: 'Варианты оснащения', ships: 'Корабли', categories: 'Категории' }, metrics: { categories: 'Категории', options: 'Варианты', ships: 'Корабли', overrides: 'Правки администратора', inactive: 'Неактивные' }, seedStatus: { seeded: 'Значение seed', overridden: 'Правка администратора', custom: 'Пользовательское' }, categories: { title: 'Категории билдов', edit: 'Изменить категорию', create: 'Создать категорию' }, options: { title: 'Варианты каталога', edit: 'Изменить вариант', create: 'Создать вариант' }, ships: { title: 'Каталог кораблей', edit: 'Изменить корабль', create: 'Создать корабль' },
      shipUpgradeOverrides: { title: 'Значения улучшений для корабля', hint: 'Сохраняйте только отличающиеся эффекты. Остальные значения наследуются из общего каталога.', upgrade: 'Улучшение', defaultEffects: 'Общие значения', overrideEffects: 'Значения корабля (JSON)', add: 'Добавить значение', remove: 'Удалить', empty: 'Для этого корабля используются общие значения всех улучшений.' },
      fields: { key: 'Ключ', label: 'Название', sortOrder: 'Порядок', active: 'Активно', category: 'Категория', name: 'Имя', kind: 'Тип варианта', source: 'Источник / ревизия', notes: 'Примечания', imageUrl: 'URL изображения', weaponClass: 'Класс оружия', caliber: 'Макс. калибр (дюйм)', allowedSlots: 'Разрешённые слоты', effects: 'Эффекты параметров', type: 'Тип корабля', sailSlots: 'Слоты парусов', upgradeSlots: 'Слоты улучшений', durability: 'Прочность', speed: 'Скорость (уз)', baseSpeed: 'Базовая скорость (уз)', cruiseMaxSpeed: 'Максимальная крейсерская скорость (уз)', maneuverability: 'Манёвренность', armor: 'Броня', holdCapacity: 'Вместимость трюма', displacement: 'Водоизмещение (т)', crewCapacity: 'Вместимость экипажа', sailorMinimum: 'Минимум матросов', weaponMounts: 'Орудийные слоты', capacity: 'Вместимость', specialWeaponCapacity: 'Вместимость спецоружия', lantern: 'Фонарь доступен' },
    },
  },
  cn: {
    masterData: {
      mortarModification: { title: '迫击炮改装', available: '该舰船支持永久改装', hint: '这是永久舰船改装，不占升级槽。请明确填写新增迫击炮槽及交换的所有舰船属性。', mortarCapacity: '新增迫击炮槽', broadsideDelta: '每侧舷炮变化', durabilityDelta: '耐久变化', speedPercent: '速度变化（%）', maneuverabilityDelta: '机动性变化', holdPercent: '货舱变化（%）', crewDelta: '船员容量变化' },
      eyebrow: '管理', title: '主数据管理', subtitle: '维护配装设计器目录、舰船数值、武器挂点和图片引用，并避免后续种子运行覆盖管理员修改。', back: '返回管理面板', loading: '正在加载主数据 ...', loadError: '无法加载主数据。', saveError: '无法保存记录。', saved: '主数据已保存。', new: '新建记录', restore: '恢复种子默认值', deactivate: '停用', allCategories: '全部分类', customRecord: '自定义记录', effectsHint: 'JSON 对象，例如 {"speed_pct": 5, "crew_capacity": 10}。', effectsError: '属性效果必须是 JSON 对象。',
      tabs: { options: '装备选项', ships: '舰船', categories: '分类' }, metrics: { categories: '分类', options: '选项', ships: '舰船', overrides: '管理员覆盖', inactive: '已停用' }, seedStatus: { seeded: '种子默认值', overridden: '管理员覆盖', custom: '自定义' }, categories: { title: '配装分类', edit: '编辑分类', create: '新建分类' }, options: { title: '目录选项', edit: '编辑选项', create: '新建选项' }, ships: { title: '舰船目录', edit: '编辑舰船', create: '新建舰船' },
      shipUpgradeOverrides: { title: '舰船专属升级数值', hint: '仅填写该舰船不同的效果值；未填写的项目继续继承全局升级数值。', upgrade: '升级', defaultEffects: '全局默认效果', overrideEffects: '舰船覆盖值（JSON）', add: '添加舰船覆盖值', remove: '移除', empty: '该舰船目前对所有升级均使用全局数值。' },
      fields: { key: '键', label: '标签', sortOrder: '排序', active: '启用', category: '分类', name: '名称', kind: '选项类型', source: '来源 / 修订', notes: '备注', imageUrl: '图片 URL', weaponClass: '武器等级', caliber: '最大口径（英寸）', allowedSlots: '允许的武器槽位', effects: '属性效果', type: '舰船类型', sailSlots: '帆槽位', upgradeSlots: '升级槽位', durability: '耐久', speed: '速度（节）', baseSpeed: '基础速度（节）', cruiseMaxSpeed: '最大巡航速度（节）', maneuverability: '机动性', armor: '装甲', holdCapacity: '货舱容量', displacement: '排水量（吨）', crewCapacity: '船员容量', sailorMinimum: '最低水手数', weaponMounts: '武器挂点', capacity: '容量', specialWeaponCapacity: '特殊武器容量', lantern: '可用灯笼' },
    },
  },
}
