export const newcomerGuideMessages = {
  en: {
    common: { newCaptainGuide: 'New Captain Guide', remove: 'Remove', title: 'Title', description: 'Description' },
    home: { newcomer: {
      guideTitle: 'Follow the New Captain Guide',
      guideText: 'Use the curated roadmap for the most important guides, proven builds, Q&A and your first scheduled operations.',
      guideMeta: 'Curated beginner roadmap',
    } },
    newcomerGuide: {
      eyebrow: 'New captain roadmap', title: 'New Captain Guide', subtitle: 'A curated route from first login to prepared fleet participation.',
      memberOnly: 'Members only', updatedBy: 'Updated by {name}', edit: 'Edit guide', loading: 'Loading the newcomer guide …',
      loadError: 'The newcomer guide could not be loaded.', saveError: 'The newcomer guide could not be saved.', saved: 'Newcomer guide saved.',
      textSection: 'Briefing', resourceSection: 'Recommended route', open: 'Open resource', unavailable: 'Resource unavailable',
      folderNavigation: 'Guide folders', folders: 'Contents', folderCount: '{count} folders', folderPosition: 'Folder {current} of {total}', emptyFolders: 'No folders have been added yet.',
      explorer: { workspace: 'New player knowledge base', home: 'Guide home', allTopics: 'Browse all topics', back: 'Back to all topics', addressLabel: 'Current guide location', topicsHeading: 'Choose a topic to begin', topicsHint: 'Browse the fleet knowledge base like a shared folder. Open a topic for its briefing, guides, builds and next steps.', topicCount: '{count} topics', resourceCount: '{count} resources', text: 'Briefing topic', resources: 'Resource topic', noSummary: 'Open this topic to read its fleet guidance.', openTopic: 'Open topic', topicNavigation: 'Previous and next guide topics', previous: 'Previous topic', next: 'Next topic', resourcesHeading: 'Guides, builds and references', resourcesHint: 'Continue with the curated material attached to this topic.', noResourceDescription: 'Open this resource for more information.', available: 'Available', noResources: 'No resources have been linked to this topic yet.' },
      editor: {
        guideSettings: 'Guide settings', guideIdentity: 'Title and introduction', addFolder: 'Add folder', selectedFolder: 'Folder {index}', orderHint: 'The folder order on the left is also the reading order.', folderActions: 'Actions for {title}', moveUp: 'Move folder up', moveDown: 'Move folder down', removeFolder: 'Remove {title}', folderResources: 'Folder resources', resourceOrderHint: 'Resources appear in this order inside the folder.', emptyResources: 'This folder is empty. Add its first resource above.', noFolderTitle: 'Create the first folder', noFolderText: 'Choose a text folder or resource folder from the left to begin.', saveHint: 'Saving publishes this folder order to members.',
        pageTitle: 'Page title', intro: 'Introduction', block: 'Section {index}', untitled: 'Untitled section', blockType: 'Section type',
        textBlock: 'Text section', resourceBlock: 'Resource collection', text: 'Text', optionalIntro: 'Optional section introduction',
        resource: 'Resource {index}', url: 'Destination URL', customLabel: 'Custom label', customLabelHint: 'Optional — otherwise the resource title is used',
        addResource: 'Add resource', addTextBlock: 'Add text section', addResourceBlock: 'Add resource collection', linkGuide: 'Link guide', linkBuild: 'Link build', loadingResources: 'Loading guides and builds …', resourceLoadError: 'Guides and builds could not be loaded.', noGuides: 'No published guides available', noBuilds: 'No builds available',
        types: { guide: 'Guide', build: 'Build', internal: 'Hub page', external: 'External link' },
      },
    },
  },
  de: {
    common: { newCaptainGuide: 'Einsteiger-Leitfaden', remove: 'Entfernen', title: 'Titel', description: 'Beschreibung' },
    home: { newcomer: {
      guideTitle: 'Dem Einsteiger-Leitfaden folgen',
      guideText: 'Nutze die kuratierte Roadmap für wichtige Guides, erprobte Builds, Q&A und deine ersten geplanten Operationen.',
      guideMeta: 'Kuratierte Anfänger-Roadmap',
    } },
    newcomerGuide: {
      eyebrow: 'Roadmap für neue Kapitäne', title: 'Einsteiger-Leitfaden', subtitle: 'Ein kuratierter Weg vom ersten Login bis zur vorbereiteten Teilnahme an Flottenaktivitäten.',
      memberOnly: 'Nur für Mitglieder', updatedBy: 'Aktualisiert von {name}', edit: 'Leitfaden bearbeiten', loading: 'Einsteiger-Leitfaden wird geladen …',
      loadError: 'Der Einsteiger-Leitfaden konnte nicht geladen werden.', saveError: 'Der Einsteiger-Leitfaden konnte nicht gespeichert werden.', saved: 'Einsteiger-Leitfaden gespeichert.',
      textSection: 'Einsatzbriefing', resourceSection: 'Empfohlener Weg', open: 'Ressource öffnen', unavailable: 'Ressource nicht verfügbar',
      folderNavigation: 'Ordner des Leitfadens', folders: 'Inhalt', folderCount: '{count} Ordner', folderPosition: 'Ordner {current} von {total}', emptyFolders: 'Noch wurden keine Ordner angelegt.',
      explorer: { workspace: 'Wissensbasis für neue Spieler', home: 'Leitfaden-Start', allTopics: 'Alle Themen durchsuchen', back: 'Zurück zu allen Themen', addressLabel: 'Aktueller Ort im Leitfaden', topicsHeading: 'Wähle ein Thema zum Einstieg', topicsHint: 'Durchsuche das Flottenwissen wie einen gemeinsamen Ordner. Öffne ein Thema für Briefing, Guides, Builds und nächste Schritte.', topicCount: '{count} Themen', resourceCount: '{count} Ressourcen', text: 'Briefing-Thema', resources: 'Ressourcen-Thema', noSummary: 'Öffne dieses Thema, um die Anleitung der Flotte zu lesen.', openTopic: 'Thema öffnen', topicNavigation: 'Vorherige und nächste Themen', previous: 'Vorheriges Thema', next: 'Nächstes Thema', resourcesHeading: 'Guides, Builds und Referenzen', resourcesHint: 'Vertiefe das Thema mit den kuratierten Materialien.', noResourceDescription: 'Öffne diese Ressource für weitere Informationen.', available: 'Verfügbar', noResources: 'Diesem Thema wurden noch keine Ressourcen zugeordnet.' },
      editor: {
        guideSettings: 'Leitfaden-Einstellungen', guideIdentity: 'Titel und Einleitung', addFolder: 'Ordner hinzufügen', selectedFolder: 'Ordner {index}', orderHint: 'Die Ordnerreihenfolge links ist zugleich die Lesereihenfolge.', folderActions: 'Aktionen für {title}', moveUp: 'Ordner nach oben', moveDown: 'Ordner nach unten', removeFolder: '{title} entfernen', folderResources: 'Ressourcen im Ordner', resourceOrderHint: 'Ressourcen erscheinen in dieser Reihenfolge im Ordner.', emptyResources: 'Dieser Ordner ist leer. Füge oben die erste Ressource hinzu.', noFolderTitle: 'Ersten Ordner anlegen', noFolderText: 'Wähle links einen Text- oder Ressourcenordner aus.', saveHint: 'Beim Speichern wird diese Ordnerreihenfolge für Mitglieder veröffentlicht.',
        pageTitle: 'Seitentitel', intro: 'Einleitung', block: 'Abschnitt {index}', untitled: 'Unbenannter Abschnitt', blockType: 'Abschnittstyp',
        textBlock: 'Textabschnitt', resourceBlock: 'Ressourcensammlung', text: 'Text', optionalIntro: 'Optionale Abschnittseinleitung',
        resource: 'Ressource {index}', url: 'Ziel-URL', customLabel: 'Eigene Bezeichnung', customLabelHint: 'Optional – sonst wird der Ressourcentitel verwendet',
        addResource: 'Ressource hinzufügen', addTextBlock: 'Textabschnitt hinzufügen', addResourceBlock: 'Ressourcensammlung hinzufügen', linkGuide: 'Leitfaden verlinken', linkBuild: 'Build verlinken', loadingResources: 'Leitfäden und Builds werden geladen …', resourceLoadError: 'Leitfäden und Builds konnten nicht geladen werden.', noGuides: 'Keine veröffentlichten Leitfäden verfügbar', noBuilds: 'Keine Builds verfügbar',
        types: { guide: 'Leitfaden', build: 'Schiffskonfiguration', internal: 'Hub-Seite', external: 'Externer Link' },
      },
    },
  },
  fr: {
    common: { newCaptainGuide: 'Guide du nouveau capitaine', remove: 'Supprimer', title: 'Titre', description: 'Description' },
    home: { newcomer: { guideTitle: 'Suivre le guide du nouveau capitaine', guideText: 'Utilisez la feuille de route sélectionnée pour les guides essentiels, les builds éprouvés, les questions-réponses et vos premières opérations planifiées.', guideMeta: 'Feuille de route débutant' } },
    newcomerGuide: {
      eyebrow: 'Parcours du nouveau capitaine', title: 'Guide du nouveau capitaine', subtitle: 'Un parcours sélectionné de la première connexion à une participation préparée aux activités de flotte.', memberOnly: 'Membres uniquement', updatedBy: 'Mis à jour par {name}', edit: 'Modifier le guide', loading: 'Chargement du guide …', loadError: 'Le guide n’a pas pu être chargé.', saveError: 'Le guide n’a pas pu être enregistré.', saved: 'Guide enregistré.', textSection: 'Briefing', resourceSection: 'Parcours recommandé', open: 'Ouvrir la ressource', unavailable: 'Ressource indisponible', folderNavigation: 'Dossiers du guide', folders: 'Sommaire', folderCount: '{count} dossiers', folderPosition: 'Dossier {current} sur {total}', emptyFolders: 'Aucun dossier n’a encore été ajouté.',
      explorer: { workspace: 'Base de connaissances des nouveaux joueurs', home: 'Accueil du guide', allTopics: 'Parcourir tous les sujets', back: 'Retour à tous les sujets', addressLabel: 'Emplacement actuel dans le guide', topicsHeading: 'Choisissez un sujet pour commencer', topicsHint: 'Parcourez les connaissances de la flotte comme un dossier partagé. Ouvrez un sujet pour son briefing, ses guides, builds et prochaines étapes.', topicCount: '{count} sujets', resourceCount: '{count} ressources', text: 'Sujet de briefing', resources: 'Sujet de ressources', noSummary: 'Ouvrez ce sujet pour lire les conseils de la flotte.', openTopic: 'Ouvrir le sujet', topicNavigation: 'Sujets précédent et suivant', previous: 'Sujet précédent', next: 'Sujet suivant', resourcesHeading: 'Guides, builds et références', resourcesHint: 'Approfondissez avec les ressources sélectionnées pour ce sujet.', noResourceDescription: 'Ouvrez cette ressource pour plus d’informations.', available: 'Disponible', noResources: 'Aucune ressource n’est encore liée à ce sujet.' },
      editor: { guideSettings: 'Paramètres du guide', guideIdentity: 'Titre et introduction', addFolder: 'Ajouter un dossier', selectedFolder: 'Dossier {index}', orderHint: 'L’ordre à gauche est aussi l’ordre de lecture.', folderActions: 'Actions pour {title}', moveUp: 'Monter le dossier', moveDown: 'Descendre le dossier', removeFolder: 'Supprimer {title}', folderResources: 'Ressources du dossier', resourceOrderHint: 'Les ressources apparaissent dans cet ordre.', emptyResources: 'Ce dossier est vide. Ajoutez sa première ressource.', noFolderTitle: 'Créer le premier dossier', noFolderText: 'Choisissez un dossier de texte ou de ressources à gauche.', saveHint: 'L’enregistrement publie cet ordre pour les membres.', pageTitle: 'Titre de la page', intro: 'Présentation', block: 'Étape {index}', untitled: 'Section sans titre', blockType: 'Type de section', textBlock: 'Section de texte', resourceBlock: 'Collection de ressources', text: 'Texte', optionalIntro: 'Introduction facultative', resource: 'Ressource {index}', url: 'URL cible', customLabel: 'Libellé personnalisé', customLabelHint: 'Facultatif — sinon le titre de la ressource est utilisé', addResource: 'Ajouter une ressource', addTextBlock: 'Ajouter une section de texte', addResourceBlock: 'Ajouter une collection', linkGuide: 'Lier un guide', linkBuild: 'Lier un build', loadingResources: 'Chargement des guides et builds …', resourceLoadError: 'Impossible de charger les guides et builds.', noGuides: 'Aucun guide publié disponible', noBuilds: 'Aucun build disponible', types: { guide: 'Tutoriel', build: 'Configuration', internal: 'Page du hub', external: 'Lien externe' } },
    },
  },
  es: {
    common: { newCaptainGuide: 'Guía para nuevos capitanes', remove: 'Eliminar', title: 'Título', description: 'Descripción' },
    home: { newcomer: { guideTitle: 'Sigue la guía para nuevos capitanes', guideText: 'Usa la ruta seleccionada para encontrar guías esenciales, builds probados, preguntas y respuestas y tus primeras operaciones programadas.', guideMeta: 'Ruta para principiantes' } },
    newcomerGuide: {
      eyebrow: 'Ruta del nuevo capitán', title: 'Guía para nuevos capitanes', subtitle: 'Un camino seleccionado desde el primer acceso hasta una participación preparada en la flota.', memberOnly: 'Solo miembros', updatedBy: 'Actualizado por {name}', edit: 'Editar guía', loading: 'Cargando la guía …', loadError: 'No se pudo cargar la guía.', saveError: 'No se pudo guardar la guía.', saved: 'Guía guardada.', textSection: 'Briefing', resourceSection: 'Ruta recomendada', open: 'Abrir recurso', unavailable: 'Recurso no disponible', folderNavigation: 'Carpetas de la guía', folders: 'Contenido', folderCount: '{count} carpetas', folderPosition: 'Carpeta {current} de {total}', emptyFolders: 'Todavía no hay carpetas.',
      explorer: { workspace: 'Base de conocimientos para nuevos jugadores', home: 'Inicio de la guía', allTopics: 'Explorar todos los temas', back: 'Volver a todos los temas', addressLabel: 'Ubicación actual en la guía', topicsHeading: 'Elige un tema para empezar', topicsHint: 'Explora el conocimiento de la flota como una carpeta compartida. Abre un tema para ver su briefing, guías, builds y próximos pasos.', topicCount: '{count} temas', resourceCount: '{count} recursos', text: 'Tema informativo', resources: 'Tema de recursos', noSummary: 'Abre este tema para leer las instrucciones de la flota.', openTopic: 'Abrir tema', topicNavigation: 'Temas anterior y siguiente', previous: 'Tema anterior', next: 'Tema siguiente', resourcesHeading: 'Guías, builds y referencias', resourcesHint: 'Profundiza con el material seleccionado para este tema.', noResourceDescription: 'Abre este recurso para obtener más información.', available: 'Disponible', noResources: 'Todavía no hay recursos vinculados a este tema.' },
      editor: { guideSettings: 'Ajustes de la guía', guideIdentity: 'Título e introducción', addFolder: 'Añadir carpeta', selectedFolder: 'Carpeta {index}', orderHint: 'El orden de la izquierda también es el orden de lectura.', folderActions: 'Acciones para {title}', moveUp: 'Subir carpeta', moveDown: 'Bajar carpeta', removeFolder: 'Eliminar {title}', folderResources: 'Recursos de la carpeta', resourceOrderHint: 'Los recursos aparecen en este orden.', emptyResources: 'Esta carpeta está vacía. Añade su primer recurso.', noFolderTitle: 'Crear la primera carpeta', noFolderText: 'Elige una carpeta de texto o recursos a la izquierda.', saveHint: 'Al guardar se publica este orden para los miembros.', pageTitle: 'Título de la página', intro: 'Introducción', block: 'Sección {index}', untitled: 'Sección sin título', blockType: 'Tipo de sección', textBlock: 'Sección de texto', resourceBlock: 'Colección de recursos', text: 'Texto', optionalIntro: 'Introducción opcional', resource: 'Recurso {index}', url: 'URL de destino', customLabel: 'Etiqueta personalizada', customLabelHint: 'Opcional; si no, se usa el título del recurso', addResource: 'Añadir recurso', addTextBlock: 'Añadir sección de texto', addResourceBlock: 'Añadir colección', linkGuide: 'Vincular guía', linkBuild: 'Vincular build', loadingResources: 'Cargando guías y builds …', resourceLoadError: 'No se pudieron cargar las guías y builds.', noGuides: 'No hay guías publicadas', noBuilds: 'No hay builds disponibles', types: { guide: 'Guía', build: 'Configuración', internal: 'Página del hub', external: 'Enlace externo' } },
    },
  },
  pt: {
    common: { newCaptainGuide: 'Guia do novo capitão', remove: 'Remover', title: 'Título', description: 'Descrição' },
    home: { newcomer: { guideTitle: 'Segue o guia do novo capitão', guideText: 'Usa o percurso selecionado para encontrar guias essenciais, builds testados, perguntas e respostas e as primeiras operações planeadas.', guideMeta: 'Percurso para iniciantes' } },
    newcomerGuide: {
      eyebrow: 'Percurso do novo capitão', title: 'Guia do novo capitão', subtitle: 'Um percurso selecionado desde o primeiro acesso até à participação preparada na frota.', memberOnly: 'Apenas membros', updatedBy: 'Atualizado por {name}', edit: 'Editar guia', loading: 'A carregar o guia …', loadError: 'Não foi possível carregar o guia.', saveError: 'Não foi possível guardar o guia.', saved: 'Guia guardado.', textSection: 'Briefing', resourceSection: 'Percurso recomendado', open: 'Abrir recurso', unavailable: 'Recurso indisponível', folderNavigation: 'Pastas do guia', folders: 'Conteúdo', folderCount: '{count} pastas', folderPosition: 'Pasta {current} de {total}', emptyFolders: 'Ainda não existem pastas.',
      explorer: { workspace: 'Base de conhecimento para novos jogadores', home: 'Início do guia', allTopics: 'Explorar todos os tópicos', back: 'Voltar a todos os tópicos', addressLabel: 'Local atual no guia', topicsHeading: 'Escolhe um tópico para começar', topicsHint: 'Explora o conhecimento da frota como uma pasta partilhada. Abre um tópico para o briefing, guias, builds e próximos passos.', topicCount: '{count} tópicos', resourceCount: '{count} recursos', text: 'Tópico de briefing', resources: 'Tópico de recursos', noSummary: 'Abre este tópico para ler as orientações da frota.', openTopic: 'Abrir tópico', topicNavigation: 'Tópicos anterior e seguinte', previous: 'Tópico anterior', next: 'Tópico seguinte', resourcesHeading: 'Guias, builds e referências', resourcesHint: 'Aprofunda o tema com os materiais selecionados.', noResourceDescription: 'Abre este recurso para mais informações.', available: 'Disponível', noResources: 'Ainda não existem recursos ligados a este tópico.' },
      editor: { guideSettings: 'Definições do guia', guideIdentity: 'Título e introdução', addFolder: 'Adicionar pasta', selectedFolder: 'Pasta {index}', orderHint: 'A ordem à esquerda também é a ordem de leitura.', folderActions: 'Ações para {title}', moveUp: 'Mover pasta para cima', moveDown: 'Mover pasta para baixo', removeFolder: 'Remover {title}', folderResources: 'Recursos da pasta', resourceOrderHint: 'Os recursos aparecem nesta ordem.', emptyResources: 'Esta pasta está vazia. Adiciona o primeiro recurso.', noFolderTitle: 'Criar a primeira pasta', noFolderText: 'Escolhe uma pasta de texto ou recursos à esquerda.', saveHint: 'Guardar publica esta ordem para os membros.', pageTitle: 'Título da página', intro: 'Introdução', block: 'Secção {index}', untitled: 'Secção sem título', blockType: 'Tipo de secção', textBlock: 'Secção de texto', resourceBlock: 'Coleção de recursos', text: 'Texto', optionalIntro: 'Introdução opcional', resource: 'Recurso {index}', url: 'URL de destino', customLabel: 'Etiqueta personalizada', customLabelHint: 'Opcional — caso contrário é usado o título do recurso', addResource: 'Adicionar recurso', addTextBlock: 'Adicionar secção de texto', addResourceBlock: 'Adicionar coleção', linkGuide: 'Ligar guia', linkBuild: 'Ligar build', loadingResources: 'A carregar guias e builds …', resourceLoadError: 'Não foi possível carregar guias e builds.', noGuides: 'Nenhum guia publicado disponível', noBuilds: 'Nenhum build disponível', types: { guide: 'Guia', build: 'Configuração', internal: 'Página do hub', external: 'Ligação externa' } },
    },
  },
  ru: {
    common: { newCaptainGuide: 'Гайд нового капитана', remove: 'Удалить', title: 'Заголовок', description: 'Описание' },
    home: { newcomer: { guideTitle: 'Следуйте гайду нового капитана', guideText: 'Используйте подобранный маршрут к важным гайдам, проверенным билдам, вопросам и ответам и первым запланированным операциям.', guideMeta: 'Маршрут для новичков' } },
    newcomerGuide: {
      eyebrow: 'Маршрут нового капитана', title: 'Гайд нового капитана', subtitle: 'Подобранный путь от первого входа до подготовленного участия в действиях флота.', memberOnly: 'Только для участников', updatedBy: 'Обновил: {name}', edit: 'Редактировать гайд', loading: 'Загрузка гайда …', loadError: 'Не удалось загрузить гайд.', saveError: 'Не удалось сохранить гайд.', saved: 'Гайд сохранён.', textSection: 'Брифинг', resourceSection: 'Рекомендуемый путь', open: 'Открыть ресурс', unavailable: 'Ресурс недоступен', folderNavigation: 'Папки гайда', folders: 'Содержание', folderCount: 'Папок: {count}', folderPosition: 'Папка {current} из {total}', emptyFolders: 'Папок пока нет.',
      explorer: { workspace: 'База знаний для новых игроков', home: 'Главная гайда', allTopics: 'Все темы', back: 'Вернуться ко всем темам', addressLabel: 'Текущее место в гайде', topicsHeading: 'Выберите тему для начала', topicsHint: 'Просматривайте знания флота как общую папку. Откройте тему, чтобы увидеть брифинг, гайды, билды и следующие шаги.', topicCount: 'Тем: {count}', resourceCount: 'Ресурсов: {count}', text: 'Тема-брифинг', resources: 'Тема с ресурсами', noSummary: 'Откройте тему, чтобы прочитать указания флота.', openTopic: 'Открыть тему', topicNavigation: 'Предыдущая и следующая темы', previous: 'Предыдущая тема', next: 'Следующая тема', resourcesHeading: 'Гайды, билды и ссылки', resourcesHint: 'Углубитесь в тему с подобранными материалами.', noResourceDescription: 'Откройте ресурс для дополнительной информации.', available: 'Доступно', noResources: 'К этой теме пока не привязаны ресурсы.' },
      editor: { guideSettings: 'Настройки гайда', guideIdentity: 'Название и введение', addFolder: 'Добавить папку', selectedFolder: 'Папка {index}', orderHint: 'Порядок слева также является порядком чтения.', folderActions: 'Действия для {title}', moveUp: 'Переместить папку вверх', moveDown: 'Переместить папку вниз', removeFolder: 'Удалить {title}', folderResources: 'Ресурсы папки', resourceOrderHint: 'Ресурсы отображаются в этом порядке.', emptyResources: 'Эта папка пуста. Добавьте первый ресурс.', noFolderTitle: 'Создать первую папку', noFolderText: 'Выберите слева текстовую папку или папку ресурсов.', saveHint: 'Сохранение публикует этот порядок для участников.', pageTitle: 'Заголовок страницы', intro: 'Введение', block: 'Раздел {index}', untitled: 'Раздел без названия', blockType: 'Тип раздела', textBlock: 'Текстовый раздел', resourceBlock: 'Подборка ресурсов', text: 'Текст', optionalIntro: 'Необязательное введение', resource: 'Ресурс {index}', url: 'Целевой URL', customLabel: 'Собственная подпись', customLabelHint: 'Необязательно — иначе используется название ресурса', addResource: 'Добавить ресурс', addTextBlock: 'Добавить текстовый раздел', addResourceBlock: 'Добавить подборку', linkGuide: 'Добавить ссылку на гайд', linkBuild: 'Добавить ссылку на билд', loadingResources: 'Загрузка гайдов и билдов …', resourceLoadError: 'Не удалось загрузить гайды и билды.', noGuides: 'Нет опубликованных гайдов', noBuilds: 'Нет доступных билдов', types: { guide: 'Гайд', build: 'Билд', internal: 'Страница хаба', external: 'Внешняя ссылка' } },
    },
  },
  cn: {
    common: { newCaptainGuide: '新船长指南', remove: '移除', title: '标题', description: '描述' },
    home: { newcomer: { guideTitle: '按照新船长指南前进', guideText: '通过精选路线找到关键指南、可靠配装、问答内容以及首次计划行动。', guideMeta: '新手精选路线' } },
    newcomerGuide: {
      eyebrow: '新船长路线', title: '新船长指南', subtitle: '从首次登录到做好准备参与舰队活动的精选路线。', memberOnly: '仅限成员', updatedBy: '由 {name} 更新', edit: '编辑指南', loading: '正在加载指南…', loadError: '无法加载指南。', saveError: '无法保存指南。', saved: '指南已保存。', textSection: '简报', resourceSection: '推荐路线', open: '打开资源', unavailable: '资源不可用', folderNavigation: '指南文件夹', folders: '目录', folderCount: '{count} 个文件夹', folderPosition: '文件夹 {current}/{total}', emptyFolders: '尚未添加文件夹。',
      explorer: { workspace: '新玩家知识库', home: '指南首页', allTopics: '浏览所有主题', back: '返回所有主题', addressLabel: '指南中的当前位置', topicsHeading: '选择一个主题开始', topicsHint: '像浏览共享文件夹一样探索舰队知识。打开主题查看简报、指南、配装和后续步骤。', topicCount: '{count} 个主题', resourceCount: '{count} 个资源', text: '简报主题', resources: '资源主题', noSummary: '打开此主题阅读舰队指南。', openTopic: '打开主题', topicNavigation: '上一个和下一个主题', previous: '上一个主题', next: '下一个主题', resourcesHeading: '指南、配装和参考资料', resourcesHint: '通过为此主题精选的资料继续深入。', noResourceDescription: '打开此资源了解更多信息。', available: '可用', noResources: '此主题尚未关联资源。' },
      editor: { guideSettings: '指南设置', guideIdentity: '标题和介绍', addFolder: '添加文件夹', selectedFolder: '文件夹 {index}', orderHint: '左侧顺序也是阅读顺序。', folderActions: '{title} 的操作', moveUp: '上移文件夹', moveDown: '下移文件夹', removeFolder: '移除 {title}', folderResources: '文件夹资源', resourceOrderHint: '资源将按此顺序显示。', emptyResources: '此文件夹为空，请添加第一个资源。', noFolderTitle: '创建第一个文件夹', noFolderText: '请从左侧选择文本或资源文件夹。', saveHint: '保存后将向成员发布此文件夹顺序。', pageTitle: '页面标题', intro: '介绍', block: '第 {index} 节', untitled: '未命名章节', blockType: '章节类型', textBlock: '文本章节', resourceBlock: '资源集合', text: '文本', optionalIntro: '可选章节介绍', resource: '资源 {index}', url: '目标网址', customLabel: '自定义名称', customLabelHint: '可选；否则使用资源标题', addResource: '添加资源', addTextBlock: '添加文本章节', addResourceBlock: '添加资源集合', linkGuide: '关联指南', linkBuild: '关联配装', loadingResources: '正在加载指南和配装…', resourceLoadError: '无法加载指南和配装。', noGuides: '暂无已发布指南', noBuilds: '暂无可用配装', types: { guide: '指南', build: '配装', internal: '站内页面', external: '外部链接' } },
    },
  },
}
