export const securityAuditDashboardMessages = {
  en: {
    admin: {
      tabs: { audit: 'Audit history' },
      security: { title: 'IP-ban signal review', subtitle: 'Aggregated, short-lived security signals for deciding whether to block an IP address.', from: 'From', to: 'To', sort: 'IP sorting', sortThreat: 'Highest threat', sortEvents: 'Most signals', sortRecent: 'Most recent', sortIp: 'IP address', selectedIp: 'Focused IP', allIps: 'All IPs', currentThreat: 'Current threat level', events: 'Signals', elevatedCandidates: 'Elevated candidates', reconnaissance: 'Scan probes', loginFailures: 'Login failures', rateLimits: 'Rate-limit hits', uniqueIps: 'Unique IPs', loading: 'Loading IP-ban candidates ...', loadError: 'IP-ban candidates could not be loaded.', byDay: 'Signals by day', byIp: 'IP-ban candidates', day: 'Day', lastSeen: 'Last active day', noIps: 'No ban-relevant signals in this period.', methodNote: 'Scores use only daily counts of coarse scan, failed-login and rate-limit signals. No route, query string, user agent, request body, request ID, exact request time or exception is retained. Blocking always remains a deliberate administrator action.', filtersTitle: 'Ban-candidate scope', filtersHint: 'Filter the temporary, purpose-bound signals by date, threat level and candidate IP.', quickRange: 'Quick range', today: 'Today', sevenDays: '7 days', thirtyDays: '30 days', threatFilter: 'Threat level', allThreats: 'All threat levels', ipFilter: 'IP focus', resetFilters: 'Reset filters', activeFilters: '{count} active filters', filteredView: 'Filtered view', matchingIps: 'Matching IPs', clickDayHint: 'Select a day to narrow the candidate view to that date.', topMatches: 'Top matching IPs', chooseIpHint: 'Select an IP for its aggregated threat profile.', noMatches: 'No IPs match the selected filters.', levels: { low: 'Low', guarded: 'Guarded', elevated: 'Elevated', critical: 'Critical' } },
      audit: {
        title: 'Audit history', subtitle: 'Who changed which managed content, when it happened and which fields were touched.',
        loading: 'Loading audit history ...', loadError: 'Audit history could not be loaded.', empty: 'No matching changes found.',
        allEntities: 'All content types', allActions: 'All actions', actorPlaceholder: 'Filter by user', fields: 'Changed fields',
        actions: { create: 'Created', update: 'Updated', delete: 'Deleted' },
        entities: { build: 'Build', forum_thread: 'Forum thread', forum_post: 'Forum post', guide: 'Guide', newcomer_guide: 'Starter guide' },
      },
    },
    builds: { visuals: { selectedShip: 'Selected ship' } },
  },
  de: {
    admin: {
      tabs: { audit: 'Änderungshistorie' },
      security: { title: 'Prüfung von IP-Sperrsignalen', subtitle: 'Aggregierte, kurzzeitig gespeicherte Sicherheitssignale für die Entscheidung über eine IP-Sperre.', from: 'Von', to: 'Bis', sort: 'IP-Sortierung', sortThreat: 'Höchste Bedrohung', sortEvents: 'Meiste Signale', sortRecent: 'Zuletzt aktiv', sortIp: 'IP-Adresse', selectedIp: 'Fokussierte IP', allIps: 'Alle IPs', currentThreat: 'Aktuelles Threat-Level', events: 'Signale', elevatedCandidates: 'Erhöhte Kandidaten', reconnaissance: 'Scan-Versuche', loginFailures: 'Login-Fehlschläge', rateLimits: 'Rate-Limit-Treffer', uniqueIps: 'Eindeutige IPs', loading: 'IP-Sperrkandidaten werden geladen ...', loadError: 'IP-Sperrkandidaten konnten nicht geladen werden.', byDay: 'Signale nach Tagen', byIp: 'IP-Sperrkandidaten', day: 'Tag', lastSeen: 'Zuletzt aktiver Tag', noIps: 'Keine sperrrelevanten Signale in diesem Zeitraum.', methodNote: 'Die Bewertung verwendet ausschließlich tägliche Zähler grober Signale für Scans, fehlgeschlagene Logins und Rate-Limits. Route, Query-String, User-Agent, Request-Inhalt, Request-ID, genauer Request-Zeitpunkt und Exceptions werden nicht gespeichert. Eine Sperre bleibt immer eine bewusste Admin-Entscheidung.', filtersTitle: 'Sperrkandidaten filtern', filtersHint: 'Die kurzzeitig und zweckgebunden gespeicherten Signale nach Zeitraum, Threat-Level und Kandidaten-IP filtern.', quickRange: 'Schnellzeitraum', today: 'Heute', sevenDays: '7 Tage', thirtyDays: '30 Tage', threatFilter: 'Threat-Level', allThreats: 'Alle Threat-Level', ipFilter: 'IP-Fokus', resetFilters: 'Filter zurücksetzen', activeFilters: '{count} aktive Filter', filteredView: 'Gefilterte Ansicht', matchingIps: 'Passende IPs', clickDayHint: 'Einen Tag auswählen, um die Kandidatenansicht auf dieses Datum einzugrenzen.', topMatches: 'Auffälligste passende IPs', chooseIpHint: 'Eine IP auswählen, um ihr aggregiertes Threat-Profil zu öffnen.', noMatches: 'Keine IP passt zu den gewählten Filtern.', levels: { low: 'Niedrig', guarded: 'Beobachten', elevated: 'Erhöht', critical: 'Kritisch' } },
      audit: {
        title: 'Änderungshistorie', subtitle: 'Wer wann welche verwalteten Inhalte geändert hat und welche Felder betroffen waren.',
        loading: 'Änderungshistorie wird geladen ...', loadError: 'Änderungshistorie konnte nicht geladen werden.', empty: 'Keine passenden Änderungen gefunden.',
        allEntities: 'Alle Inhaltstypen', allActions: 'Alle Aktionen', actorPlaceholder: 'Nach Benutzer filtern', fields: 'Geänderte Felder',
        actions: { create: 'Erstellt', update: 'Geändert', delete: 'Gelöscht' },
        entities: { build: 'Schiffskonfiguration', forum_thread: 'Forum-Thread', forum_post: 'Forum-Beitrag', guide: 'Leitfaden', newcomer_guide: 'Starter-Leitfaden' },
      },
    },
    builds: { visuals: { selectedShip: 'Ausgewähltes Schiff' } },
  },
  fr: {
    admin: {
      tabs: { audit: 'Historique d’audit' },
      security: { title: 'Examen des signaux de blocage IP', subtitle: 'Signaux de sécurité agrégés et conservés brièvement pour décider d’un blocage IP.', from: 'Du', to: 'Au', sort: 'Tri des IP', sortThreat: 'Menace la plus élevée', sortEvents: 'Plus de signaux', sortRecent: 'Activité la plus récente', sortIp: 'Adresse IP', selectedIp: 'IP ciblée', allIps: 'Toutes les IP', currentThreat: 'Niveau de menace actuel', events: 'Signaux', elevatedCandidates: 'Candidats élevés', reconnaissance: 'Tentatives de scan', loginFailures: 'Échecs de connexion', rateLimits: 'Limites de débit atteintes', uniqueIps: 'IP uniques', loading: 'Chargement des candidats au blocage ...', loadError: 'Impossible de charger les candidats au blocage.', byDay: 'Signaux par jour', byIp: 'Candidats au blocage IP', day: 'Jour', lastSeen: 'Dernier jour actif', noIps: 'Aucun signal pertinent pour un blocage sur cette période.', methodNote: 'Le score utilise uniquement des compteurs journaliers de signaux généraux de scan, d’échec de connexion et de limitation de débit. Aucun chemin, paramètre de requête, agent utilisateur, contenu, identifiant ou horaire exact de requête, ni exception n’est conservé. Le blocage reste une décision explicite de l’administrateur.', filtersTitle: 'Périmètre des candidats', filtersHint: 'Filtrer les signaux temporaires et limités à leur finalité par date, menace et IP.', quickRange: 'Période rapide', today: 'Aujourd’hui', sevenDays: '7 jours', thirtyDays: '30 jours', threatFilter: 'Niveau de menace', allThreats: 'Toutes les menaces', ipFilter: 'IP ciblée', resetFilters: 'Réinitialiser', activeFilters: '{count} filtres actifs', filteredView: 'Vue filtrée', matchingIps: 'IP correspondantes', clickDayHint: 'Sélectionnez un jour pour limiter la vue à cette date.', topMatches: 'Principales IP correspondantes', chooseIpHint: 'Sélectionnez une IP pour afficher son profil agrégé.', noMatches: 'Aucune IP ne correspond aux filtres.', levels: { low: 'Faible', guarded: 'Surveillé', elevated: 'Élevé', critical: 'Critique' } },
      audit: { title: 'Historique d’audit', subtitle: 'Qui a modifié quel contenu, quand et quels champs ont changé.', loading: 'Chargement de l’historique ...', loadError: 'Impossible de charger l’historique.', empty: 'Aucune modification correspondante.', allEntities: 'Tous les contenus', allActions: 'Toutes les actions', actorPlaceholder: 'Filtrer par utilisateur', fields: 'Champs modifiés', actions: { create: 'Créé', update: 'Modifié', delete: 'Supprimé' }, entities: { build: 'Configuration', forum_thread: 'Sujet du forum', forum_post: 'Message du forum', guide: 'Manuel', newcomer_guide: 'Guide de démarrage' } },
    },
    builds: { visuals: { selectedShip: 'Navire sélectionné' } },
  },
  es: {
    admin: {
      tabs: { audit: 'Historial de auditoría' },
      security: { title: 'Revisión de señales de bloqueo IP', subtitle: 'Señales de seguridad agregadas y de corta duración para decidir un bloqueo de IP.', from: 'Desde', to: 'Hasta', sort: 'Orden de IP', sortThreat: 'Mayor amenaza', sortEvents: 'Más señales', sortRecent: 'Actividad más reciente', sortIp: 'Dirección IP', selectedIp: 'IP enfocada', allIps: 'Todas las IP', currentThreat: 'Nivel de amenaza actual', events: 'Señales', elevatedCandidates: 'Candidatos elevados', reconnaissance: 'Intentos de escaneo', loginFailures: 'Fallos de inicio de sesión', rateLimits: 'Límites de frecuencia alcanzados', uniqueIps: 'IP únicas', loading: 'Cargando candidatos de bloqueo ...', loadError: 'No se pudieron cargar los candidatos de bloqueo.', byDay: 'Señales por día', byIp: 'Candidatos de bloqueo IP', day: 'Día', lastSeen: 'Último día activo', noIps: 'No hay señales relevantes para bloqueo en este periodo.', methodNote: 'La puntuación usa solo contadores diarios de señales generales de escaneo, fallos de acceso y límites de frecuencia. No se conservan rutas, consultas, agentes de usuario, contenidos, identificadores, horas exactas de solicitudes ni excepciones. El bloqueo siempre requiere una decisión explícita del administrador.', filtersTitle: 'Ámbito de candidatos', filtersHint: 'Filtra las señales temporales y limitadas a su finalidad por fecha, amenaza e IP.', quickRange: 'Periodo rápido', today: 'Hoy', sevenDays: '7 días', thirtyDays: '30 días', threatFilter: 'Nivel de amenaza', allThreats: 'Todas las amenazas', ipFilter: 'IP enfocada', resetFilters: 'Restablecer', activeFilters: '{count} filtros activos', filteredView: 'Vista filtrada', matchingIps: 'IP coincidentes', clickDayHint: 'Selecciona un día para limitar la vista a esa fecha.', topMatches: 'Principales IP coincidentes', chooseIpHint: 'Selecciona una IP para ver su perfil agregado.', noMatches: 'Ninguna IP coincide con los filtros.', levels: { low: 'Bajo', guarded: 'Vigilado', elevated: 'Elevado', critical: 'Crítico' } },
      audit: { title: 'Historial de auditoría', subtitle: 'Quién cambió qué contenido, cuándo y qué campos fueron afectados.', loading: 'Cargando historial ...', loadError: 'No se pudo cargar el historial.', empty: 'No hay cambios coincidentes.', allEntities: 'Todos los contenidos', allActions: 'Todas las acciones', actorPlaceholder: 'Filtrar por usuario', fields: 'Campos cambiados', actions: { create: 'Creado', update: 'Actualizado', delete: 'Eliminado' }, entities: { build: 'Configuración', forum_thread: 'Tema del foro', forum_post: 'Mensaje del foro', guide: 'Guía', newcomer_guide: 'Guía inicial' } },
    },
    builds: { visuals: { selectedShip: 'Barco seleccionado' } },
  },
  pt: {
    admin: {
      tabs: { audit: 'Histórico de auditoria' },
      security: { title: 'Revisão de sinais de bloqueio de IP', subtitle: 'Sinais de segurança agregados e mantidos por pouco tempo para decidir um bloqueio de IP.', from: 'De', to: 'Até', sort: 'Ordenação de IP', sortThreat: 'Maior ameaça', sortEvents: 'Mais sinais', sortRecent: 'Atividade mais recente', sortIp: 'Endereço IP', selectedIp: 'IP em foco', allIps: 'Todos os IPs', currentThreat: 'Nível de ameaça atual', events: 'Sinais', elevatedCandidates: 'Candidatos elevados', reconnaissance: 'Tentativas de scan', loginFailures: 'Falhas de início de sessão', rateLimits: 'Limites de frequência atingidos', uniqueIps: 'IPs únicos', loading: 'A carregar candidatos a bloqueio ...', loadError: 'Não foi possível carregar os candidatos a bloqueio.', byDay: 'Sinais por dia', byIp: 'Candidatos a bloqueio de IP', day: 'Dia', lastSeen: 'Último dia ativo', noIps: 'Sem sinais relevantes para bloqueio neste período.', methodNote: 'A pontuação usa apenas contadores diários de sinais gerais de scan, falhas de início de sessão e limites de frequência. Não são guardados caminhos, consultas, user agents, conteúdos, identificadores, horas exatas dos pedidos ou exceções. O bloqueio exige sempre uma decisão explícita do administrador.', filtersTitle: 'Âmbito dos candidatos', filtersHint: 'Filtre os sinais temporários e limitados à finalidade por data, ameaça e IP.', quickRange: 'Período rápido', today: 'Hoje', sevenDays: '7 dias', thirtyDays: '30 dias', threatFilter: 'Nível de ameaça', allThreats: 'Todas as ameaças', ipFilter: 'IP em foco', resetFilters: 'Repor filtros', activeFilters: '{count} filtros ativos', filteredView: 'Vista filtrada', matchingIps: 'IPs correspondentes', clickDayHint: 'Selecione um dia para limitar a vista a essa data.', topMatches: 'Principais IPs correspondentes', chooseIpHint: 'Selecione um IP para ver o perfil agregado.', noMatches: 'Nenhum IP corresponde aos filtros.', levels: { low: 'Baixo', guarded: 'Vigiado', elevated: 'Elevado', critical: 'Crítico' } },
      audit: { title: 'Histórico de auditoria', subtitle: 'Quem alterou que conteúdo, quando e quais campos foram afetados.', loading: 'A carregar histórico ...', loadError: 'Não foi possível carregar o histórico.', empty: 'Nenhuma alteração correspondente.', allEntities: 'Todos os conteúdos', allActions: 'Todas as ações', actorPlaceholder: 'Filtrar por utilizador', fields: 'Campos alterados', actions: { create: 'Criado', update: 'Atualizado', delete: 'Eliminado' }, entities: { build: 'Configuração', forum_thread: 'Tópico do fórum', forum_post: 'Mensagem do fórum', guide: 'Guia', newcomer_guide: 'Guia inicial' } },
    },
    builds: { visuals: { selectedShip: 'Navio selecionado' } },
  },
  ru: {
    admin: {
      tabs: { audit: 'История изменений' },
      security: { title: 'Проверка сигналов для блокировки IP', subtitle: 'Агрегированные краткосрочные сигналы безопасности для решения о блокировке IP.', from: 'С', to: 'По', sort: 'Сортировка IP', sortThreat: 'Наивысшая угроза', sortEvents: 'Больше сигналов', sortRecent: 'Последняя активность', sortIp: 'IP-адрес', selectedIp: 'Выбранный IP', allIps: 'Все IP', currentThreat: 'Текущий уровень угрозы', events: 'Сигналы', elevatedCandidates: 'Повышенные кандидаты', reconnaissance: 'Попытки сканирования', loginFailures: 'Ошибки входа', rateLimits: 'Срабатывания ограничения частоты', uniqueIps: 'Уникальные IP', loading: 'Загрузка кандидатов на блокировку ...', loadError: 'Не удалось загрузить кандидатов на блокировку.', byDay: 'Сигналы по дням', byIp: 'Кандидаты на блокировку IP', day: 'День', lastSeen: 'Последний активный день', noIps: 'За этот период нет сигналов, значимых для блокировки.', methodNote: 'Оценка использует только суточные счётчики общих сигналов сканирования, неудачных входов и ограничений частоты. Маршруты, строки запроса, user-agent, содержимое, идентификаторы, точное время запросов и исключения не сохраняются. Блокировка всегда остаётся явным решением администратора.', filtersTitle: 'Область кандидатов', filtersHint: 'Фильтруйте временные целевые сигналы по дате, угрозе и IP.', quickRange: 'Быстрый период', today: 'Сегодня', sevenDays: '7 дней', thirtyDays: '30 дней', threatFilter: 'Уровень угрозы', allThreats: 'Все угрозы', ipFilter: 'Выбранный IP', resetFilters: 'Сбросить', activeFilters: 'Активных фильтров: {count}', filteredView: 'Отфильтровано', matchingIps: 'Подходящие IP', clickDayHint: 'Выберите день, чтобы ограничить представление этой датой.', topMatches: 'Основные подходящие IP', chooseIpHint: 'Выберите IP для просмотра агрегированного профиля.', noMatches: 'Нет IP, соответствующих фильтрам.', levels: { low: 'Низкий', guarded: 'Наблюдение', elevated: 'Повышенный', critical: 'Критический' } },
      audit: { title: 'История изменений', subtitle: 'Кто, когда и какие управляемые материалы менял, а также затронутые поля.', loading: 'Загрузка истории ...', loadError: 'Не удалось загрузить историю.', empty: 'Подходящих изменений нет.', allEntities: 'Все типы контента', allActions: 'Все действия', actorPlaceholder: 'Фильтр по пользователю', fields: 'Изменённые поля', actions: { create: 'Создано', update: 'Изменено', delete: 'Удалено' }, entities: { build: 'Билд', forum_thread: 'Тема форума', forum_post: 'Сообщение форума', guide: 'Руководство', newcomer_guide: 'Стартовое руководство' } },
    },
    builds: { visuals: { selectedShip: 'Выбранный корабль' } },
  },
  cn: {
    admin: {
      tabs: { audit: '审计历史' },
      security: { title: 'IP 封禁信号审核', subtitle: '用于决定是否封禁 IP 的聚合短期安全信号。', from: '开始', to: '结束', sort: 'IP 排序', sortThreat: '最高威胁', sortEvents: '最多信号', sortRecent: '最近活动', sortIp: 'IP 地址', selectedIp: '聚焦 IP', allIps: '全部 IP', currentThreat: '当前威胁等级', events: '信号', elevatedCandidates: '高风险候选', reconnaissance: '扫描尝试', loginFailures: '登录失败', rateLimits: '频率限制触发', uniqueIps: '唯一 IP', loading: '正在加载封禁候选 ...', loadError: '无法加载封禁候选。', byDay: '每日信号', byIp: 'IP 封禁候选', day: '日期', lastSeen: '最后活跃日期', noIps: '此期间没有与封禁相关的信号。', methodNote: '评分仅使用扫描、登录失败和频率限制等粗粒度信号的每日计数。不会保留路由、查询字符串、User-Agent、请求内容、请求标识、精确请求时间或异常。封禁始终需要管理员明确决定。', filtersTitle: '封禁候选范围', filtersHint: '按日期、威胁等级和候选 IP 筛选临时且限定用途的信号。', quickRange: '快捷时间', today: '今天', sevenDays: '7 天', thirtyDays: '30 天', threatFilter: '威胁等级', allThreats: '全部威胁', ipFilter: '聚焦 IP', resetFilters: '重置筛选', activeFilters: '{count} 个筛选条件', filteredView: '筛选视图', matchingIps: '匹配 IP', clickDayHint: '选择日期以将候选视图限制到该日。', topMatches: '主要匹配 IP', chooseIpHint: '选择 IP 查看其聚合威胁详情。', noMatches: '没有符合筛选条件的 IP。', levels: { low: '低', guarded: '关注', elevated: '升高', critical: '严重' } },
      audit: { title: '审计历史', subtitle: '查看谁在何时修改了哪些受管内容及涉及的字段。', loading: '正在加载审计历史 ...', loadError: '无法加载审计历史。', empty: '没有匹配的变更。', allEntities: '所有内容类型', allActions: '所有操作', actorPlaceholder: '按用户筛选', fields: '变更字段', actions: { create: '已创建', update: '已更新', delete: '已删除' }, entities: { build: '配置', forum_thread: '论坛主题', forum_post: '论坛帖子', guide: '指南', newcomer_guide: '新手指南' } },
    },
    builds: { visuals: { selectedShip: '已选择船只' } },
  },
}
