export const strategyPlannerMessages = {
  en: {
    strategyPlanner: {
      title: 'Strategy planner', eyebrow: 'Port-Battle planning', subtitle: 'Preserve the chart as a background and keep every tactical mark editable above it.',
      tools: 'Tools', showTools: 'Show tools', hideTools: 'Hide tools', legend: 'Strategic legend', playerList: 'Player list, builds and guides',
      inspector: 'Inspector', inspectorHint: 'Open only the sections you need while keeping the chart in view.', briefing: 'Briefing and chart', selectedObject: 'Selected object', transform: 'Size and rotation', transformHint: 'Transform the selected object', sharing: 'Sharing and access', sharingHint: 'Publication and share link',
      commandDeck: 'Command deck', history: 'Edit history', drawingTools: 'Draw and select', formationsLabel: 'Formations', annotations: 'Annotations',
      create: 'New strategy', empty: 'No strategies saved yet.', loading: 'Loading strategy…', saving: 'Saving…', save: 'Save strategy', saved: 'Strategy saved.',
      titleLabel: 'Strategy title', descriptionLabel: 'Briefing notes', background: 'Background chart', backgroundHint: 'Upload a JPG, PNG, GIF or WebP image. The original image remains separate from the drawing layer.',
      objects: 'Drawing layer', marker: 'Ship marker', line: 'Line', arrow: 'Arrow', text: 'Text', formation: 'Formation', freehand: 'Freehand', select: 'Select',
      ship: 'Ship', shipName: 'Ship name (optional)', playerName: 'Player name (optional)', build: 'Website build (optional)', guide: 'Website guide (optional)',
      noBuild: 'No linked build', noGuide: 'No linked guide', addMarker: 'Add ship marker', addText: 'Add text', textValue: 'Text', formationType: 'Formation type',
      formations: { line: 'Battle line', circle: 'Circle', oval: 'Oval', wedge: 'Wedge', column: 'Column', box: 'Box' },
      color: 'Color', creationColor: 'New object color', textColor: 'Text color', rotation: 'Rotation', scale: 'Scale', deleteObject: 'Delete selected object', undo: 'Undo', redo: 'Redo',
      publish: 'Publish share link', unpublish: 'Disable share link', copyLink: 'Copy share link', copied: 'Share link copied.', private: 'Private', published: 'Published',
      print: 'Print / save PDF', downloadSvg: 'Download SVG', view: 'View', edit: 'Edit', delete: 'Delete', confirmDelete: 'Delete this strategy permanently?',
      readOnly: 'Shared read-only strategy', missingBackground: 'Upload a background image before saving.', missingShip: 'Select a ship before adding a marker.', invalidShipReference: 'Every ship marker must use a ship from the website catalog. Builds and guides remain optional.', invalidBuildReference: 'A linked build must belong to the same ship as its marker.', loadError: 'Could not load the strategy.', saveError: 'Could not save the strategy.',
      catalogError: 'Could not load ships, builds or guides.', shareError: 'Could not update the share link.', exportError: 'Could not export the strategy with its background image.', objectHelp: 'Select and drag objects on the chart. Arrow keys move the selected object precisely.',
      formationLine: 'Line formation', formationCircle: 'Circle formation', formationWedge: 'Wedge formation', formationColumn: 'Column formation', formationBox: 'Box formation',
    },
  },
  de: { strategyPlanner: {
    inspector: 'Inspektor', inspectorHint: 'Öffne nur die benötigten Bereiche und behalte die Karte im Blick.', briefing: 'Briefing und Karte', selectedObject: 'Ausgewähltes Objekt', transform: 'Größe und Drehung', transformHint: 'Ausgewähltes Objekt transformieren', sharing: 'Freigabe und Zugriff', sharingHint: 'Veröffentlichung und Freigabelink', commandDeck: 'Kommandodeck', history: 'Bearbeitungsverlauf', drawingTools: 'Zeichnen und auswählen', formationsLabel: 'Formationen', annotations: 'Anmerkungen',
    title: 'Strategieplaner', tools: 'Werkzeuge', showTools: 'Werkzeuge anzeigen', hideTools: 'Werkzeuge ausblenden', legend: 'Strategische Legende', playerList: 'Spielerliste, Builds und Leitfäden', create: 'Neue Strategie', descriptionLabel: 'Briefing-Notizen', objects: 'Zeichenebene', line: 'Linie', arrow: 'Pfeil', select: 'Auswählen', playerName: 'Spielername (optional)', build: 'Website-Build (optional)', guide: 'Website-Leitfaden (optional)', addText: 'Text hinzufügen', creationColor: 'Farbe neuer Objekte', textColor: 'Textfarbe', rotation: 'Drehung', scale: 'Größe', undo: 'Rückgängig', redo: 'Wiederholen', publish: 'Freigabelink veröffentlichen', unpublish: 'Freigabelink deaktivieren', copyLink: 'Freigabelink kopieren', copied: 'Freigabelink kopiert.', private: 'Privat', published: 'Veröffentlicht', print: 'Drucken / als PDF speichern', downloadSvg: 'SVG herunterladen', view: 'Anzeigen', edit: 'Bearbeiten', readOnly: 'Geteilte schreibgeschützte Strategie', invalidShipReference: 'Jede Schiffsmarkierung muss ein Schiff aus dem Website-Katalog verwenden. Builds und Leitfäden bleiben optional.', formations: { line: 'Gefechtslinie', circle: 'Kreis', oval: 'Ellipse', wedge: 'Keil', column: 'Kolonne', box: 'Rechteck' },
  } },
  fr: { strategyPlanner: {
    inspector: 'Inspecteur', inspectorHint: 'Ouvrez uniquement les sections utiles tout en gardant la carte visible.', briefing: 'Briefing et carte', selectedObject: 'Objet sélectionné', transform: 'Taille et rotation', transformHint: 'Transformer l’objet sélectionné', sharing: 'Partage et accès', sharingHint: 'Publication et lien de partage', commandDeck: 'Poste de commande', history: 'Historique des modifications', drawingTools: 'Dessiner et sélectionner', formationsLabel: 'Formations', annotations: 'Notes tactiques',
    title: 'Planificateur stratégique', tools: 'Outils', showTools: 'Afficher les outils', hideTools: 'Masquer les outils', legend: 'Légende stratégique', create: 'Nouvelle stratégie', descriptionLabel: 'Notes de briefing', objects: 'Calque de dessin', line: 'Ligne', arrow: 'Flèche', select: 'Sélectionner', playerName: 'Nom du joueur (facultatif)', build: 'Build du site (facultatif)', guide: 'Guide du site (facultatif)', addText: 'Ajouter du texte', creationColor: 'Couleur du nouvel objet', textColor: 'Couleur du texte', rotation: 'Orientation', scale: 'Échelle', undo: 'Annuler', redo: 'Rétablir', publish: 'Publier le lien de partage', unpublish: 'Désactiver le lien de partage', copyLink: 'Copier le lien de partage', copied: 'Lien de partage copié.', private: 'Privée', published: 'Publiée', print: 'Imprimer / enregistrer PDF', downloadSvg: 'Télécharger le SVG', view: 'Voir', edit: 'Modifier', readOnly: 'Stratégie partagée en lecture seule', invalidShipReference: 'Chaque marqueur doit utiliser un navire du catalogue du site. Les builds et guides restent facultatifs.', formations: { line: 'Ligne de bataille', circle: 'Cercle', oval: 'Ovale', wedge: 'Formation en coin', column: 'Colonne', box: 'Carré' },
  } },
  es: { strategyPlanner: {
    inspector: 'Inspector', inspectorHint: 'Abre solo las secciones necesarias mientras mantienes visible el mapa.', briefing: 'Informe y mapa', selectedObject: 'Objeto seleccionado', transform: 'Tamaño y rotación', transformHint: 'Transformar el objeto seleccionado', sharing: 'Uso compartido y acceso', sharingHint: 'Publicación y enlace compartido', commandDeck: 'Panel de mando', history: 'Historial de edición', drawingTools: 'Dibujar y seleccionar', formationsLabel: 'Formaciones', annotations: 'Anotaciones',
    title: 'Planificador de estrategia', tools: 'Herramientas', showTools: 'Mostrar herramientas', hideTools: 'Ocultar herramientas', legend: 'Leyenda estratégica', create: 'Nueva estrategia', descriptionLabel: 'Notas informativas', objects: 'Capa de dibujo', line: 'Línea', arrow: 'Flecha', select: 'Seleccionar', playerName: 'Nombre del jugador (opcional)', build: 'Build del sitio (opcional)', guide: 'Guía del sitio (opcional)', addText: 'Añadir texto', creationColor: 'Color del objeto nuevo', textColor: 'Color del texto', rotation: 'Rotación', scale: 'Escala', undo: 'Deshacer', redo: 'Rehacer', publish: 'Publicar enlace para compartir', unpublish: 'Desactivar enlace compartido', copyLink: 'Copiar enlace', copied: 'Enlace copiado.', private: 'Privada', published: 'Publicada', print: 'Imprimir / guardar como PDF', downloadSvg: 'Descargar SVG', view: 'Ver', edit: 'Editar', readOnly: 'Estrategia compartida de solo lectura', invalidShipReference: 'Cada marcador debe usar un barco del catálogo web. Los builds y las guías siguen siendo opcionales.', formations: { line: 'Línea de batalla', circle: 'Círculo', oval: 'Óvalo', wedge: 'Cuña', column: 'Columna', box: 'Cuadro' },
  } },
  pt: { strategyPlanner: {
    inspector: 'Inspetor', inspectorHint: 'Abra apenas as secções necessárias mantendo o mapa visível.', briefing: 'Briefing e mapa', selectedObject: 'Objeto selecionado', transform: 'Tamanho e rotação', transformHint: 'Transformar o objeto selecionado', sharing: 'Partilha e acesso', sharingHint: 'Publicação e ligação de partilha', commandDeck: 'Painel de comando', history: 'Histórico de edição', drawingTools: 'Desenhar e selecionar', formationsLabel: 'Formações', annotations: 'Anotações',
    title: 'Planeador de estratégia', tools: 'Ferramentas', showTools: 'Mostrar ferramentas', hideTools: 'Ocultar ferramentas', legend: 'Legenda estratégica', create: 'Nova estratégia', descriptionLabel: 'Notas de briefing', objects: 'Camada de desenho', line: 'Linha', arrow: 'Seta', select: 'Selecionar', playerName: 'Nome do jogador (opcional)', build: 'Build do site (opcional)', guide: 'Guia do site (opcional)', addText: 'Adicionar texto', creationColor: 'Cor do novo objeto', textColor: 'Cor do texto', rotation: 'Rotação', scale: 'Escala', undo: 'Desfazer', redo: 'Refazer', publish: 'Publicar ligação de partilha', unpublish: 'Desativar ligação de partilha', copyLink: 'Copiar ligação', copied: 'Ligação copiada.', private: 'Privada', published: 'Publicada', print: 'Imprimir / guardar como PDF', downloadSvg: 'Transferir SVG', view: 'Ver', edit: 'Editar', readOnly: 'Estratégia partilhada só de leitura', invalidShipReference: 'Cada marcador deve usar um navio do catálogo do site. Builds e guias continuam opcionais.', formations: { line: 'Linha de batalha', circle: 'Círculo', oval: 'Elipse', wedge: 'Cunha', column: 'Coluna', box: 'Quadrado' },
  } },
  ru: { strategyPlanner: {
    inspector: 'Инспектор', inspectorHint: 'Открывайте только нужные разделы, сохраняя карту в поле зрения.', briefing: 'Брифинг и карта', selectedObject: 'Выбранный объект', transform: 'Размер и поворот', transformHint: 'Преобразовать выбранный объект', sharing: 'Общий доступ', sharingHint: 'Публикация и ссылка доступа', commandDeck: 'Командная панель', history: 'История изменений', drawingTools: 'Рисование и выбор', formationsLabel: 'Формации', annotations: 'Аннотации',
    title: 'Планировщик стратегии', tools: 'Инструменты', showTools: 'Показать инструменты', hideTools: 'Скрыть инструменты', legend: 'Стратегическая легенда', create: 'Новая стратегия', descriptionLabel: 'Заметки к брифингу', objects: 'Слой разметки', line: 'Линия', arrow: 'Стрелка', select: 'Выбрать', playerName: 'Имя игрока (необязательно)', build: 'Билд с сайта (необязательно)', guide: 'Руководство с сайта (необязательно)', addText: 'Добавить текст', creationColor: 'Цвет нового объекта', textColor: 'Цвет текста', rotation: 'Поворот', scale: 'Масштаб', undo: 'Отменить', redo: 'Повторить', publish: 'Опубликовать ссылку', unpublish: 'Отключить ссылку', copyLink: 'Копировать ссылку', copied: 'Ссылка скопирована.', private: 'Личная', published: 'Опубликована', print: 'Печать / сохранить PDF', downloadSvg: 'Скачать SVG', view: 'Просмотр', edit: 'Изменить', readOnly: 'Общая стратегия только для чтения', invalidShipReference: 'Каждая метка должна использовать корабль из каталога сайта. Билды и руководства остаются необязательными.', formations: { line: 'Линия боя', circle: 'Круг', oval: 'Овал', wedge: 'Клин', column: 'Колонна', box: 'Каре' },
  } },
  cn: { strategyPlanner: {
    inspector: '检查器', inspectorHint: '只展开当前需要的区域，同时保持地图可见。', briefing: '简报与地图', selectedObject: '已选对象', transform: '大小与旋转', transformHint: '变换已选对象', sharing: '共享与访问', sharingHint: '发布状态与共享链接', commandDeck: '指挥面板', history: '编辑历史', drawingTools: '绘制与选择', formationsLabel: '编队', annotations: '标注',
    title: '战略规划器', tools: '工具', showTools: '显示工具', hideTools: '隐藏工具', legend: '战略图例', create: '新建战略', descriptionLabel: '简报备注', objects: '绘图图层', line: '直线', arrow: '箭头', select: '选择', playerName: '玩家名称（可选）', build: '站内配装（可选）', guide: '站内指南（可选）', addText: '添加文字', creationColor: '新对象颜色', textColor: '文字颜色', rotation: '旋转', scale: '缩放', undo: '撤销', redo: '重做', publish: '发布分享链接', unpublish: '停用分享链接', copyLink: '复制分享链接', copied: '分享链接已复制。', private: '私有', published: '已发布', print: '打印 / 保存为 PDF', downloadSvg: '下载 SVG', view: '查看', edit: '编辑', readOnly: '共享的只读战略', invalidShipReference: '每个舰船标记都必须使用网站目录中的舰船。配装和指南仍为可选项。', formations: { line: '战列线', circle: '圆形', oval: '椭圆形', wedge: '楔形', column: '纵队', box: '方阵' },
  } },
}
