// Generated from spring-api/src/main/reference/webhook-events.json; do not edit manually.
package eu.royalblackwater.api.webhooks.service;

import eu.royalblackwater.api.webhooks.dto.WebhookEventDefinition;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

public final class WebhookEventCatalog {
    public static final List<WebhookEventDefinition> ALL = List.of(
            new WebhookEventDefinition("🧪 **Manual connectivity and payload test**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "Manual connectivity and payload test.", "integration", "integration.test"),
            new WebhookEventDefinition("🛠️ **A controlled server operation was requested and queued**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A controlled server operation was requested and queued.", "system", "system.update.started"),
            new WebhookEventDefinition("🛠️ **A controlled server operation completed or failed**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A controlled server operation completed or failed.", "system", "system.update.result"),
            new WebhookEventDefinition("🛠️ **A maintenance window was activated**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A maintenance window was activated.", "system", "system.maintenance.started"),
            new WebhookEventDefinition("🛠️ **A maintenance window ended or failed**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A maintenance window ended or failed.", "system", "system.maintenance.ended"),
            new WebhookEventDefinition("💾 **An administrator requested a protected application backup**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "An administrator requested a protected application backup.", "operations", "backup.run.requested"),
            new WebhookEventDefinition("💾 **A bootstrap administrator requested a database restore**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A bootstrap administrator requested a database restore.", "operations", "backup.restore.requested"),
            new WebhookEventDefinition("💾 **The protected backup connection configuration changed**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "The protected backup connection configuration changed.", "operations", "backup.configuration.updated"),
            new WebhookEventDefinition("💾 **The protected backup connection configuration was removed**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "The protected backup connection configuration was removed.", "operations", "backup.configuration.deleted"),
            new WebhookEventDefinition("🛡️ **A data-subject request requires an administrator response**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A data-subject request requires an administrator response.", "moderation", "privacy.request.created"),
            new WebhookEventDefinition("🛡️ **A data-subject request was resolved by an administrator**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A data-subject request was resolved by an administrator.", "moderation", "privacy.request.resolved"),
            new WebhookEventDefinition("🔔 **A new access request was submitted**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A new access request was submitted.", "registrations", "registration.request.created"),
            new WebhookEventDefinition("🔔 **An access request was approved**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "An access request was approved.", "registrations", "registration.request.approved"),
            new WebhookEventDefinition("🔔 **An access request was rejected**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "An access request was rejected.", "registrations", "registration.request.rejected"),
            new WebhookEventDefinition("⚓ **A squad was created**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A squad was created.", "squads", "squad.created"),
            new WebhookEventDefinition("⚓ **A squad was updated**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A squad was updated.", "squads", "squad.updated"),
            new WebhookEventDefinition("⚓ **A squad was archived**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A squad was archived.", "squads", "squad.archived"),
            new WebhookEventDefinition("⚓ **A member was added to a squad**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A member was added to a squad.", "squads", "squad.member.added"),
            new WebhookEventDefinition("⚓ **A squad membership was updated**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A squad membership was updated.", "squads", "squad.member.updated"),
            new WebhookEventDefinition("⚓ **A member was removed from a squad**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A member was removed from a squad.", "squads", "squad.member.removed"),
            new WebhookEventDefinition("🔎 **A new group-search listing was created**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A new group-search listing was created.", "groups", "group.created"),
            new WebhookEventDefinition("🔎 **A member joined a group-search listing**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A member joined a group-search listing.", "groups", "group.member.joined"),
            new WebhookEventDefinition("🔎 **A group-search listing was closed**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A group-search listing was closed.", "groups", "group.closed"),
            new WebhookEventDefinition("📅 **A fleet or squad event was created**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A fleet or squad event was created.", "calendar", "calendar.event.created"),
            new WebhookEventDefinition("📅 **A fleet or squad event was updated**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A fleet or squad event was updated.", "calendar", "calendar.event.updated"),
            new WebhookEventDefinition("📅 **A fleet or squad event was cancelled**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A fleet or squad event was cancelled.", "calendar", "calendar.event.cancelled"),
            new WebhookEventDefinition("📘 **A new guide was published**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A new guide was published.", "content", "guide.created"),
            new WebhookEventDefinition("📘 **A published guide was updated**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A published guide was updated.", "content", "guide.updated"),
            new WebhookEventDefinition("📘 **A guide was removed from publication**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A guide was removed from publication.", "content", "guide.removed"),
            new WebhookEventDefinition("📘 **The starter guide was updated**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "The starter guide was updated.", "content", "newcomer_guide.updated"),
            new WebhookEventDefinition("🧰 **A new build was created**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A new build was created.", "builds", "build.created"),
            new WebhookEventDefinition("🧰 **A build was updated**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A build was updated.", "builds", "build.updated"),
            new WebhookEventDefinition("🧰 **A build was removed**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A build was removed.", "builds", "build.removed"),
            new WebhookEventDefinition("🧰 **A public build printout was published to Discord**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A public build printout was published to Discord.", "builds", "build.printout.published"),
            new WebhookEventDefinition("💬 **A new forum thread was created**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A new forum thread was created.", "forum", "forum.thread.created"),
            new WebhookEventDefinition("💬 **A forum thread was updated**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A forum thread was updated.", "forum", "forum.thread.updated"),
            new WebhookEventDefinition("💬 **A forum thread was removed**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A forum thread was removed.", "forum", "forum.thread.removed"),
            new WebhookEventDefinition("💬 **A new forum reply was posted**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A new forum reply was posted.", "forum", "forum.post.created"),
            new WebhookEventDefinition("💬 **A forum reply was updated**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A forum reply was updated.", "forum", "forum.post.updated"),
            new WebhookEventDefinition("💬 **A forum reply was removed**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A forum reply was removed.", "forum", "forum.post.removed"),
            new WebhookEventDefinition("🏴‍☠️ **A fleet was created**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A fleet was created.", "fleet", "fleet.created"),
            new WebhookEventDefinition("🏴‍☠️ **A fleet profile was updated**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A fleet profile was updated.", "fleet", "fleet.updated"),
            new WebhookEventDefinition("🏴‍☠️ **A fleet application was submitted**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A fleet application was submitted.", "fleet", "fleet.application.created"),
            new WebhookEventDefinition("🏴‍☠️ **A fleet membership was updated**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A fleet membership was updated.", "fleet", "fleet.membership.updated"),
            new WebhookEventDefinition("🏴‍☠️ **A fleet leadership role was assigned**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A fleet leadership role was assigned.", "fleet", "fleet.leader.assigned"),
            new WebhookEventDefinition("🏴‍☠️ **A fleet role was created**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A fleet role was created.", "fleet", "fleet.role.created"),
            new WebhookEventDefinition("🏴‍☠️ **A fleet role was updated**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A fleet role was updated.", "fleet", "fleet.role.updated"),
            new WebhookEventDefinition("🏴‍☠️ **A fleet role was removed**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A fleet role was removed.", "fleet", "fleet.role.removed"),
            new WebhookEventDefinition("📦 **Warehouse stock changed**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "Guild warehouse stock was created, changed, or removed.", "warehouse", "warehouse.stock.changed"),
            new WebhookEventDefinition("🔒 **Warehouse reservation changed**\n\n{data.summary}\n\nResource: `{resource.type} #{resource.id}`\nEvent: `{event}`\nTriggered by **{actor.display_name}** at `{occurred_at}`.", "A guild warehouse reservation changed.", "warehouse", "warehouse.reservation.changed"),
            new WebhookEventDefinition("📊 **Guild warehouse stock overview**\n\n{data.summary}\n\nEvent: `{event}`\nUpdated at `{occurred_at}`.", "The complete current warehouse stock overview for a fleet.", "warehouse", "warehouse.stock.overview")
    );
    public static final Set<String> TYPES = ALL.stream().map(WebhookEventDefinition::key)
            .collect(Collectors.toUnmodifiableSet());

    public static WebhookEventDefinition required(String key) {
        return ALL.stream().filter(event -> event.key().equals(key)).findFirst()
                .orElseThrow(() -> new IllegalArgumentException("Unknown webhook event: " + key));
    }

    private WebhookEventCatalog() { }
}
