from __future__ import annotations

from copy import deepcopy
from typing import Any

from app.modules.admin.services.webhook_event_samples_forum_fleet import forum_and_fleet_samples
from app.modules.admin.services.webhook_event_samples_maintenance import maintenance_samples

_COMMON_USER = {
    "id": 42,
    "username": "test-captain",
    "display_name": "Test Captain",
    "role": "user",
}
_COMMON_SCOPE = {
    "scope_type": "fleet",
    "scope_id": 1,
    "fleet_id": 1,
    "squad_id": None,
}
_COMMON_EVENT = {
    **_COMMON_SCOPE,
    "resource_type": "integration",
    "resource_id": 1,
    "resource_url": "/admin/discord-webhooks",
    "data": {},
}

EVENT_TEST_SAMPLES: dict[str, dict[str, Any]] = {
    "backup.configuration.deleted": {
        **_COMMON_EVENT,
        "scope_type": "global",
        "scope_id": None,
        "fleet_id": None,
        "resource_type": "backup_connection",
        "resource_id": "remote",
        "resource_url": "/admin?tab=database-backups",
        "data": {},
    },
    "backup.configuration.updated": {
        **_COMMON_EVENT,
        "scope_type": "global",
        "scope_id": None,
        "fleet_id": None,
        "resource_type": "backup_connection",
        "resource_id": "remote",
        "resource_url": "/admin?tab=database-backups",
        "data": {"action": "updated"},
    },
    "backup.restore.requested": {
        **_COMMON_EVENT,
        "scope_type": "global",
        "scope_id": None,
        "fleet_id": None,
        "resource_type": "database_backup",
        "resource_id": "backup-20260815",
        "resource_url": "/admin?tab=database-backups",
        "data": {"backup_id": "backup-20260815"},
    },
    "backup.run.requested": {
        **_COMMON_EVENT,
        "scope_type": "global",
        "scope_id": None,
        "fleet_id": None,
        "resource_type": "database_backup",
        "resource_id": "remote",
        "resource_url": "/admin?tab=database-backups",
        "data": {},
    },
    "privacy.request.created": {
        **_COMMON_EVENT,
        "scope_type": "global",
        "scope_id": None,
        "fleet_id": None,
        "resource_type": "privacy_request",
        "resource_id": 301,
        "resource_url": "/admin?tab=privacy-requests",
        "data": {"id": 301, "request_type": "erasure"},
    },
    "privacy.request.resolved": {
        **_COMMON_EVENT,
        "scope_type": "global",
        "scope_id": None,
        "fleet_id": None,
        "resource_type": "privacy_request",
        "resource_id": 301,
        "resource_url": "/admin?tab=privacy-requests",
        "data": {"id": 301, "request_type": "erasure", "decision": "completed"},
    },
    "system.update.started": {
        **_COMMON_EVENT,
        "scope_type": "global",
        "scope_id": None,
        "fleet_id": None,
        "resource_type": "system_update",
        "resource_id": "2026-08-15T12:00:00+00:00",
        "resource_url": "/admin?section=status",
        "data": {
            "state": "queued",
            "operation": "update_migrate",
            "requested_by": "admin",
            "requested_at": "2026-08-15T12:00:00+00:00",
            "message": "Update request accepted and waiting for the host runner.",
        },
    },
    "system.update.result": {
        **_COMMON_EVENT,
        "scope_type": "global",
        "scope_id": None,
        "fleet_id": None,
        "resource_type": "system_update",
        "resource_id": "2026-08-15T12:00:10+00:00",
        "resource_url": "/admin?section=status",
        "data": {
            "state": "succeeded",
            "operation": "update_migrate",
            "requested_by": "admin",
            "requested_at": "2026-08-15T12:00:00+00:00",
            "started_at": "2026-08-15T12:00:10+00:00",
            "finished_at": "2026-08-15T12:04:30+00:00",
            "commit_before": "1111111",
            "commit_after": "2222222",
            "message": "Server update completed successfully.",
        },
    },
    "integration.test": {
        **_COMMON_EVENT,
        "data": {
            "message": "Royal Blackwater Fleet webhook test delivery.",
            "webhook_name": "RBF Test Webhook",
        },
    },
    "registration.request.created": {
        **_COMMON_EVENT,
        "resource_type": "registration_request",
        "resource_id": 101,
        "resource_url": "/admin?tab=registrations",
        "data": {
            "id": 101,
            "username": "new-captain",
            "display_name": "New Captain",
            "wants_fleet_membership": True,
            "fleet_id": 1,
            "fleet_application_note": "Existing fleet member requesting account access.",
        },
    },
    "registration.request.approved": {
        **_COMMON_EVENT,
        "resource_type": "registration_request",
        "resource_id": 101,
        "resource_url": "/admin?tab=registrations",
        "data": {
            "id": 101,
            "username": "new-captain",
            "display_name": "New Captain",
            "wants_fleet_membership": True,
            "decision_note": "Identity confirmed.",
        },
    },
    "registration.request.rejected": {
        **_COMMON_EVENT,
        "resource_type": "registration_request",
        "resource_id": 102,
        "resource_url": "/admin?tab=registrations",
        "data": {
            "id": 102,
            "username": "declined-captain",
            "display_name": "Declined Captain",
            "decision_note": "Additional verification required.",
        },
    },
    "squad.created": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "squad",
        "resource_id": 7,
        "resource_url": "/squads/7",
        "data": {"id": 7, "name": "Vanguard", "slug": "vanguard", "fleet_id": 1, "member_count": 4},
    },
    "squad.updated": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "squad",
        "resource_id": 7,
        "resource_url": "/squads/7",
        "data": {"id": 7, "name": "Vanguard", "slug": "vanguard", "fleet_id": 1, "member_count": 5},
    },
    "squad.archived": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "squad",
        "resource_id": 7,
        "resource_url": "/squads/7",
        "data": {"id": 7, "name": "Vanguard", "slug": "vanguard", "fleet_id": 1, "member_count": 5},
    },
    "squad.member.added": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "squad",
        "resource_id": 7,
        "resource_url": "/squads/7",
        "data": {
            "id": 7,
            "name": "Vanguard",
            "squad_name": "Vanguard",
            "fleet_id": 1,
            "member_display_name": "New Sailor",
            "member_role": "member",
        },
    },
    "squad.member.updated": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "squad",
        "resource_id": 7,
        "resource_url": "/squads/7",
        "data": {"id": 7, "squad_name": "Vanguard", "fleet_id": 1, "member_id": 88},
    },
    "squad.member.removed": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "squad",
        "resource_id": 7,
        "resource_url": "/squads/7",
        "data": {"id": 7, "squad_name": "Vanguard", "fleet_id": 1, "member_id": 88},
    },
    "group.created": {
        **_COMMON_EVENT,
        "resource_type": "group",
        "resource_id": 901,
        "resource_url": "/groups/901",
        "data": {
            "id": 901,
            "title": "Evening PvP group",
            "focus": "pvp_open_world",
            "status": "open",
            "max_members": 8,
            "active_members_count": 0,
            "spots_left": 8,
            "min_ship_rate": 5,
            "max_ship_rate": 2,
            "allow_guests": True,
            "fleet_restriction": None,
            "scheduled_start_at": "2026-08-15T19:00:00+00:00",
            "scheduled_end_at": "2026-08-15T21:00:00+00:00",
            "expires_at": "2026-08-16T12:00:00+00:00",
            "owner": {"id": 42, "display_name": "Test Captain"},
        },
    },
    "group.member.joined": {
        **_COMMON_EVENT,
        "resource_type": "group",
        "resource_id": 901,
        "resource_url": "/groups/901",
        "data": {
            "id": 901,
            "title": "Evening PvP group",
            "focus": "pvp_open_world",
            "status": "open",
            "max_members": 8,
            "active_members_count": 3,
            "spots_left": 5,
            "min_ship_rate": 5,
            "max_ship_rate": 2,
            "allow_guests": True,
            "fleet_restriction": None,
            "scheduled_start_at": "2026-08-15T19:00:00+00:00",
            "scheduled_end_at": "2026-08-15T21:00:00+00:00",
            "expires_at": "2026-08-16T12:00:00+00:00",
            "owner": {"id": 42, "display_name": "Test Captain"},
            "member": {
                "id": 77,
                "display_name": "Joining Captain",
                "fleet_name": "Royal Blackwater Fleet",
                "ship_name": "De Zeven Provincien",
                "ship_rate": 3,
                "is_guest": False,
            },
        },
    },
    "group.closed": {
        **_COMMON_EVENT,
        "resource_type": "group",
        "resource_id": 901,
        "resource_url": "/groups/901",
        "data": {
            "id": 901,
            "title": "Evening PvP group",
            "focus": "pvp_open_world",
            "status": "closed",
            "max_members": 8,
            "active_members_count": 6,
            "spots_left": 2,
            "min_ship_rate": 5,
            "max_ship_rate": 2,
            "allow_guests": True,
            "fleet_restriction": None,
            "scheduled_start_at": "2026-08-15T19:00:00+00:00",
            "scheduled_end_at": "2026-08-15T21:00:00+00:00",
            "expires_at": "2026-08-16T12:00:00+00:00",
            "owner": {"id": 42, "display_name": "Test Captain"},
        },
    },
    "calendar.event.created": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "calendar_event",
        "resource_id": 201,
        "resource_url": "/calendar?date=2026-08-15&event=201",
        "data": {
            "id": 201,
            "title": "Port Battle",
            "category": "operation",
            "description": "Fleet deployment and briefing.",
            "location": "Nassau",
            "start_at": "2026-08-15T18:00:00+00:00",
            "end_at": "2026-08-15T20:00:00+00:00",
            "all_day": False,
            "owner": _COMMON_USER,
            "squad_id": 7,
            "scope_type": "squad",
            "scope_name": "Vanguard",
            "squad": {"id": 7, "name": "Vanguard", "slug": "vanguard"},
        },
    },
    "calendar.event.updated": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "calendar_event",
        "resource_id": 201,
        "resource_url": "/calendar?date=2026-08-15&event=201",
        "data": {
            "id": 201,
            "title": "Port Battle Briefing",
            "category": "operation",
            "description": "Updated fleet deployment plan.",
            "location": "Nassau",
            "start_at": "2026-08-15T18:30:00+00:00",
            "end_at": "2026-08-15T20:30:00+00:00",
            "all_day": False,
            "owner": _COMMON_USER,
            "squad_id": 7,
            "scope_type": "squad",
            "scope_name": "Vanguard",
            "squad": {"id": 7, "name": "Vanguard", "slug": "vanguard"},
        },
    },
    "calendar.event.cancelled": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "calendar_event",
        "resource_id": 201,
        "resource_url": "/calendar?date=2026-08-15&event=201",
        "data": {
            "id": 201,
            "title": "Port Battle Briefing",
            "category": "operation",
            "location": "Nassau",
            "start_at": "2026-08-15T18:30:00+00:00",
            "end_at": "2026-08-15T20:30:00+00:00",
            "squad_id": 7,
            "scope_type": "squad",
            "scope_name": "Vanguard",
            "squad": {"id": 7, "name": "Vanguard", "slug": "vanguard"},
        },
    },
    "guide.created": {
        **_COMMON_EVENT,
        "resource_type": "guide",
        "resource_id": 301,
        "resource_url": "/guides/301",
        "data": {
            "id": 301,
            "title": "Gunnery Fundamentals",
            "category": "combat",
            "summary": "Core aiming, range and ammunition guidance.",
            "owner": _COMMON_USER,
            "attachment_count": 2,
            "build_reference_count": 1,
            "created_at": "2026-08-15T12:00:00+00:00",
            "updated_at": "2026-08-15T12:00:00+00:00",
        },
    },
    "guide.updated": {
        **_COMMON_EVENT,
        "resource_type": "guide",
        "resource_id": 301,
        "resource_url": "/guides/301",
        "data": {
            "id": 301,
            "title": "Gunnery Fundamentals",
            "category": "combat",
            "summary": "Expanded aiming, range and ammunition guidance.",
            "owner": _COMMON_USER,
            "attachment_count": 3,
            "build_reference_count": 2,
            "created_at": "2026-08-15T12:00:00+00:00",
            "updated_at": "2026-08-16T12:00:00+00:00",
        },
    },
    "guide.removed": {
        **_COMMON_EVENT,
        "resource_type": "guide",
        "resource_id": 301,
        "resource_url": "/guides",
        "data": {"id": 301, "title": "Gunnery Fundamentals"},
    },
    "newcomer_guide.updated": {
        **_COMMON_EVENT,
        "resource_type": "newcomer_guide",
        "resource_id": 1,
        "resource_url": "/newcomer-guide",
        "data": {
            "id": 1,
            "title": "Welcome aboard",
            "updated_by": "Test Captain",
            "updated_at": "2026-08-16T12:00:00+00:00",
        },
    },
    "build.created": {
        **_COMMON_EVENT,
        "resource_type": "build",
        "resource_id": 401,
        "resource_url": "/builds/401",
        "data": {
            "id": 401,
            "build_name": "Heavy Broadside",
            "build_type": "balanced",
            "ship": {"id": 12, "name": "Anson", "rate": 3},
            "is_official_template": False,
            "sailors": 80,
            "soldiers": 80,
            "musketeers": 0,
            "mercenaries": 0,
            "owner_id": 42,
            "created_at": "2026-08-15T12:00:00+00:00",
            "updated_at": "2026-08-15T12:00:00+00:00",
        },
    },
    "build.updated": {
        **_COMMON_EVENT,
        "resource_type": "build",
        "resource_id": 401,
        "resource_url": "/builds/401",
        "data": {
            "id": 401,
            "build_name": "Heavy Broadside Mk II",
            "build_type": "balanced",
            "ship": {"id": 12, "name": "Anson", "rate": 3},
            "is_official_template": False,
            "sailors": 90,
            "soldiers": 70,
            "musketeers": 0,
            "mercenaries": 0,
            "owner_id": 42,
            "created_at": "2026-08-15T12:00:00+00:00",
            "updated_at": "2026-08-16T12:00:00+00:00",
        },
    },
    "build.removed": {
        **_COMMON_EVENT,
        "resource_type": "build",
        "resource_id": 401,
        "resource_url": "/builds",
        "data": {"id": 401, "build_name": "Heavy Broadside Mk II"},
    },
    "forum.thread.created": {
        **_COMMON_EVENT,
        "resource_type": "forum_thread",
        "resource_id": 501,
        "resource_url": "/forum/501",
        "data": {
            "id": 501,
            "title": "Fleet formation questions",
            "category": "training",
            "owner": _COMMON_USER,
            "reply_count": 0,
            "created_at": "2026-08-15T12:00:00+00:00",
            "updated_at": "2026-08-15T12:00:00+00:00",
            "last_activity_at": "2026-08-15T12:00:00+00:00",
        },
    },
    "forum.thread.updated": {
        **_COMMON_EVENT,
        "resource_type": "forum_thread",
        "resource_id": 501,
        "resource_url": "/forum/501",
        "data": {
            "id": 501,
            "title": "Fleet formation questions and answers",
            "category": "training",
            "owner": _COMMON_USER,
            "reply_count": 3,
            "created_at": "2026-08-15T12:00:00+00:00",
            "updated_at": "2026-08-16T12:00:00+00:00",
            "last_activity_at": "2026-08-16T12:00:00+00:00",
        },
    },
}


EVENT_TEST_SAMPLES.update(forum_and_fleet_samples(_COMMON_EVENT, _COMMON_USER))
EVENT_TEST_SAMPLES.update(maintenance_samples(_COMMON_EVENT))


def event_test_sample(event_type: str) -> dict[str, Any]:
    return deepcopy(EVENT_TEST_SAMPLES.get(event_type, EVENT_TEST_SAMPLES["integration.test"]))
