from __future__ import annotations

EVENT_CATALOG = (
    ("integration.test", "integration", "Manual connectivity and payload test."),
    ("system.update.started", "system", "A controlled server update was requested and queued."),
    ("system.update.result", "system", "A controlled server update completed or failed."),
    ("registration.request.created", "registrations", "A new access request was submitted."),
    ("registration.request.approved", "registrations", "An access request was approved."),
    ("registration.request.rejected", "registrations", "An access request was rejected."),
    ("squad.created", "squads", "A squad was created."),
    ("squad.updated", "squads", "A squad was updated."),
    ("squad.archived", "squads", "A squad was archived."),
    ("squad.member.added", "squads", "A member was added to a squad."),
    ("squad.member.updated", "squads", "A squad membership was updated."),
    ("squad.member.removed", "squads", "A member was removed from a squad."),
    ("group.created", "groups", "A new group-search listing was created."),
    ("group.member.joined", "groups", "A member joined a group-search listing."),
    ("group.closed", "groups", "A group-search listing was closed."),
    ("calendar.event.created", "calendar", "A fleet or squad event was created."),
    ("calendar.event.updated", "calendar", "A fleet or squad event was updated."),
    ("calendar.event.cancelled", "calendar", "A fleet or squad event was cancelled."),
    ("guide.created", "content", "A new guide was published."),
    ("guide.updated", "content", "A published guide was updated."),
    ("guide.removed", "content", "A guide was removed from publication."),
    ("newcomer_guide.updated", "content", "The starter guide was updated."),
    ("build.created", "builds", "A new build was created."),
    ("build.updated", "builds", "A build was updated."),
    ("build.removed", "builds", "A build was removed."),
    ("forum.thread.created", "forum", "A new forum thread was created."),
    ("forum.thread.updated", "forum", "A forum thread was updated."),
    ("forum.thread.removed", "forum", "A forum thread was removed."),
    ("forum.post.created", "forum", "A new forum reply was posted."),
    ("forum.post.updated", "forum", "A forum reply was updated."),
    ("forum.post.removed", "forum", "A forum reply was removed."),
    ("fleet.created", "fleet", "A fleet was created."),
    ("fleet.updated", "fleet", "A fleet profile was updated."),
    ("fleet.application.created", "fleet", "A fleet application was submitted."),
    ("fleet.membership.updated", "fleet", "A fleet membership was updated."),
    ("fleet.leader.assigned", "fleet", "A fleet leadership role was assigned."),
    ("fleet.role.created", "fleet", "A fleet role was created."),
    ("fleet.role.updated", "fleet", "A fleet role was updated."),
    ("fleet.role.removed", "fleet", "A fleet role was removed."),
)
EVENT_TYPES = {row[0] for row in EVENT_CATALOG}
