from __future__ import annotations

from copy import deepcopy
from typing import Any

from app.modules.admin.services.webhook_message_templates import DEFAULT_MESSAGES

EVENT_CATALOG = (
    ("integration.test", "integration", "Manual connectivity and payload test."),
    ("registration.request.created", "registrations", "A new access request was submitted."),
    ("registration.request.approved", "registrations", "An access request was approved."),
    ("registration.request.rejected", "registrations", "An access request was rejected."),
    ("squad.created", "squads", "A squad was created."),
    ("squad.updated", "squads", "A squad was updated."),
    ("squad.archived", "squads", "A squad was archived."),
    ("squad.member.added", "squads", "A member was added to a squad."),
    ("squad.member.updated", "squads", "A squad membership was updated."),
    ("squad.member.removed", "squads", "A member was removed from a squad."),
    ("calendar.event.created", "calendar", "A fleet or squad event was created."),
    ("calendar.event.updated", "calendar", "A fleet or squad event was updated."),
    ("calendar.event.cancelled", "calendar", "A fleet or squad event was cancelled."),
    ("guide.created", "content", "A new guide was published."),
    ("guide.updated", "content", "A published guide was updated."),
    ("guide.removed", "content", "A guide was removed from publication."),
    ("newcomer_guide.updated", "content", "The starter guide was updated."),
    ("build.created", "builds", "A new build was created."),
    ("build.updated", "builds", "A build was updated."),
    ("build.removed", "builds", "A build was removed."),
    ("forum.thread.created", "forum", "A new forum thread was created."),
    ("forum.thread.updated", "forum", "A forum thread was updated."),
)
EVENT_TYPES = {row[0] for row in EVENT_CATALOG}


_COMMON_USER = {
    "id": 42,
    "username": "test-captain",
    "display_name": "Test Captain",
    "role": "user",
}
_COMMON_SCOPE = {
    "scope_type": "fleet",
    "scope_id": 1,
    "fleet_id": 1,
    "squad_id": None,
}
_COMMON_EVENT = {
    **_COMMON_SCOPE,
    "resource_type": "integration",
    "resource_id": 1,
    "resource_url": "/admin/discord-webhooks",
    "data": {},
}

EVENT_TEST_SAMPLES: dict[str, dict[str, Any]] = {
    "integration.test": {
        **_COMMON_EVENT,
        "data": {
            "message": "Royal Blackwater Fleet webhook test delivery.",
            "webhook_name": "RBF Test Webhook",
        },
    },
    "registration.request.created": {
        **_COMMON_EVENT,
        "resource_type": "registration_request",
        "resource_id": 101,
        "resource_url": "/admin?tab=registrations",
        "data": {
            "id": 101,
            "username": "new-captain",
            "display_name": "New Captain",
            "wants_fleet_membership": True,
            "fleet_id": 1,
            "fleet_application_note": "Existing fleet member requesting account access.",
        },
    },
    "registration.request.approved": {
        **_COMMON_EVENT,
        "resource_type": "registration_request",
        "resource_id": 101,
        "resource_url": "/admin?tab=registrations",
        "data": {
            "id": 101,
            "username": "new-captain",
            "display_name": "New Captain",
            "wants_fleet_membership": True,
            "decision_note": "Identity confirmed.",
        },
    },
    "registration.request.rejected": {
        **_COMMON_EVENT,
        "resource_type": "registration_request",
        "resource_id": 102,
        "resource_url": "/admin?tab=registrations",
        "data": {
            "id": 102,
            "username": "declined-captain",
            "display_name": "Declined Captain",
            "decision_note": "Additional verification required.",
        },
    },
    "squad.created": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "squad",
        "resource_id": 7,
        "resource_url": "/squads/7",
        "data": {"id": 7, "name": "Vanguard", "slug": "vanguard", "fleet_id": 1, "member_count": 4},
    },
    "squad.updated": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "squad",
        "resource_id": 7,
        "resource_url": "/squads/7",
        "data": {"id": 7, "name": "Vanguard", "slug": "vanguard", "fleet_id": 1, "member_count": 5},
    },
    "squad.archived": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "squad",
        "resource_id": 7,
        "resource_url": "/squads/7",
        "data": {"id": 7, "name": "Vanguard", "slug": "vanguard", "fleet_id": 1, "member_count": 5},
    },
    "squad.member.added": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "squad",
        "resource_id": 7,
        "resource_url": "/squads/7",
        "data": {
            "id": 7,
            "name": "Vanguard",
            "squad_name": "Vanguard",
            "fleet_id": 1,
            "member_display_name": "New Sailor",
            "member_role": "member",
        },
    },
    "squad.member.updated": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "squad",
        "resource_id": 7,
        "resource_url": "/squads/7",
        "data": {"id": 7, "squad_name": "Vanguard", "fleet_id": 1, "member_id": 88},
    },
    "squad.member.removed": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "squad",
        "resource_id": 7,
        "resource_url": "/squads/7",
        "data": {"id": 7, "squad_name": "Vanguard", "fleet_id": 1, "member_id": 88},
    },
    "calendar.event.created": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "calendar_event",
        "resource_id": 201,
        "resource_url": "/calendar?date=2026-08-15&event=201",
        "data": {
            "id": 201,
            "title": "Port Battle",
            "category": "operation",
            "description": "Fleet deployment and briefing.",
            "location": "Nassau",
            "start_at": "2026-08-15T18:00:00+00:00",
            "end_at": "2026-08-15T20:00:00+00:00",
            "all_day": False,
            "owner": _COMMON_USER,
            "squad_id": 7,
            "squad": {"id": 7, "name": "Vanguard", "slug": "vanguard"},
        },
    },
    "calendar.event.updated": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "calendar_event",
        "resource_id": 201,
        "resource_url": "/calendar?date=2026-08-15&event=201",
        "data": {
            "id": 201,
            "title": "Port Battle Briefing",
            "category": "operation",
            "description": "Updated fleet deployment plan.",
            "location": "Nassau",
            "start_at": "2026-08-15T18:30:00+00:00",
            "end_at": "2026-08-15T20:30:00+00:00",
            "all_day": False,
            "owner": _COMMON_USER,
            "squad_id": 7,
            "squad": {"id": 7, "name": "Vanguard", "slug": "vanguard"},
        },
    },
    "calendar.event.cancelled": {
        **_COMMON_EVENT,
        "scope_type": "squad",
        "scope_id": 7,
        "squad_id": 7,
        "resource_type": "calendar_event",
        "resource_id": 201,
        "resource_url": "/calendar?date=2026-08-15&event=201",
        "data": {
            "id": 201,
            "title": "Port Battle Briefing",
            "category": "operation",
            "location": "Nassau",
            "start_at": "2026-08-15T18:30:00+00:00",
            "end_at": "2026-08-15T20:30:00+00:00",
            "squad_id": 7,
            "squad": {"id": 7, "name": "Vanguard", "slug": "vanguard"},
        },
    },
    "guide.created": {
        **_COMMON_EVENT,
        "resource_type": "guide",
        "resource_id": 301,
        "resource_url": "/guides/301",
        "data": {
            "id": 301,
            "title": "Gunnery Fundamentals",
            "category": "combat",
            "summary": "Core aiming, range and ammunition guidance.",
            "owner": _COMMON_USER,
            "attachment_count": 2,
            "build_reference_count": 1,
            "created_at": "2026-08-15T12:00:00+00:00",
            "updated_at": "2026-08-15T12:00:00+00:00",
        },
    },
    "guide.updated": {
        **_COMMON_EVENT,
        "resource_type": "guide",
        "resource_id": 301,
        "resource_url": "/guides/301",
        "data": {
            "id": 301,
            "title": "Gunnery Fundamentals",
            "category": "combat",
            "summary": "Expanded aiming, range and ammunition guidance.",
            "owner": _COMMON_USER,
            "attachment_count": 3,
            "build_reference_count": 2,
            "created_at": "2026-08-15T12:00:00+00:00",
            "updated_at": "2026-08-16T12:00:00+00:00",
        },
    },
    "guide.removed": {
        **_COMMON_EVENT,
        "resource_type": "guide",
        "resource_id": 301,
        "resource_url": "/guides",
        "data": {"id": 301, "title": "Gunnery Fundamentals"},
    },
    "newcomer_guide.updated": {
        **_COMMON_EVENT,
        "resource_type": "newcomer_guide",
        "resource_id": 1,
        "resource_url": "/newcomer-guide",
        "data": {
            "id": 1,
            "title": "Welcome aboard",
            "updated_by": "Test Captain",
            "updated_at": "2026-08-16T12:00:00+00:00",
        },
    },
    "build.created": {
        **_COMMON_EVENT,
        "resource_type": "build",
        "resource_id": 401,
        "resource_url": "/builds/401",
        "data": {
            "id": 401,
            "build_name": "Heavy Broadside",
            "build_type": "balanced",
            "ship": {"id": 12, "name": "Anson", "rate": 3},
            "is_official_template": False,
            "sailors": 80,
            "soldiers": 80,
            "musketeers": 0,
            "mercenaries": 0,
            "owner_id": 42,
            "created_at": "2026-08-15T12:00:00+00:00",
            "updated_at": "2026-08-15T12:00:00+00:00",
        },
    },
    "build.updated": {
        **_COMMON_EVENT,
        "resource_type": "build",
        "resource_id": 401,
        "resource_url": "/builds/401",
        "data": {
            "id": 401,
            "build_name": "Heavy Broadside Mk II",
            "build_type": "balanced",
            "ship": {"id": 12, "name": "Anson", "rate": 3},
            "is_official_template": False,
            "sailors": 90,
            "soldiers": 70,
            "musketeers": 0,
            "mercenaries": 0,
            "owner_id": 42,
            "created_at": "2026-08-15T12:00:00+00:00",
            "updated_at": "2026-08-16T12:00:00+00:00",
        },
    },
    "build.removed": {
        **_COMMON_EVENT,
        "resource_type": "build",
        "resource_id": 401,
        "resource_url": "/builds",
        "data": {"id": 401, "build_name": "Heavy Broadside Mk II"},
    },
    "forum.thread.created": {
        **_COMMON_EVENT,
        "resource_type": "forum_thread",
        "resource_id": 501,
        "resource_url": "/forum/501",
        "data": {
            "id": 501,
            "title": "Fleet formation questions",
            "category": "training",
            "owner": _COMMON_USER,
            "reply_count": 0,
            "created_at": "2026-08-15T12:00:00+00:00",
            "updated_at": "2026-08-15T12:00:00+00:00",
            "last_activity_at": "2026-08-15T12:00:00+00:00",
        },
    },
    "forum.thread.updated": {
        **_COMMON_EVENT,
        "resource_type": "forum_thread",
        "resource_id": 501,
        "resource_url": "/forum/501",
        "data": {
            "id": 501,
            "title": "Fleet formation questions and answers",
            "category": "training",
            "owner": _COMMON_USER,
            "reply_count": 3,
            "created_at": "2026-08-15T12:00:00+00:00",
            "updated_at": "2026-08-16T12:00:00+00:00",
            "last_activity_at": "2026-08-16T12:00:00+00:00",
        },
    },
}


def event_test_sample(event_type: str) -> dict[str, Any]:
    return deepcopy(EVENT_TEST_SAMPLES.get(event_type, EVENT_TEST_SAMPLES["integration.test"]))


__all__ = [
    "DEFAULT_MESSAGES",
    "EVENT_CATALOG",
    "EVENT_TEST_SAMPLES",
    "EVENT_TYPES",
    "event_test_sample",
]
