"""Consumable and utility item seeds from the public WoSB wiki item catalog."""

CONSUMABLE_OPTIONS = [
    {"category": "consumable", "name": "Black Double Powder", "source": "wiki"},
    {"category": "consumable", "name": "Blue Signal Flare", "source": "wiki"},
    {"category": "consumable", "name": "Bribery", "source": "wiki"},
    {"category": "consumable", "name": "Bronze Patches", "source": "wiki"},
    {"category": "consumable", "name": "Bronze Repair Kit", "source": "wiki"},
    {"category": "consumable", "name": "Field Kit", "source": "wiki"},
    {"category": "consumable", "name": "Filling Ration", "source": "wiki"},
    {"category": "consumable", "name": "Horn", "source": "wiki"},
    {"category": "consumable", "name": "Iron Patches", "source": "wiki"},
    {"category": "consumable", "name": "Iron Repair Kit", "source": "wiki"},
    {"category": "consumable", "name": "Large Additional Sails", "source": "wiki"},
    {"category": "consumable", "name": "Large Plates", "source": "wiki"},
    {"category": "consumable", "name": "Phosphorous", "source": "wiki"},
    {"category": "consumable", "name": "Poseidon's Hook", "source": "wiki"},
    {"category": "consumable", "name": "Powder Charge", "source": "wiki"},
    {"category": "consumable", "name": "Red Double Powder", "source": "wiki"},
    {"category": "consumable", "name": "Red Signal Flare", "source": "wiki"},
    {"category": "consumable", "name": "Rum Ration", "source": "wiki"},
    {"category": "consumable", "name": "Small Additional Sails", "source": "wiki"},
    {"category": "consumable", "name": "Small Plates", "source": "wiki"},
    {"category": "consumable", "name": "Smoke Bomb", "source": "wiki"},
    {"category": "consumable", "name": "Smoke Screen", "source": "wiki"},
    {"category": "consumable", "name": "White Double Powder", "source": "wiki"},
    {"category": "consumable", "name": "Wooden Patches", "source": "wiki"},
    {"category": "consumable", "name": "Wooden Repair Kit", "source": "wiki"},
    {"category": "consumable", "name": "Wreckage Patches", "source": "wiki"},
    {"category": "consumable", "name": "Yellow Signal Flare", "source": "wiki"},
]
