DEMO_GROUP_DATA = [
    {
        "title": "Evening PvE Farming Run",
        "focus": "pve_farming",
        "description": "Relaxed fleet announcement for resources and routine fights.",
        "expectations": "Bring a ship you are comfortable with, enough repair supplies and a calm voice-chat attitude.",
        "activity_plan": "We start with easy resource routes, then switch to harder targets if the fleet composition allows it.",
        "contact_note": "Post under the announcement or ping the leader in Discord before departure.",
        "max_members": 6,
        "min_ship_rate": 3,
        "max_ship_rate": None,
        "allow_guests": False,
        "fleet_restriction": None,
    },
    {
        "title": "Arena Practice Rotation",
        "focus": "pvp_arena",
        "description": "Practice announcement for arena rotations and gunnery basics.",
        "expectations": "Be ready to lose ships, review mistakes and keep comms clear during calls.",
        "activity_plan": "Short warm-up, focused 2v2/3v3 rotations, then a quick debrief after each match.",
        "contact_note": "Leader collects interested players before the session starts.",
        "max_members": 4,
        "min_ship_rate": 4,
        "max_ship_rate": 2,
        "allow_guests": False,
        "fleet_restriction": None,
    },
]
