"""Hold/cargo item seeds from the public WoSB wiki item catalog."""

HOLD_OPTIONS = [
    {"category": "hold", "name": "Animals", "source": "wiki"},
    {"category": "hold", "name": "Beam", "source": "wiki"},
    {"category": "hold", "name": "Beer", "source": "wiki"},
    {"category": "hold", "name": "Bronze", "source": "wiki"},
    {"category": "hold", "name": "Bulkhead", "source": "wiki"},
    {"category": "hold", "name": "Canvas", "source": "wiki"},
    {"category": "hold", "name": "Chest", "source": "wiki"},
    {"category": "hold", "name": "Cinnamon", "source": "wiki"},
    {"category": "hold", "name": "Coal", "source": "wiki"},
    {"category": "hold", "name": "Coffee", "source": "wiki"},
    {"category": "hold", "name": "Copper", "source": "wiki"},
    {"category": "hold", "name": "Copper Ore", "source": "wiki"},
    {"category": "hold", "name": "Dates", "source": "wiki"},
    {"category": "hold", "name": "Fabric", "source": "wiki"},
    {"category": "hold", "name": "Fish", "source": "wiki"},
    {"category": "hold", "name": "Fresh Meat", "source": "wiki"},
    {"category": "hold", "name": "Grain", "source": "wiki"},
    {"category": "hold", "name": "Grog", "source": "wiki"},
    {"category": "hold", "name": "Iron", "source": "wiki"},
    {"category": "hold", "name": "Iron Ore", "source": "wiki"},
    {"category": "hold", "name": "Leather", "source": "wiki"},
    {"category": "hold", "name": "Mango", "source": "wiki"},
    {"category": "hold", "name": "Nuts", "source": "wiki"},
    {"category": "hold", "name": "Oil", "source": "wiki"},
    {"category": "hold", "name": "Paprika", "source": "wiki"},
    {"category": "hold", "name": "Pepper", "source": "wiki"},
    {"category": "hold", "name": "Pineapples", "source": "wiki"},
    {"category": "hold", "name": "Provision", "source": "wiki"},
    {"category": "hold", "name": "Resin", "source": "wiki"},
    {"category": "hold", "name": "Rugs", "source": "wiki"},
    {"category": "hold", "name": "Rum", "source": "wiki"},
    {"category": "hold", "name": "Saffron", "source": "wiki"},
    {"category": "hold", "name": "Salt", "source": "wiki"},
    {"category": "hold", "name": "Silk", "source": "wiki"},
    {"category": "hold", "name": "Sugar", "source": "wiki"},
    {"category": "hold", "name": "Supplies", "source": "wiki"},
    {"category": "hold", "name": "Tobacco", "source": "wiki"},
    {"category": "hold", "name": "Vanilla", "source": "wiki"},
    {"category": "hold", "name": "Water", "source": "wiki"},
    {"category": "hold", "name": "Whale Oil", "source": "wiki"},
    {"category": "hold", "name": "Wine", "source": "wiki"},
    {"category": "hold", "name": "Wood", "source": "wiki"},
    {"category": "hold", "name": "Wreckage", "source": "wiki"},
]
