"""Ship catalog seed data for the Build Designer.

The catalog is audited against the individual World of Sea Battle wiki ship
pages. ``weapon_layout`` always means ``bow-side-stern`` plus an optional
``mortar Xin xN`` suffix. ``max_weapon_class`` stores the explicit audited
Light/Medium/Heavy mount ceiling instead of a pound-value heuristic. This
prevents hull dimensions or weapon names from being mistaken for compatibility
(including the former De Zeven Provincien bug).

`sailor_minimum` remains an app-level planning rule (40% of crew capacity) until
an official API/export exposes the exact minimum crew requirement.
"""

SHIP_SOURCE_URL = "https://world-of-sea-battle.fandom.com/wiki/Ships"
SHIP_WEAPON_LAYOUT_AUDIT_DATE = "2026-07-10"

SHIP_SEED_DATA = [{'armor': 4.2,
  'crew_capacity': 170,
  'displacement_tons': 3150,
  'durability': 2600,
  'has_lantern': True,
  'hold_capacity': 20000,
  'maneuverability': 85,
  'max_weapon_class': 'heavy',
  'name': 'Firestorm',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 68,
  'ship_type': 'Frigate',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.7,
  'upgrade_slots': 6,
  'weapon_layout': '1-28-12'},
 {'armor': 3.2,
  'crew_capacity': 152,
  'displacement_tons': 3060,
  'durability': 2340,
  'has_lantern': True,
  'hold_capacity': 17500,
  'maneuverability': 87,
  'max_weapon_class': 'heavy',
  'name': 'Ingermanland',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 61,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.0,
  'upgrade_slots': 6,
  'weapon_layout': '4-32-0'},
 {'armor': 2.8,
  'crew_capacity': 132,
  'displacement_tons': 2475,
  'durability': 2100,
  'has_lantern': True,
  'hold_capacity': 15500,
  'maneuverability': 95,
  'max_weapon_class': 'heavy',
  'name': 'Poltava',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 53,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.6,
  'upgrade_slots': 5,
  'weapon_layout': '4-23-0'},
 {'armor': 2.4,
  'crew_capacity': 112,
  'displacement_tons': 2025,
  'durability': 1680,
  'has_lantern': True,
  'hold_capacity': 13000,
  'maneuverability': 105,
  'max_weapon_class': 'medium',
  'name': 'Surprise',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 45,
  'ship_type': 'Corvette',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 10.5,
  'upgrade_slots': 5,
  'weapon_layout': '2-18-0'},
 {'armor': 5.0,
  'crew_capacity': 66,
  'displacement_tons': 900,
  'durability': 880,
  'has_lantern': True,
  'hold_capacity': 7500,
  'maneuverability': 110,
  'max_weapon_class': 'medium',
  'name': 'Axel Thorsen',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 26,
  'ship_type': 'Schooner',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.5,
  'upgrade_slots': 5,
  'weapon_layout': '0-7-3'},
 {'armor': 2.0,
  'crew_capacity': 96,
  'displacement_tons': 1620,
  'durability': 1400,
  'has_lantern': True,
  'hold_capacity': 11000,
  'maneuverability': 100,
  'max_weapon_class': 'medium',
  'name': 'La Creole',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 38,
  'ship_type': 'Corvette',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 11.0,
  'upgrade_slots': 5,
  'weapon_layout': '0-12-4'},
 {'armor': 1.8,
  'crew_capacity': 78,
  'displacement_tons': 990,
  'durability': 900,
  'has_lantern': True,
  'hold_capacity': 8000,
  'maneuverability': 97,
  'max_weapon_class': 'light',
  'name': 'Le Cerf',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 31,
  'ship_type': 'Cutter',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 10.0,
  'upgrade_slots': 5,
  'weapon_layout': '0-9-0'},
 {'armor': 3.0,
  'crew_capacity': 94,
  'displacement_tons': 1575,
  'durability': 1000,
  'has_lantern': True,
  'hold_capacity': 10000,
  'maneuverability': 92,
  'max_weapon_class': 'light',
  'name': 'Savannah',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 38,
  'ship_type': 'Frigate',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 10.8,
  'upgrade_slots': 5,
  'weapon_layout': '0-9-0'},
 {'armor': 1.6,
  'crew_capacity': 66,
  'displacement_tons': 900,
  'durability': 700,
  'has_lantern': True,
  'hold_capacity': 6000,
  'maneuverability': 94,
  'max_weapon_class': 'light',
  'name': 'Pickle',
  'rate': 7,
  'sail_slots': 1,
  'sailor_minimum': 26,
  'ship_type': 'Schooner',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.2,
  'upgrade_slots': 5,
  'weapon_layout': '0-6-0'},
 {'armor': 8.6,
  'crew_capacity': 188,
  'displacement_tons': 4440,
  'durability': 3320,
  'has_lantern': True,
  'hold_capacity': 26000,
  'maneuverability': 75,
  'max_weapon_class': 'heavy',
  'name': 'De Zeven Provincien',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 75,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.7,
  'upgrade_slots': 6,
  'weapon_layout': '4-42-4'},
 {'armor': 7.0,
  'crew_capacity': 192,
  'displacement_tons': 4275,
  'durability': 3600,
  'has_lantern': True,
  'hold_capacity': 26500,
  'maneuverability': 70,
  'max_weapon_class': 'heavy',
  'name': 'Sovereign',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 77,
  'ship_type': 'Galleon',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.4,
  'upgrade_slots': 6,
  'weapon_layout': '8-38-4 + mortar 7in x2'},
 {'armor': 8.0,
  'crew_capacity': 204,
  'displacement_tons': 4050,
  'durability': 3740,
  'has_lantern': True,
  'hold_capacity': 25000,
  'maneuverability': 66,
  'max_weapon_class': 'heavy',
  'name': 'Victory',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 82,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.1,
  'upgrade_slots': 6,
  'weapon_layout': '4-49-4'},
 {'armor': 5.8,
  'crew_capacity': 194,
  'displacement_tons': 4050,
  'durability': 2900,
  'has_lantern': True,
  'hold_capacity': 28000,
  'maneuverability': 80,
  'max_weapon_class': 'heavy',
  'name': 'Neptuno',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 78,
  'ship_type': 'Galleon',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.2,
  'upgrade_slots': 6,
  'weapon_layout': '4-36-4'},
 {'armor': 6.4,
  'crew_capacity': 184,
  'displacement_tons': 3330,
  'durability': 3000,
  'has_lantern': True,
  'hold_capacity': 21500,
  'maneuverability': 74,
  'max_weapon_class': 'heavy',
  'name': 'Sans Pareil',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 74,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.7,
  'upgrade_slots': 6,
  'weapon_layout': '2-38-4'},
 {'armor': 5.6,
  'crew_capacity': 160,
  'displacement_tons': 3150,
  'durability': 2700,
  'has_lantern': True,
  'hold_capacity': 18500,
  'maneuverability': 80,
  'max_weapon_class': 'heavy',
  'name': 'Anson',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 64,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.2,
  'upgrade_slots': 5,
  'weapon_layout': '2-30-4'},
 {'armor': 5.6,
  'crew_capacity': 170,
  'displacement_tons': 2925,
  'durability': 2700,
  'has_lantern': True,
  'hold_capacity': 20000,
  'maneuverability': 78,
  'max_weapon_class': 'heavy',
  'name': 'Le Saint Louis',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 68,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.9,
  'upgrade_slots': 5,
  'weapon_layout': '6-26-6'},
 {'armor': 4.8,
  'crew_capacity': 136,
  'displacement_tons': 2115,
  'durability': 2160,
  'has_lantern': True,
  'hold_capacity': 15500,
  'maneuverability': 88,
  'max_weapon_class': 'medium',
  'name': 'Essex',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 54,
  'ship_type': 'Frigate',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.9,
  'upgrade_slots': 5,
  'weapon_layout': '2-21-2'},
 {'armor': 5.5,
  'crew_capacity': 140,
  'displacement_tons': 2700,
  'durability': 1940,
  'has_lantern': True,
  'hold_capacity': 18000,
  'maneuverability': 95,
  'max_weapon_class': 'medium',
  'name': 'Red Arrow',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 56,
  'ship_type': 'Galleon',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.1,
  'upgrade_slots': 5,
  'weapon_layout': '6-15-0 + mortar 7in x1'},
 {'armor': 4.0,
  'crew_capacity': 116,
  'displacement_tons': 2250,
  'durability': 1820,
  'has_lantern': True,
  'hold_capacity': 13000,
  'maneuverability': 84,
  'max_weapon_class': 'medium',
  'name': 'Black Wind',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 46,
  'ship_type': 'Frigate',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.4,
  'upgrade_slots': 5,
  'weapon_layout': '2-16-2'},
 {'armor': 4.5,
  'crew_capacity': 108,
  'displacement_tons': 1800,
  'durability': 1360,
  'has_lantern': True,
  'hold_capacity': 12500,
  'maneuverability': 105,
  'max_weapon_class': 'medium',
  'name': 'Kwee Song',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 43,
  'ship_type': 'Phanokson',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.9,
  'upgrade_slots': 5,
  'weapon_layout': '10-10-0'},
 {'armor': 3.6,
  'crew_capacity': 96,
  'displacement_tons': 1350,
  'durability': 1160,
  'has_lantern': True,
  'hold_capacity': 9500,
  'maneuverability': 82,
  'max_weapon_class': 'light',
  'name': 'La Salamandre',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 38,
  'ship_type': 'Ketch',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.8,
  'upgrade_slots': 5,
  'weapon_layout': '0-10-2'},
 {'armor': 3.0,
  'crew_capacity': 92,
  'displacement_tons': 1485,
  'durability': 1000,
  'has_lantern': True,
  'hold_capacity': 11000,
  'maneuverability': 90,
  'max_weapon_class': 'light',
  'name': 'Shunsen',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 37,
  'ship_type': 'Junk',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.5,
  'upgrade_slots': 5,
  'weapon_layout': '0-10-0'},
 {'armor': 3.2,
  'crew_capacity': 78,
  'displacement_tons': 1125,
  'durability': 850,
  'has_lantern': True,
  'hold_capacity': 7000,
  'maneuverability': 80,
  'max_weapon_class': 'light',
  'name': 'Horizont',
  'rate': 7,
  'sail_slots': 1,
  'sailor_minimum': 31,
  'ship_type': 'Brigantine',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.4,
  'upgrade_slots': 5,
  'weapon_layout': '0-8-2'},
 {'armor': 5.5,
  'crew_capacity': 188,
  'displacement_tons': 4500,
  'durability': 3500,
  'has_lantern': True,
  'hold_capacity': 50000,
  'maneuverability': 72,
  'max_weapon_class': 'heavy',
  'name': 'La Couronne',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 75,
  'ship_type': 'Galleon',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.6,
  'upgrade_slots': 6,
  'weapon_layout': '0-28-8'},
 {'armor': 4.4,
  'crew_capacity': 170,
  'displacement_tons': 3600,
  'durability': 2660,
  'has_lantern': True,
  'hold_capacity': 43000,
  'maneuverability': 80,
  'max_weapon_class': 'heavy',
  'name': 'La Sirene',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 68,
  'ship_type': 'Ship',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.1,
  'upgrade_slots': 6,
  'weapon_layout': '0-32-4'},
 {'armor': 3.9,
  'crew_capacity': 148,
  'displacement_tons': 2475,
  'durability': 2380,
  'has_lantern': True,
  'hold_capacity': 34000,
  'maneuverability': 87,
  'max_weapon_class': 'heavy',
  'name': 'Mordaunt',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 59,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.7,
  'upgrade_slots': 5,
  'weapon_layout': '0-26-4'},
 {'armor': 4.2,
  'crew_capacity': 152,
  'displacement_tons': 3375,
  'durability': 2440,
  'has_lantern': True,
  'hold_capacity': 38000,
  'maneuverability': 85,
  'max_weapon_class': 'heavy',
  'name': 'Prins Willem',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 61,
  'ship_type': 'Galleon',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.5,
  'upgrade_slots': 5,
  'weapon_layout': '4-26-6'},
 {'armor': 3.3,
  'crew_capacity': 126,
  'displacement_tons': 3060,
  'durability': 1920,
  'has_lantern': True,
  'hold_capacity': 27500,
  'maneuverability': 96,
  'max_weapon_class': 'medium',
  'name': 'Falmouth',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 50,
  'ship_type': 'Ship',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.4,
  'upgrade_slots': 5,
  'weapon_layout': '0-18-4'},
 {'armor': 2.7,
  'crew_capacity': 100,
  'displacement_tons': 2700,
  'durability': 1700,
  'has_lantern': True,
  'hold_capacity': 30000,
  'maneuverability': 100,
  'max_weapon_class': 'medium',
  'name': 'Flying Cloud',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 40,
  'ship_type': 'Clipper',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 10.8,
  'upgrade_slots': 5,
  'weapon_layout': '0-16-0'},
 {'armor': 3.5,
  'crew_capacity': 120,
  'displacement_tons': 2700,
  'durability': 2020,
  'has_lantern': True,
  'hold_capacity': 26000,
  'maneuverability': 96,
  'max_weapon_class': 'medium',
  'name': 'Friedrich Wilhelm',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 48,
  'ship_type': 'Frigate',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.4,
  'upgrade_slots': 5,
  'weapon_layout': '4-21-4'},
 {'armor': 2.7,
  'crew_capacity': 108,
  'displacement_tons': 2070,
  'durability': 1600,
  'has_lantern': True,
  'hold_capacity': 22000,
  'maneuverability': 91,
  'max_weapon_class': 'medium',
  'name': 'Russia',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 43,
  'ship_type': 'Frigate',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.9,
  'upgrade_slots': 5,
  'weapon_layout': '0-14-2'},
 {'armor': 2.5,
  'crew_capacity': 88,
  'displacement_tons': 2025,
  'durability': 1040,
  'has_lantern': True,
  'hold_capacity': 15500,
  'maneuverability': 89,
  'max_weapon_class': 'light',
  'name': 'Mercury',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 35,
  'ship_type': 'Galleon',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.2,
  'upgrade_slots': 5,
  'weapon_layout': '0-9-2'},
 {'armor': 2.2,
  'crew_capacity': 72,
  'displacement_tons': 1350,
  'durability': 750,
  'has_lantern': True,
  'hold_capacity': 11000,
  'maneuverability': 86,
  'max_weapon_class': 'light',
  'name': 'Friede',
  'rate': 7,
  'sail_slots': 1,
  'sailor_minimum': 29,
  'ship_type': 'Flute',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.8,
  'upgrade_slots': 5,
  'weapon_layout': '0-7-2'},
 {'armor': 10.0,
  'crew_capacity': 220,
  'displacement_tons': 4500,
  'durability': 4400,
  'has_lantern': True,
  'hold_capacity': 36000,
  'maneuverability': 49,
  'max_weapon_class': 'heavy',
  'name': '12 Apostolov',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 88,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 6.2,
  'upgrade_slots': 6,
  'weapon_layout': '0-59-0'},
 {'armor': 11.0,
  'crew_capacity': 240,
  'displacement_tons': 4950,
  'durability': 4800,
  'has_lantern': True,
  'hold_capacity': 39500,
  'maneuverability': 45,
  'max_weapon_class': 'heavy',
  'name': 'Santisima Trinidad',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 96,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 5.8,
  'upgrade_slots': 6,
  'weapon_layout': '0-63-4'},
 {'armor': 8.0,
  'crew_capacity': 198,
  'displacement_tons': 3600,
  'durability': 3540,
  'has_lantern': True,
  'hold_capacity': 30500,
  'maneuverability': 57,
  'max_weapon_class': 'heavy',
  'name': 'Redoutable',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 79,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.0,
  'upgrade_slots': 6,
  'weapon_layout': '0-43-0'},
 {'armor': 7.5,
  'crew_capacity': 190,
  'displacement_tons': 3600,
  'durability': 3400,
  'has_lantern': True,
  'hold_capacity': 33500,
  'maneuverability': 60,
  'max_weapon_class': 'heavy',
  'name': 'St. Pavel',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 76,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.2,
  'upgrade_slots': 6,
  'weapon_layout': '0-44-2'},
 {'armor': 7.2,
  'crew_capacity': 184,
  'displacement_tons': 3550,
  'durability': 3280,
  'has_lantern': True,
  'hold_capacity': 32000,
  'maneuverability': 58,
  'max_weapon_class': 'heavy',
  'name': 'Vasa',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 74,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.1,
  'upgrade_slots': 6,
  'weapon_layout': '2-31-4'},
 {'armor': 7.0,
  'crew_capacity': 174,
  'displacement_tons': 3915,
  'durability': 3180,
  'has_lantern': True,
  'hold_capacity': 26000,
  'maneuverability': 62,
  'max_weapon_class': 'heavy',
  'name': 'Azov',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 70,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.5,
  'upgrade_slots': 5,
  'weapon_layout': '8-35-8'},
 {'armor': 7.0,
  'crew_capacity': 174,
  'displacement_tons': 3915,
  'durability': 3180,
  'has_lantern': True,
  'hold_capacity': 26000,
  'maneuverability': 62,
  'max_weapon_class': 'heavy',
  'name': 'Bellona',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 70,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.5,
  'upgrade_slots': 5,
  'weapon_layout': '0-35-0'},
 {'armor': 6.0,
  'crew_capacity': 148,
  'displacement_tons': 2565,
  'durability': 2560,
  'has_lantern': True,
  'hold_capacity': 21500,
  'maneuverability': 68,
  'max_weapon_class': 'medium',
  'name': 'Constitution',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 59,
  'ship_type': 'Frigate',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.0,
  'upgrade_slots': 5,
  'weapon_layout': '0-26-0'},
 {'armor': 5.0,
  'crew_capacity': 126,
  'displacement_tons': 2475,
  'durability': 2140,
  'has_lantern': True,
  'hold_capacity': 17500,
  'maneuverability': 72,
  'max_weapon_class': 'medium',
  'name': 'San Martin',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 50,
  'ship_type': 'Galleon',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.5,
  'upgrade_slots': 5,
  'weapon_layout': '0-20-0'},
 {'armor': 4.5,
  'crew_capacity': 104,
  'displacement_tons': 1440,
  'durability': 1380,
  'has_lantern': True,
  'hold_capacity': 12500,
  'maneuverability': 75,
  'max_weapon_class': 'light',
  'name': 'Phoenix',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 42,
  'ship_type': 'Brig',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.2,
  'upgrade_slots': 5,
  'weapon_layout': '0-12-0'},
 {'armor': 6.5,
  'crew_capacity': 156,
  'displacement_tons': 3870,
  'durability': 2900,
  'has_lantern': True,
  'hold_capacity': 24000,
  'maneuverability': 83,
  'max_weapon_class': 'heavy',
  'name': 'La Royale',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 62,
  'ship_type': 'Galley',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.4,
  'upgrade_slots': 6,
  'weapon_layout': '6-18-0 + mortar 11in x3'},
 {'armor': 5.2,
  'crew_capacity': 140,
  'displacement_tons': 2925,
  'durability': 2660,
  'has_lantern': True,
  'hold_capacity': 21000,
  'maneuverability': 92,
  'max_weapon_class': 'heavy',
  'name': 'Adventure',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 56,
  'ship_type': 'Galley',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.2,
  'upgrade_slots': 6,
  'weapon_layout': '0-19-4 + mortar 10in x2'},
 {'armor': 4.6,
  'crew_capacity': 124,
  'displacement_tons': 2250,
  'durability': 2000,
  'has_lantern': True,
  'hold_capacity': 18000,
  'maneuverability': 85,
  'max_weapon_class': 'heavy',
  'name': 'Kobukson',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 50,
  'ship_type': 'Phanokson',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.0,
  'upgrade_slots': 5,
  'weapon_layout': '0-15-0 + mortar 9in x4'},
 {'armor': 5.4,
  'crew_capacity': 158,
  'displacement_tons': 3150,
  'durability': 2600,
  'has_lantern': True,
  'hold_capacity': 19000,
  'maneuverability': 79,
  'max_weapon_class': 'heavy',
  'name': 'Shen',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 63,
  'ship_type': 'Galiot',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.6,
  'upgrade_slots': 5,
  'weapon_layout': '1-22-0 + mortar 11in x2'},
 {'armor': 3.5,
  'crew_capacity': 110,
  'displacement_tons': 2025,
  'durability': 1780,
  'has_lantern': True,
  'hold_capacity': 15000,
  'maneuverability': 96,
  'max_weapon_class': 'medium',
  'name': 'Sparrow',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 44,
  'ship_type': 'Tartane',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.2,
  'upgrade_slots': 5,
  'weapon_layout': '0-4-0 + mortar 8in x3'},
 {'armor': 3.3,
  'crew_capacity': 98,
  'displacement_tons': 1800,
  'durability': 1620,
  'has_lantern': True,
  'hold_capacity': 13000,
  'maneuverability': 96,
  'max_weapon_class': 'medium',
  'name': 'Eagle',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 39,
  'ship_type': 'Flute',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.0,
  'upgrade_slots': 5,
  'weapon_layout': '0-8-4'},
 {'armor': 3.2,
  'crew_capacity': 88,
  'displacement_tons': 2025,
  'durability': 1520,
  'has_lantern': True,
  'hold_capacity': 12500,
  'maneuverability': 105,
  'max_weapon_class': 'medium',
  'name': 'Le Requin',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 35,
  'ship_type': 'Xebec',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.6,
  'upgrade_slots': 5,
  'weapon_layout': '0-12-2 + mortar 7in x1'},
 {'armor': 2.9,
  'crew_capacity': 96,
  'displacement_tons': 1575,
  'durability': 980,
  'has_lantern': True,
  'hold_capacity': 8500,
  'maneuverability': 102,
  'max_weapon_class': 'light',
  'name': 'Golden Apostle',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 38,
  'ship_type': 'Cutter',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.2,
  'upgrade_slots': 5,
  'weapon_layout': '0-7-0 + mortar 6in x1'},
 {'armor': 2.9,
  'crew_capacity': 74,
  'displacement_tons': 1575,
  'durability': 980,
  'has_lantern': True,
  'hold_capacity': 9000,
  'maneuverability': 102,
  'max_weapon_class': 'light',
  'name': 'Polacca',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 30,
  'ship_type': 'Polacca',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.0,
  'upgrade_slots': 5,
  'weapon_layout': '0-7-0 + mortar 6in x1'},
 {'armor': 11.5,
  'crew_capacity': 288,
  'displacement_tons': 5625,
  'durability': 8000,
  'has_lantern': True,
  'hold_capacity': 54000,
  'maneuverability': 42,
  'max_weapon_class': 'heavy',
  'name': 'Huracan',
  'rate': 1,
  'sail_slots': 1,
  'sailor_minimum': 115,
  'ship_type': 'Ship of the Line',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 5.5,
  'upgrade_slots': 6,
  'weapon_layout': '2-85-0'},
 {'armor': 6.8,
  'crew_capacity': 176,
  'displacement_tons': 3375,
  'durability': 2760,
  'has_lantern': True,
  'hold_capacity': 23000,
  'maneuverability': 75,
  'max_weapon_class': 'heavy',
  'name': 'Octopus',
  'rate': 2,
  'sail_slots': 1,
  'sailor_minimum': 70,
  'ship_type': 'Ship',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.3,
  'upgrade_slots': 6,
  'weapon_layout': '0-37-8'},
 {'armor': 8.2,
  'crew_capacity': 166,
  'displacement_tons': 4950,
  'durability': 3000,
  'has_lantern': True,
  'hold_capacity': 27000,
  'maneuverability': 66,
  'max_weapon_class': 'heavy',
  'name': 'Deadfish',
  'rate': 3,
  'sail_slots': 1,
  'sailor_minimum': 66,
  'ship_type': 'Ship',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 6.8,
  'upgrade_slots': 5,
  'weapon_layout': '1-25-8'},
 {'armor': 5.5,
  'crew_capacity': 144,
  'displacement_tons': 2610,
  'durability': 1760,
  'has_lantern': True,
  'hold_capacity': 17000,
  'maneuverability': 110,
  'max_weapon_class': 'medium',
  'name': 'Devourer',
  'rate': 4,
  'sail_slots': 1,
  'sailor_minimum': 58,
  'ship_type': 'Barque',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 7.5,
  'upgrade_slots': 5,
  'weapon_layout': '8-11-12'},
 {'armor': 3.0,
  'crew_capacity': 120,
  'displacement_tons': 1800,
  'durability': 1700,
  'has_lantern': True,
  'hold_capacity': 14500,
  'maneuverability': 90,
  'max_weapon_class': 'medium',
  'name': 'Black Prince',
  'rate': 5,
  'sail_slots': 1,
  'sailor_minimum': 48,
  'ship_type': 'Galleon',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 9.9,
  'upgrade_slots': 5,
  'weapon_layout': '2-15-2'},
 {'armor': 2.0,
  'crew_capacity': 84,
  'displacement_tons': 1200,
  'durability': 900,
  'has_lantern': True,
  'hold_capacity': 9000,
  'maneuverability': 90,
  'max_weapon_class': 'light',
  'name': 'Balloon',
  'rate': 6,
  'sail_slots': 1,
  'sailor_minimum': 34,
  'ship_type': 'Montgolfiere',
  'source': 'WoSB wiki ship page audit 2026-07',
  'speed_knots': 8.5,
  'upgrade_slots': 5,
  'weapon_layout': '0-4-0'}]

# The community pages for these special ships do not currently expose a full
# bow/side/stern weapon breakdown. Keep the existing planning values visible as
# provisional instead of presenting them as fully verified source data.
for _ship in SHIP_SEED_DATA:
    if _ship["name"] in {"Axel Thorsen", "Balloon"}:
        _ship["source"] = "WoSB wiki audit 2026-07 (incomplete weapon page; provisional layout)"
