"""production baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-07-15 23:22:38.905982
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('logger', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=12), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('client', sa.String(length=120), nullable=True),
    sa.Column('client_ip', sa.String(length=120), nullable=True),
    sa.Column('forwarded_for', sa.String(length=300), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('query_string', sa.String(length=500), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_logs_client_ip'), ['client_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_logger'), ['logger'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_status_code'), ['status_code'], unique=False)

    op.create_table('build_item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=220), nullable=True),
    sa.Column('seed_revision', sa.String(length=80), nullable=True),
    sa.Column('seed_checksum', sa.String(length=64), nullable=True),
    sa.Column('is_seed_overridden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_build_item_categories_sort_order'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('build_item_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_item_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_categories_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_build_item_categories_seed_key'), ['seed_key'], unique=True)

    op.create_table('fleet_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_leadership', sa.Boolean(), nullable=False),
    sa.Column('can_manage_fleet', sa.Boolean(), nullable=False),
    sa.Column('can_manage_members', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rank >= 0', name='ck_fleet_roles_rank'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fleet_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleet_roles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_fleet_roles_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_roles_is_leadership'), ['is_leadership'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_roles_is_system'), ['is_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_roles_rank'), ['rank'], unique=False)

    op.create_table('fleets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('focus', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('standing_orders', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleets_focus'), ['focus'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleets_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_fleets_slug'), ['slug'], unique=True)

    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('ship_type', sa.String(length=80), nullable=False),
    sa.Column('durability', sa.Integer(), nullable=False),
    sa.Column('speed_min_knots', sa.Float(), nullable=False),
    sa.Column('speed_knots', sa.Float(), nullable=False),
    sa.Column('maneuverability', sa.Float(), nullable=False),
    sa.Column('armor', sa.Float(), nullable=False),
    sa.Column('hold_capacity', sa.Integer(), nullable=False),
    sa.Column('crew_capacity', sa.Integer(), nullable=False),
    sa.Column('sailor_minimum', sa.Integer(), nullable=False),
    sa.Column('displacement_tons', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=240), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sail_slots', sa.Integer(), nullable=False),
    sa.Column('upgrade_slots', sa.Integer(), nullable=False),
    sa.Column('has_lantern', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=220), nullable=True),
    sa.Column('seed_revision', sa.String(length=80), nullable=True),
    sa.Column('seed_checksum', sa.String(length=64), nullable=True),
    sa.Column('is_seed_overridden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('armor >= 0', name='ck_ships_armor'),
    sa.CheckConstraint('crew_capacity >= 0', name='ck_ships_crew_capacity'),
    sa.CheckConstraint('displacement_tons >= 0', name='ck_ships_displacement_tons'),
    sa.CheckConstraint('durability >= 0', name='ck_ships_durability'),
    sa.CheckConstraint('hold_capacity >= 0', name='ck_ships_hold_capacity'),
    sa.CheckConstraint('maneuverability >= 0', name='ck_ships_maneuverability'),
    sa.CheckConstraint('rate >= 1 and rate <= 7', name='ck_ships_rate'),
    sa.CheckConstraint('sail_slots >= 0', name='ck_ships_sail_slots'),
    sa.CheckConstraint('sailor_minimum >= 0', name='ck_ships_sailor_minimum'),
    sa.CheckConstraint('speed_knots >= speed_min_knots', name='ck_ships_speed_range'),
    sa.CheckConstraint('speed_min_knots >= 0', name='ck_ships_speed_min_knots'),
    sa.CheckConstraint('upgrade_slots >= 0 and upgrade_slots <= 8', name='ck_ships_upgrade_slots'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ships_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_ships_rate'), ['rate'], unique=False)
        batch_op.create_index(batch_op.f('ix_ships_seed_key'), ['seed_key'], unique=True)

    op.create_table('site_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('can_manage_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rank >= 0', name='ck_site_roles_rank'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_roles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_site_roles_rank'), ['rank'], unique=False)

    op.create_table('squad_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('can_manage_roster', sa.Boolean(), nullable=False),
    sa.Column('can_manage_events', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rank >= 0', name='ck_squad_roles_rank'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('squad_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_squad_roles_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_squad_roles_rank'), ['rank'], unique=False)

    op.create_table('weapon_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.CheckConstraint('rank >= 0', name='ck_weapon_classes_rank'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weapon_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weapon_classes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_weapon_classes_rank'), ['rank'], unique=False)

    op.create_table('weapon_slot_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weapon_slot_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weapon_slot_types_code'), ['code'], unique=True)

    op.create_table('build_item_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('source', sa.String(length=240), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('option_kind', sa.String(length=40), nullable=True),
    sa.Column('weapon_class_id', sa.Integer(), nullable=True),
    sa.Column('weapon_caliber_inches', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('seed_key', sa.String(length=220), nullable=True),
    sa.Column('seed_revision', sa.String(length=80), nullable=True),
    sa.Column('seed_checksum', sa.String(length=64), nullable=True),
    sa.Column('is_seed_overridden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['build_item_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weapon_class_id'], ['weapon_classes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_build_item_option_category_name')
    )
    with op.batch_alter_table('build_item_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_item_options_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_options_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_options_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_options_option_kind'), ['option_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_options_seed_key'), ['seed_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_build_item_options_weapon_class_id'), ['weapon_class_id'], unique=False)

    op.create_table('ship_weapon_mounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('slot_type_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('max_weapon_class_id', sa.Integer(), nullable=True),
    sa.Column('max_caliber_inches', sa.Float(), nullable=True),
    sa.CheckConstraint('capacity >= 0', name='ck_ship_weapon_mount_capacity'),
    sa.CheckConstraint('max_caliber_inches is null or max_caliber_inches >= 0', name='ck_ship_weapon_mount_max_caliber'),
    sa.ForeignKeyConstraint(['max_weapon_class_id'], ['weapon_classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_type_id'], ['weapon_slot_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ship_id', 'slot_type_id', name='uq_ship_weapon_mount_slot')
    )
    with op.batch_alter_table('ship_weapon_mounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_weapon_mounts_max_weapon_class_id'), ['max_weapon_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ship_weapon_mounts_ship_id'), ['ship_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ship_weapon_mounts_slot_type_id'), ['slot_type_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('site_role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_role_id'], ['site_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_site_role_id'), ['site_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=80), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('changed_fields_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_role'), ['actor_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_username'), ['actor_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('build_item_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('effect_key', sa.String(length=80), nullable=False),
    sa.Column('effect_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['build_item_options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_id', 'effect_key', name='uq_build_item_effect_key')
    )
    with op.batch_alter_table('build_item_effects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_item_effects_effect_key'), ['effect_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_effects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_effects_option_id'), ['option_id'], unique=False)

    op.create_table('build_item_option_slot_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('slot_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['build_item_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_type_id'], ['weapon_slot_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_id', 'slot_type_id', name='uq_build_item_option_slot_type')
    )
    with op.batch_alter_table('build_item_option_slot_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_item_option_slot_types_option_id'), ['option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_option_slot_types_slot_type_id'), ['slot_type_id'], unique=False)

    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_name', sa.String(length=140), nullable=False),
    sa.Column('build_type', sa.String(length=32), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('is_official_template', sa.Boolean(), nullable=False),
    sa.Column('research_upgrade_slot_unlocked', sa.Boolean(), nullable=False),
    sa.Column('sailors', sa.Integer(), nullable=False),
    sa.Column('soldiers', sa.Integer(), nullable=False),
    sa.Column('musketeers', sa.Integer(), nullable=False),
    sa.Column('mercenaries', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('mercenaries >= 0', name='ck_builds_mercenaries'),
    sa.CheckConstraint('musketeers >= 0', name='ck_builds_musketeers'),
    sa.CheckConstraint('sailors >= 0', name='ck_builds_sailors'),
    sa.CheckConstraint('soldiers >= 0', name='ck_builds_soldiers'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builds_build_name'), ['build_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_builds_build_type'), ['build_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_builds_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builds_is_official_template'), ['is_official_template'], unique=False)
        batch_op.create_index(batch_op.f('ix_builds_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builds_ship_id'), ['ship_id'], unique=False)

    op.create_table('cookie_consent_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_key', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('necessary', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.Boolean(), nullable=False),
    sa.Column('analytics', sa.Boolean(), nullable=False),
    sa.Column('external_media', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cookie_consent_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cookie_consent_decisions_consent_key'), ['consent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_cookie_consent_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cookie_consent_decisions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_cookie_consent_key_created', ['consent_key', 'created_at'], unique=False)

    op.create_table('fleet_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fleet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fleet_role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('assignment', sa.String(length=120), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status in ('pending', 'active', 'inactive')", name='ck_fleet_memberships_status'),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ),
    sa.ForeignKeyConstraint(['fleet_role_id'], ['fleet_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fleet_id', 'user_id', name='uq_fleet_membership_user'),
    sa.UniqueConstraint('user_id', name='uq_fleet_membership_single_user')
    )
    with op.batch_alter_table('fleet_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleet_memberships_fleet_id'), ['fleet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_memberships_fleet_role_id'), ['fleet_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_memberships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_memberships_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('forum_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_threads_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_threads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_threads_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_threads_title'), ['title'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('focus', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expectations', sa.Text(), nullable=True),
    sa.Column('activity_plan', sa.Text(), nullable=True),
    sa.Column('contact_note', sa.String(length=300), nullable=True),
    sa.Column('scheduled_start_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('min_ship_rate', sa.Integer(), nullable=True),
    sa.Column('max_ship_rate', sa.Integer(), nullable=True),
    sa.Column('allow_guests', sa.Boolean(), nullable=False),
    sa.Column('fleet_restriction', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status in ('open', 'full', 'closed')", name='ck_groups_status'),
    sa.CheckConstraint('max_members >= 2 and max_members <= 50', name='ck_groups_max_members'),
    sa.CheckConstraint('max_ship_rate is null or (max_ship_rate >= 1 and max_ship_rate <= 7)', name='ck_groups_max_ship_rate'),
    sa.CheckConstraint('min_ship_rate is null or (min_ship_rate >= 1 and min_ship_rate <= 7)', name='ck_groups_min_ship_rate'),
    sa.CheckConstraint('scheduled_end_at is null or scheduled_start_at is null or scheduled_end_at > scheduled_start_at', name='ck_groups_schedule_range'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_focus'), ['focus'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_scheduled_start_at'), ['scheduled_start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_title'), ['title'], unique=False)

    op.create_table('guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guides_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_title'), ['title'], unique=False)

    op.create_table('ip_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('reason', sa.String(length=240), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_username', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('unblocked_at', sa.DateTime(), nullable=True),
    sa.Column('unblocked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('unblocked_by_username', sa.String(length=80), nullable=True),
    sa.Column('unblock_reason', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unblocked_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ip_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ip_blocks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_blocks_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_blocks_created_by_username'), ['created_by_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_blocks_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_blocks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_blocks_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_blocks_unblocked_at'), ['unblocked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ip_blocks_unblocked_by_user_id'), ['unblocked_by_user_id'], unique=False)

    op.create_table('newcomer_guide_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbound_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('endpoint_url', sa.String(length=1000), nullable=False),
    sa.Column('event_types_json', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.String(length=24), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('discord_username', sa.String(length=80), nullable=True),
    sa.Column('discord_avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('broadcast_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_username', sa.String(length=80), nullable=False),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbound_webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbound_webhooks_broadcast_enabled'), ['broadcast_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhooks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhooks_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhooks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhooks_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhooks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhooks_scope_id'), ['scope_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhooks_scope_type'), ['scope_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhooks_updated_at'), ['updated_at'], unique=False)

    op.create_table('registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('wants_fleet_membership', sa.Boolean(), nullable=False),
    sa.Column('fleet_id', sa.Integer(), nullable=True),
    sa.Column('fleet_application_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status in ('pending', 'approved', 'rejected')", name='ck_registration_requests_status'),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_created_user_id'), ['created_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_fleet_id'), ['fleet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_reviewed_by_id'), ['reviewed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_username'), ['username'], unique=False)

    op.create_table('ship_upgrade_effect_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('effect_key', sa.String(length=80), nullable=False),
    sa.Column('effect_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['build_item_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ship_id', 'option_id', 'effect_key', name='uq_ship_upgrade_effect_override')
    )
    with op.batch_alter_table('ship_upgrade_effect_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_upgrade_effect_overrides_effect_key'), ['effect_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ship_upgrade_effect_overrides_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ship_upgrade_effect_overrides_option_id'), ['option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ship_upgrade_effect_overrides_ship_id'), ['ship_id'], unique=False)

    op.create_table('squads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fleet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('focus', sa.String(length=160), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fleet_id', 'name', name='uq_squads_fleet_name'),
    sa.UniqueConstraint('fleet_id', 'slug', name='uq_squads_fleet_slug')
    )
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_squads_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squads_fleet_id'), ['fleet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squads_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_squads_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_squads_slug'), ['slug'], unique=False)

    op.create_table('stored_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('usage_context', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stored_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_files_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_files_stored_name'), ['stored_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_stored_files_usage_context'), ['usage_context'], unique=False)

    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('external_fleet_name', sa.String(length=120), nullable=True),
    sa.Column('preferred_focus', sa.String(length=80), nullable=True),
    sa.Column('availability', sa.String(length=240), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=True),
    sa.Column('discord_handle', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('build_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('slot_type', sa.String(length=40), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity is null or quantity >= 1', name='ck_build_slots_quantity'),
    sa.CheckConstraint('slot_index >= 0', name='ck_build_slots_slot_index'),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['build_item_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_id', 'slot_type', 'slot_index', name='uq_build_slot_position')
    )
    with op.batch_alter_table('build_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_slots_build_id'), ['build_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_slots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_slots_option_id'), ['option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_slots_slot_type'), ['slot_type'], unique=False)

    op.create_table('fleet_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_at >= start_at', name='ck_fleet_events_time_range'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fleet_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleet_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_is_cancelled'), ['is_cancelled'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_squad_id'), ['squad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_title'), ['title'], unique=False)

    op.create_table('forum_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_posts_thread_id'), ['thread_id'], unique=False)

    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('fleet_name', sa.String(length=120), nullable=True),
    sa.Column('ship_id', sa.Integer(), nullable=True),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('ship_name', sa.String(length=140), nullable=True),
    sa.Column('ship_rate', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('ship_rate is null or (ship_rate >= 1 and ship_rate <= 7)', name='ck_group_members_ship_rate'),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_members_build_id'), ['build_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_ship_id'), ['ship_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_user_id'), ['user_id'], unique=False)

    op.create_table('guide_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['stored_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guide_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guide_attachments_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_attachments_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_attachments_id'), ['id'], unique=False)

    op.create_table('guide_build_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_id', 'build_id', name='uq_guide_build_reference')
    )
    with op.batch_alter_table('guide_build_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guide_build_references_build_id'), ['build_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_build_references_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_build_references_id'), ['id'], unique=False)

    op.create_table('newcomer_guide_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['newcomer_guide_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newcomer_guide_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newcomer_guide_blocks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_newcomer_guide_blocks_page_id'), ['page_id'], unique=False)

    op.create_table('outbound_webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['outbound_webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbound_webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbound_webhook_deliveries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhook_deliveries_delivered_at'), ['delivered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhook_deliveries_delivery_id'), ['delivery_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_outbound_webhook_deliveries_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhook_deliveries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhook_deliveries_last_attempt_at'), ['last_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhook_deliveries_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhook_deliveries_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhook_deliveries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_webhook_deliveries_webhook_id'), ['webhook_id'], unique=False)

    op.create_table('squad_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('squad_id', sa.Integer(), nullable=False),
    sa.Column('fleet_membership_id', sa.Integer(), nullable=False),
    sa.Column('squad_role_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fleet_membership_id'], ['fleet_memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_role_id'], ['squad_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('squad_id', 'fleet_membership_id', name='uq_squad_members_membership')
    )
    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_squad_members_fleet_membership_id'), ['fleet_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squad_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squad_members_squad_id'), ['squad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_squad_members_squad_role_id'), ['squad_role_id'], unique=False)

    op.create_table('user_profile_role_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fleet_role_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fleet_role_id'], ['fleet_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fleet_role_id', name='uq_user_profile_role_preference')
    )
    with op.batch_alter_table('user_profile_role_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_role_preferences_fleet_role_id'), ['fleet_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_role_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('user_profile_ship_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ship_id', name='uq_user_profile_ship_preference')
    )
    with op.batch_alter_table('user_profile_ship_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_ship_preferences_ship_id'), ['ship_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_ship_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('forum_post_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['stored_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_post_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_post_attachments_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_post_attachments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_post_attachments_post_id'), ['post_id'], unique=False)

    op.create_table('newcomer_guide_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=24), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=180), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['newcomer_guide_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('newcomer_guide_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newcomer_guide_resources_block_id'), ['block_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_newcomer_guide_resources_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newcomer_guide_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newcomer_guide_resources_id'))
        batch_op.drop_index(batch_op.f('ix_newcomer_guide_resources_block_id'))

    op.drop_table('newcomer_guide_resources')
    with op.batch_alter_table('forum_post_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_post_attachments_post_id'))
        batch_op.drop_index(batch_op.f('ix_forum_post_attachments_id'))
        batch_op.drop_index(batch_op.f('ix_forum_post_attachments_file_id'))

    op.drop_table('forum_post_attachments')
    with op.batch_alter_table('user_profile_ship_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_ship_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profile_ship_preferences_ship_id'))

    op.drop_table('user_profile_ship_preferences')
    with op.batch_alter_table('user_profile_role_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_role_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_profile_role_preferences_fleet_role_id'))

    op.drop_table('user_profile_role_preferences')
    with op.batch_alter_table('squad_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_squad_members_squad_role_id'))
        batch_op.drop_index(batch_op.f('ix_squad_members_squad_id'))
        batch_op.drop_index(batch_op.f('ix_squad_members_id'))
        batch_op.drop_index(batch_op.f('ix_squad_members_fleet_membership_id'))

    op.drop_table('squad_members')
    with op.batch_alter_table('outbound_webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_deliveries_webhook_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_deliveries_resource_type'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_deliveries_resource_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_deliveries_last_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_deliveries_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_deliveries_event_type'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_deliveries_delivery_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_deliveries_delivered_at'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhook_deliveries_created_at'))

    op.drop_table('outbound_webhook_deliveries')
    with op.batch_alter_table('newcomer_guide_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newcomer_guide_blocks_page_id'))
        batch_op.drop_index(batch_op.f('ix_newcomer_guide_blocks_id'))

    op.drop_table('newcomer_guide_blocks')
    with op.batch_alter_table('guide_build_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guide_build_references_id'))
        batch_op.drop_index(batch_op.f('ix_guide_build_references_guide_id'))
        batch_op.drop_index(batch_op.f('ix_guide_build_references_build_id'))

    op.drop_table('guide_build_references')
    with op.batch_alter_table('guide_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guide_attachments_id'))
        batch_op.drop_index(batch_op.f('ix_guide_attachments_guide_id'))
        batch_op.drop_index(batch_op.f('ix_guide_attachments_file_id'))

    op.drop_table('guide_attachments')
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_ship_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_is_active'))
        batch_op.drop_index(batch_op.f('ix_group_members_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_build_id'))

    op.drop_table('group_members')
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_posts_thread_id'))
        batch_op.drop_index(batch_op.f('ix_forum_posts_id'))
        batch_op.drop_index(batch_op.f('ix_forum_posts_author_id'))

    op.drop_table('forum_posts')
    with op.batch_alter_table('fleet_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleet_events_title'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_start_at'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_squad_id'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_owner_id'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_is_cancelled'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_id'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_end_at'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_category'))

    op.drop_table('fleet_events')
    with op.batch_alter_table('build_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_slots_slot_type'))
        batch_op.drop_index(batch_op.f('ix_build_slots_option_id'))
        batch_op.drop_index(batch_op.f('ix_build_slots_id'))
        batch_op.drop_index(batch_op.f('ix_build_slots_build_id'))

    op.drop_table('build_slots')
    op.drop_table('user_profiles')
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_files_usage_context'))
        batch_op.drop_index(batch_op.f('ix_stored_files_stored_name'))
        batch_op.drop_index(batch_op.f('ix_stored_files_owner_id'))
        batch_op.drop_index(batch_op.f('ix_stored_files_id'))

    op.drop_table('stored_files')
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_squads_slug'))
        batch_op.drop_index(batch_op.f('ix_squads_name'))
        batch_op.drop_index(batch_op.f('ix_squads_is_active'))
        batch_op.drop_index(batch_op.f('ix_squads_id'))
        batch_op.drop_index(batch_op.f('ix_squads_fleet_id'))
        batch_op.drop_index(batch_op.f('ix_squads_created_by_id'))

    op.drop_table('squads')
    with op.batch_alter_table('ship_upgrade_effect_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_upgrade_effect_overrides_ship_id'))
        batch_op.drop_index(batch_op.f('ix_ship_upgrade_effect_overrides_option_id'))
        batch_op.drop_index(batch_op.f('ix_ship_upgrade_effect_overrides_id'))
        batch_op.drop_index(batch_op.f('ix_ship_upgrade_effect_overrides_effect_key'))

    op.drop_table('ship_upgrade_effect_overrides')
    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_requests_username'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_status'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_reviewed_by_id'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_id'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_fleet_id'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_created_user_id'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_created_at'))

    op.drop_table('registration_requests')
    with op.batch_alter_table('outbound_webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_webhooks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhooks_scope_type'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhooks_scope_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhooks_name'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhooks_is_active'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhooks_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhooks_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_webhooks_created_at'))

    op.drop_table('outbound_webhooks')
    op.drop_table('newcomer_guide_pages')
    with op.batch_alter_table('ip_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ip_blocks_unblocked_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_ip_blocks_unblocked_at'))
        batch_op.drop_index(batch_op.f('ix_ip_blocks_ip_address'))
        batch_op.drop_index(batch_op.f('ix_ip_blocks_id'))
        batch_op.drop_index(batch_op.f('ix_ip_blocks_expires_at'))
        batch_op.drop_index(batch_op.f('ix_ip_blocks_created_by_username'))
        batch_op.drop_index(batch_op.f('ix_ip_blocks_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_ip_blocks_created_at'))

    op.drop_table('ip_blocks')
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guides_title'))
        batch_op.drop_index(batch_op.f('ix_guides_owner_id'))
        batch_op.drop_index(batch_op.f('ix_guides_is_published'))
        batch_op.drop_index(batch_op.f('ix_guides_id'))
        batch_op.drop_index(batch_op.f('ix_guides_category'))

    op.drop_table('guides')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_title'))
        batch_op.drop_index(batch_op.f('ix_groups_status'))
        batch_op.drop_index(batch_op.f('ix_groups_scheduled_start_at'))
        batch_op.drop_index(batch_op.f('ix_groups_owner_id'))
        batch_op.drop_index(batch_op.f('ix_groups_id'))
        batch_op.drop_index(batch_op.f('ix_groups_focus'))
        batch_op.drop_index(batch_op.f('ix_groups_expires_at'))

    op.drop_table('groups')
    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_threads_title'))
        batch_op.drop_index(batch_op.f('ix_forum_threads_owner_id'))
        batch_op.drop_index(batch_op.f('ix_forum_threads_id'))
        batch_op.drop_index(batch_op.f('ix_forum_threads_category'))

    op.drop_table('forum_threads')
    with op.batch_alter_table('fleet_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleet_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_fleet_memberships_status'))
        batch_op.drop_index(batch_op.f('ix_fleet_memberships_id'))
        batch_op.drop_index(batch_op.f('ix_fleet_memberships_fleet_role_id'))
        batch_op.drop_index(batch_op.f('ix_fleet_memberships_fleet_id'))

    op.drop_table('fleet_memberships')
    with op.batch_alter_table('cookie_consent_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_cookie_consent_key_created')
        batch_op.drop_index(batch_op.f('ix_cookie_consent_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_cookie_consent_decisions_created_at'))
        batch_op.drop_index(batch_op.f('ix_cookie_consent_decisions_consent_key'))

    op.drop_table('cookie_consent_decisions')
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builds_ship_id'))
        batch_op.drop_index(batch_op.f('ix_builds_owner_id'))
        batch_op.drop_index(batch_op.f('ix_builds_is_official_template'))
        batch_op.drop_index(batch_op.f('ix_builds_id'))
        batch_op.drop_index(batch_op.f('ix_builds_build_type'))
        batch_op.drop_index(batch_op.f('ix_builds_build_name'))

    op.drop_table('builds')
    with op.batch_alter_table('build_item_option_slot_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_item_option_slot_types_slot_type_id'))
        batch_op.drop_index(batch_op.f('ix_build_item_option_slot_types_option_id'))

    op.drop_table('build_item_option_slot_types')
    with op.batch_alter_table('build_item_effects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_item_effects_option_id'))
        batch_op.drop_index(batch_op.f('ix_build_item_effects_id'))
        batch_op.drop_index(batch_op.f('ix_build_item_effects_effect_key'))

    op.drop_table('build_item_effects')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_expires_at'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_username'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_role'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_site_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('ship_weapon_mounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_weapon_mounts_slot_type_id'))
        batch_op.drop_index(batch_op.f('ix_ship_weapon_mounts_ship_id'))
        batch_op.drop_index(batch_op.f('ix_ship_weapon_mounts_max_weapon_class_id'))

    op.drop_table('ship_weapon_mounts')
    with op.batch_alter_table('build_item_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_item_options_weapon_class_id'))
        batch_op.drop_index(batch_op.f('ix_build_item_options_seed_key'))
        batch_op.drop_index(batch_op.f('ix_build_item_options_option_kind'))
        batch_op.drop_index(batch_op.f('ix_build_item_options_name'))
        batch_op.drop_index(batch_op.f('ix_build_item_options_id'))
        batch_op.drop_index(batch_op.f('ix_build_item_options_category_id'))

    op.drop_table('build_item_options')
    with op.batch_alter_table('weapon_slot_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weapon_slot_types_code'))

    op.drop_table('weapon_slot_types')
    with op.batch_alter_table('weapon_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weapon_classes_rank'))
        batch_op.drop_index(batch_op.f('ix_weapon_classes_code'))

    op.drop_table('weapon_classes')
    with op.batch_alter_table('squad_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_squad_roles_rank'))
        batch_op.drop_index(batch_op.f('ix_squad_roles_code'))

    op.drop_table('squad_roles')
    with op.batch_alter_table('site_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_roles_rank'))
        batch_op.drop_index(batch_op.f('ix_site_roles_code'))

    op.drop_table('site_roles')
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ships_seed_key'))
        batch_op.drop_index(batch_op.f('ix_ships_rate'))
        batch_op.drop_index(batch_op.f('ix_ships_name'))
        batch_op.drop_index(batch_op.f('ix_ships_id'))

    op.drop_table('ships')
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleets_slug'))
        batch_op.drop_index(batch_op.f('ix_fleets_name'))
        batch_op.drop_index(batch_op.f('ix_fleets_id'))
        batch_op.drop_index(batch_op.f('ix_fleets_focus'))

    op.drop_table('fleets')
    with op.batch_alter_table('fleet_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleet_roles_rank'))
        batch_op.drop_index(batch_op.f('ix_fleet_roles_is_system'))
        batch_op.drop_index(batch_op.f('ix_fleet_roles_is_leadership'))
        batch_op.drop_index(batch_op.f('ix_fleet_roles_is_active'))
        batch_op.drop_index(batch_op.f('ix_fleet_roles_code'))

    op.drop_table('fleet_roles')
    with op.batch_alter_table('build_item_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_item_categories_seed_key'))
        batch_op.drop_index(batch_op.f('ix_build_item_categories_key'))
        batch_op.drop_index(batch_op.f('ix_build_item_categories_id'))

    op.drop_table('build_item_categories')
    with op.batch_alter_table('app_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_logs_status_code'))
        batch_op.drop_index(batch_op.f('ix_app_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_app_logs_path'))
        batch_op.drop_index(batch_op.f('ix_app_logs_method'))
        batch_op.drop_index(batch_op.f('ix_app_logs_logger'))
        batch_op.drop_index(batch_op.f('ix_app_logs_level'))
        batch_op.drop_index(batch_op.f('ix_app_logs_id'))
        batch_op.drop_index(batch_op.f('ix_app_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_app_logs_client_ip'))

    op.drop_table('app_logs')
    # ### end Alembic commands ###
