"""initial schema

Revision ID: 4873603a6906
Revises: 
Create Date: 2026-07-10 07:00:34.217329
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4873603a6906'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('logger', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=12), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('client', sa.String(length=120), nullable=True),
    sa.Column('client_ip', sa.String(length=120), nullable=True),
    sa.Column('forwarded_for', sa.String(length=300), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('query_string', sa.String(length=500), nullable=True),
    sa.Column('exception', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_logs_client_ip'), ['client_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_logger'), ['logger'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_method'), ['method'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_logs_status_code'), ['status_code'], unique=False)

    op.create_table('build_item_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_build_item_categories_sort_order'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('build_item_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_item_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_categories_key'), ['key'], unique=True)

    op.create_table('fleets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('focus', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('standing_orders', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleets_focus'), ['focus'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleets_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_fleets_slug'), ['slug'], unique=True)

    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('ship_type', sa.String(length=80), nullable=False),
    sa.Column('durability', sa.Integer(), nullable=False),
    sa.Column('speed_knots', sa.Float(), nullable=False),
    sa.Column('maneuverability', sa.Float(), nullable=False),
    sa.Column('armor', sa.Float(), nullable=False),
    sa.Column('hold_capacity', sa.Integer(), nullable=False),
    sa.Column('crew_capacity', sa.Integer(), nullable=False),
    sa.Column('sailor_minimum', sa.Integer(), nullable=False),
    sa.Column('weapon_layout', sa.String(length=40), nullable=True),
    sa.Column('displacement_tons', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('sail_slots', sa.Integer(), nullable=False),
    sa.Column('upgrade_slots', sa.Integer(), nullable=False),
    sa.Column('has_lantern', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('armor >= 0', name='ck_ships_armor'),
    sa.CheckConstraint('crew_capacity >= 0', name='ck_ships_crew_capacity'),
    sa.CheckConstraint('displacement_tons >= 0', name='ck_ships_displacement_tons'),
    sa.CheckConstraint('durability >= 0', name='ck_ships_durability'),
    sa.CheckConstraint('hold_capacity >= 0', name='ck_ships_hold_capacity'),
    sa.CheckConstraint('maneuverability >= 0', name='ck_ships_maneuverability'),
    sa.CheckConstraint('rate >= 1 and rate <= 7', name='ck_ships_rate'),
    sa.CheckConstraint('sail_slots >= 0', name='ck_ships_sail_slots'),
    sa.CheckConstraint('sailor_minimum >= 0', name='ck_ships_sailor_minimum'),
    sa.CheckConstraint('speed_knots >= 0', name='ck_ships_speed_knots'),
    sa.CheckConstraint('upgrade_slots >= 0', name='ck_ships_upgrade_slots'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ships_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_ships_rate'), ['rate'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role in ('user', 'moderator', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('build_item_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('option_kind', sa.String(length=40), nullable=True),
    sa.Column('allowed_slot_types', sa.String(length=160), nullable=True),
    sa.Column('weapon_caliber_inches', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_build_item_options_sort_order'),
    sa.ForeignKeyConstraint(['category_id'], ['build_item_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_build_item_option_category_name')
    )
    with op.batch_alter_table('build_item_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_item_options_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_options_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_options_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_options_option_kind'), ['option_kind'], unique=False)

    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_name', sa.String(length=140), nullable=False),
    sa.Column('build_type', sa.String(length=32), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('sailors', sa.Integer(), nullable=False),
    sa.Column('soldiers', sa.Integer(), nullable=False),
    sa.Column('musketeers', sa.Integer(), nullable=False),
    sa.Column('mercenaries', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('mercenaries >= 0', name='ck_builds_mercenaries'),
    sa.CheckConstraint('musketeers >= 0', name='ck_builds_musketeers'),
    sa.CheckConstraint('sailors >= 0', name='ck_builds_sailors'),
    sa.CheckConstraint('soldiers >= 0', name='ck_builds_soldiers'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_builds_build_name'), ['build_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_builds_build_type'), ['build_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_builds_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builds_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_builds_ship_id'), ['ship_id'], unique=False)

    op.create_table('fleet_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_at >= start_at', name='ck_fleet_events_time_range'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fleet_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleet_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_is_cancelled'), ['is_cancelled'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_start_at'), ['start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_events_title'), ['title'], unique=False)

    op.create_table('fleet_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fleet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('assignment', sa.String(length=120), nullable=True),
    sa.Column('availability', sa.String(length=240), nullable=True),
    sa.Column('preferred_ships', sa.String(length=300), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=True),
    sa.Column('discord_handle', sa.String(length=120), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role in ('member', 'fleet_lieutenant', 'fleet_admiral')", name='ck_fleet_memberships_role'),
    sa.CheckConstraint("status in ('pending', 'active', 'inactive')", name='ck_fleet_memberships_status'),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fleet_id', 'user_id', name='uq_fleet_membership_user'),
    sa.UniqueConstraint('user_id', name='uq_fleet_membership_single_user')
    )
    with op.batch_alter_table('fleet_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fleet_memberships_fleet_id'), ['fleet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_memberships_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_memberships_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_memberships_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fleet_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('forum_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_threads_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_threads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_threads_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_threads_title'), ['title'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('focus', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expectations', sa.Text(), nullable=True),
    sa.Column('activity_plan', sa.Text(), nullable=True),
    sa.Column('contact_note', sa.String(length=300), nullable=True),
    sa.Column('scheduled_start_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('min_ship_rate', sa.Integer(), nullable=True),
    sa.Column('max_ship_rate', sa.Integer(), nullable=True),
    sa.Column('allow_guests', sa.Boolean(), nullable=False),
    sa.Column('fleet_restriction', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status in ('open', 'full', 'closed')", name='ck_groups_status'),
    sa.CheckConstraint('max_members >= 2 and max_members <= 50', name='ck_groups_max_members'),
    sa.CheckConstraint('max_ship_rate is null or (max_ship_rate >= 1 and max_ship_rate <= 7)', name='ck_groups_max_ship_rate'),
    sa.CheckConstraint('min_ship_rate is null or (min_ship_rate >= 1 and min_ship_rate <= 7)', name='ck_groups_min_ship_rate'),
    sa.CheckConstraint('scheduled_end_at is null or scheduled_start_at is null or scheduled_end_at > scheduled_start_at', name='ck_groups_schedule_range'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_focus'), ['focus'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_scheduled_start_at'), ['scheduled_start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_title'), ['title'], unique=False)

    op.create_table('guides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guides_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guides_title'), ['title'], unique=False)

    op.create_table('registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('external_fleet_name', sa.String(length=120), nullable=True),
    sa.Column('fleet_id', sa.Integer(), nullable=True),
    sa.Column('wants_fleet_membership', sa.Boolean(), nullable=False),
    sa.Column('fleet_application_note', sa.Text(), nullable=True),
    sa.Column('fleet_availability', sa.String(length=240), nullable=True),
    sa.Column('fleet_preferred_ships', sa.String(length=300), nullable=True),
    sa.Column('fleet_timezone', sa.String(length=80), nullable=True),
    sa.Column('fleet_discord_handle', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status in ('pending', 'approved', 'rejected')", name='ck_registration_requests_status'),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fleet_id'], ['fleets.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registration_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_created_user_id'), ['created_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_fleet_id'), ['fleet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_reviewed_by_id'), ['reviewed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_username'), ['username'], unique=False)

    op.create_table('stored_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('usage_context', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stored_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_files_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_files_stored_name'), ['stored_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_stored_files_usage_context'), ['usage_context'], unique=False)

    op.create_table('build_item_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('effect_key', sa.String(length=80), nullable=False),
    sa.Column('effect_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['build_item_options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_id', 'effect_key', name='uq_build_item_effect_key')
    )
    with op.batch_alter_table('build_item_effects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_item_effects_effect_key'), ['effect_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_effects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_item_effects_option_id'), ['option_id'], unique=False)

    op.create_table('build_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('slot_type', sa.String(length=40), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity is null or quantity >= 1', name='ck_build_slots_quantity'),
    sa.CheckConstraint('slot_index >= 0', name='ck_build_slots_slot_index'),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['build_item_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_id', 'slot_type', 'slot_index', name='uq_build_slot_position')
    )
    with op.batch_alter_table('build_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_build_slots_build_id'), ['build_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_slots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_slots_option_id'), ['option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_build_slots_slot_type'), ['slot_type'], unique=False)

    op.create_table('forum_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['forum_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_posts_thread_id'), ['thread_id'], unique=False)

    op.create_table('group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('fleet_name', sa.String(length=120), nullable=True),
    sa.Column('ship_id', sa.Integer(), nullable=True),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('ship_name', sa.String(length=140), nullable=True),
    sa.Column('ship_rate', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('ship_rate is null or (ship_rate >= 1 and ship_rate <= 7)', name='ck_group_members_ship_rate'),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_members_build_id'), ['build_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_ship_id'), ['ship_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_user_id'), ['user_id'], unique=False)

    op.create_table('guide_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['stored_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guide_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guide_attachments_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_attachments_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_attachments_id'), ['id'], unique=False)

    op.create_table('guide_build_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guide_id'], ['guides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guide_id', 'build_id', name='uq_guide_build_reference')
    )
    with op.batch_alter_table('guide_build_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guide_build_references_build_id'), ['build_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_build_references_guide_id'), ['guide_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guide_build_references_id'), ['id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('external_fleet_name', sa.String(length=120), nullable=True),
    sa.Column('primary_fleet_membership_id', sa.Integer(), nullable=True),
    sa.Column('preferred_focus', sa.String(length=80), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_fleet_membership_id'], ['fleet_memberships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_primary_fleet_membership_id'), ['primary_fleet_membership_id'], unique=False)

    op.create_table('forum_post_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['stored_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forum_post_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_post_attachments_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_post_attachments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_post_attachments_post_id'), ['post_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_post_attachments_post_id'))
        batch_op.drop_index(batch_op.f('ix_forum_post_attachments_id'))
        batch_op.drop_index(batch_op.f('ix_forum_post_attachments_file_id'))

    op.drop_table('forum_post_attachments')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_primary_fleet_membership_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('guide_build_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guide_build_references_id'))
        batch_op.drop_index(batch_op.f('ix_guide_build_references_guide_id'))
        batch_op.drop_index(batch_op.f('ix_guide_build_references_build_id'))

    op.drop_table('guide_build_references')
    with op.batch_alter_table('guide_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guide_attachments_id'))
        batch_op.drop_index(batch_op.f('ix_guide_attachments_guide_id'))
        batch_op.drop_index(batch_op.f('ix_guide_attachments_file_id'))

    op.drop_table('guide_attachments')
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_ship_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_is_active'))
        batch_op.drop_index(batch_op.f('ix_group_members_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_build_id'))

    op.drop_table('group_members')
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_posts_thread_id'))
        batch_op.drop_index(batch_op.f('ix_forum_posts_id'))
        batch_op.drop_index(batch_op.f('ix_forum_posts_author_id'))

    op.drop_table('forum_posts')
    with op.batch_alter_table('build_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_slots_slot_type'))
        batch_op.drop_index(batch_op.f('ix_build_slots_option_id'))
        batch_op.drop_index(batch_op.f('ix_build_slots_id'))
        batch_op.drop_index(batch_op.f('ix_build_slots_build_id'))

    op.drop_table('build_slots')
    with op.batch_alter_table('build_item_effects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_item_effects_option_id'))
        batch_op.drop_index(batch_op.f('ix_build_item_effects_id'))
        batch_op.drop_index(batch_op.f('ix_build_item_effects_effect_key'))

    op.drop_table('build_item_effects')
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_files_usage_context'))
        batch_op.drop_index(batch_op.f('ix_stored_files_stored_name'))
        batch_op.drop_index(batch_op.f('ix_stored_files_owner_id'))
        batch_op.drop_index(batch_op.f('ix_stored_files_id'))

    op.drop_table('stored_files')
    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_requests_username'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_status'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_reviewed_by_id'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_id'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_fleet_id'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_created_user_id'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_created_at'))

    op.drop_table('registration_requests')
    with op.batch_alter_table('guides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guides_title'))
        batch_op.drop_index(batch_op.f('ix_guides_owner_id'))
        batch_op.drop_index(batch_op.f('ix_guides_is_published'))
        batch_op.drop_index(batch_op.f('ix_guides_id'))
        batch_op.drop_index(batch_op.f('ix_guides_category'))

    op.drop_table('guides')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_title'))
        batch_op.drop_index(batch_op.f('ix_groups_status'))
        batch_op.drop_index(batch_op.f('ix_groups_scheduled_start_at'))
        batch_op.drop_index(batch_op.f('ix_groups_owner_id'))
        batch_op.drop_index(batch_op.f('ix_groups_id'))
        batch_op.drop_index(batch_op.f('ix_groups_focus'))
        batch_op.drop_index(batch_op.f('ix_groups_expires_at'))

    op.drop_table('groups')
    with op.batch_alter_table('forum_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_threads_title'))
        batch_op.drop_index(batch_op.f('ix_forum_threads_owner_id'))
        batch_op.drop_index(batch_op.f('ix_forum_threads_id'))
        batch_op.drop_index(batch_op.f('ix_forum_threads_category'))

    op.drop_table('forum_threads')
    with op.batch_alter_table('fleet_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleet_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_fleet_memberships_status'))
        batch_op.drop_index(batch_op.f('ix_fleet_memberships_role'))
        batch_op.drop_index(batch_op.f('ix_fleet_memberships_id'))
        batch_op.drop_index(batch_op.f('ix_fleet_memberships_fleet_id'))

    op.drop_table('fleet_memberships')
    with op.batch_alter_table('fleet_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleet_events_title'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_start_at'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_owner_id'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_is_cancelled'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_id'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_end_at'))
        batch_op.drop_index(batch_op.f('ix_fleet_events_category'))

    op.drop_table('fleet_events')
    with op.batch_alter_table('builds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_builds_ship_id'))
        batch_op.drop_index(batch_op.f('ix_builds_owner_id'))
        batch_op.drop_index(batch_op.f('ix_builds_id'))
        batch_op.drop_index(batch_op.f('ix_builds_build_type'))
        batch_op.drop_index(batch_op.f('ix_builds_build_name'))

    op.drop_table('builds')
    with op.batch_alter_table('build_item_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_item_options_option_kind'))
        batch_op.drop_index(batch_op.f('ix_build_item_options_name'))
        batch_op.drop_index(batch_op.f('ix_build_item_options_id'))
        batch_op.drop_index(batch_op.f('ix_build_item_options_category_id'))

    op.drop_table('build_item_options')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_expires_at'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ships_rate'))
        batch_op.drop_index(batch_op.f('ix_ships_name'))
        batch_op.drop_index(batch_op.f('ix_ships_id'))

    op.drop_table('ships')
    with op.batch_alter_table('fleets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fleets_slug'))
        batch_op.drop_index(batch_op.f('ix_fleets_name'))
        batch_op.drop_index(batch_op.f('ix_fleets_id'))
        batch_op.drop_index(batch_op.f('ix_fleets_focus'))

    op.drop_table('fleets')
    with op.batch_alter_table('build_item_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_build_item_categories_key'))
        batch_op.drop_index(batch_op.f('ix_build_item_categories_id'))

    op.drop_table('build_item_categories')
    with op.batch_alter_table('app_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_logs_status_code'))
        batch_op.drop_index(batch_op.f('ix_app_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_app_logs_path'))
        batch_op.drop_index(batch_op.f('ix_app_logs_method'))
        batch_op.drop_index(batch_op.f('ix_app_logs_logger'))
        batch_op.drop_index(batch_op.f('ix_app_logs_level'))
        batch_op.drop_index(batch_op.f('ix_app_logs_id'))
        batch_op.drop_index(batch_op.f('ix_app_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_app_logs_client_ip'))

    op.drop_table('app_logs')
    # ### end Alembic commands ###
